clients/ios/ios_client/Apis/CoreApi.swift, clients/ios/ios_client/Coordinator.swift, clients/ios/ios_client/Screens/DebugView.swift, clients/ios/ios_client/Screens/ImportAccountView.swift, clients/ios/ios_client/Screens/ListView.swift
Adjusting the account import dialog since we changed the language/struct
=> iOS Fixing Up Account Import

containers/test.env
aka a waste of our github actions minutes
=> Clears test cert setting

server/src/files_db/connect.rs, server/src/index_db/create_file.rs, server/src/index_db/delete_file.rs, server/src/index_db/generate_version.rs, server/src/index_db/get_file_metadata.rs, server/src/index_db/get_public_key.rs, server/src/index_db/get_updates.rs, server/src/index_db/move_file.rs, server/src/index_db/new_account.rs, server/src/index_db/rename_file.rs, server/src/index_db/update_file_version.rs, server/src/services/change_file_content.rs, server/src/services/create_file.rs, server/src/services/delete_file.rs, server/src/services/get_public_key.rs, server/src/services/get_updates.rs, server/src/services/move_file.rs, server/src/services/new_account.rs, server/src/services/rename_file.rs
Each endpoint runs in one transaction; pattern that lets us manage consistency guarantees more easily. This is pre-work for #96 and #98.
=> Endpoint transactions

clients/cli/src/copy.rs, clients/cli/src/edit.rs, clients/cli/src/export.rs, clients/cli/src/import.rs, clients/cli/src/init.rs, clients/cli/src/list.rs, clients/cli/src/main.rs, clients/cli/src/new.rs, clients/cli/src/print.rs, clients/cli/src/remove.rs, clients/cli/src/status.rs, clients/cli/src/sync.rs, clients/cli/src/utils.rs, clients/cli/src/whoami.rs, core/src/lib.rs, core/src/model/crypto.rs, core/src/repo/file_metadata_repo.rs
+ No more race conditions
+ Can edit multiple files at once
+ List folders only
+ Corrected a few checks for pipe vs stdin
=> Cli improvements

containers/Dockerfile.android, containers/Dockerfile.cli, containers/Dockerfile.core, containers/Dockerfile.integration_tests, containers/Dockerfile.server, core/src/client.rs, core/src/lib.rs, core/src/service/account_service.rs, core/src/service/sync_service.rs, integration_tests/src/change_document_content_tests.rs, integration_tests/src/create_document_tests.rs, integration_tests/src/delete_document_tests.rs, integration_tests/src/get_document_tests.rs, integration_tests/src/get_public_key_tests.rs, integration_tests/src/get_updates_test.rs, integration_tests/src/lib.rs, integration_tests/src/move_document_tests.rs, integration_tests/src/new_account_tests.rs, integration_tests/src/rename_document_tests.rs
this pr deletes more code than it adds so just 👍 it
=> Compile time env var for api url

core/src/service/sync_service.rs, integration_tests/src/sync_service_tests.rs
Write a failing test
make the test pass
=> find a bug fix a bug

clients/cli/Cargo.lock, dev_utils/bump_aur_version.sh, dev_utils/release_linux_cli.sh, dev_utils/release_macos_cli_bump_brew.sh
=> Deployment automation

clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/FilesAdapter.kt, clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesActivity.kt, clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesFragment.kt, clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesViewModel.kt, clients/android/app/src/main/java/app/lockbook/loggedin/listfiles/ListFilesViewModelFactory.kt, clients/android/app/src/main/java/app/lockbook/loggedin/popupinfo/PopUpInfoActivity.kt, clients/android/app/src/main/java/app/lockbook/utils/Constants.kt, clients/android/app/src/main/res/drawable/ic_baseline_sort_by_alpha_24.xml, clients/android/app/src/main/res/menu/menu_list_files.xml, clients/android/app/src/main/res/menu/menu_text_editor.xml, clients/android/app/src/main/res/values/strings.xml
More options for sorting (close #196 )
=> Android sort

clients/windows/Core.cs, clients/windows/CoreModel.cs, clients/windows/FileExplorer.xaml, clients/windows/FileExplorer.xaml.cs, clients/windows/windows.csproj
There's "Syncing..." too but it happens too fast and can't get a screenshot (subtle flex).
closes #223
=> Show a nice call to action / sync status:

clients/cli/Cargo.lock, clients/cli/src/main.rs, clients/cli/src/utils.rs, core/Cargo.lock, core/Cargo.toml, core/Makefile, core/src/c_interface.rs, core/src/lib.rs, core/src/loggers.rs, core/src/model/state.rs, core/src/service/file_service.rs
Logging now goes to `output.log` and std out. It also has colors!
Set the env var `LOCKBOOK_DEBUG` to anything to have `DEBUG` level logs printed to standard out
Closes #121
=> File Backed Logging

clients/apple/Lockbook-iOS/AppDelegate.swift, clients/apple/Lockbook-iOS/Components/DocumentRow.swift, clients/apple/Lockbook-iOS/Components/FolderList.swift, clients/apple/Lockbook-iOS/Components/FolderRow.swift, clients/apple/Lockbook-iOS/Components/MonokaiButton.swift, clients/apple/Lockbook-iOS/Components/ProgressWidget.swift, clients/apple/Lockbook-iOS/Components/PullDownView.swift, clients/apple/Lockbook-iOS/Managers/ControllerView.swift, clients/apple/Lockbook-iOS/Managers/Coordinator.swift, clients/apple/Lockbook-iOS/Managers/LoginManager.swift, clients/apple/Lockbook-iOS/SceneDelegate.swift, clients/apple/Lockbook-iOS/Screens/CreateFileView.swift, clients/apple/Lockbook-iOS/Screens/FileBrowserView.swift, clients/apple/Lockbook-iOS/Screens/FileView.swift, clients/apple/Lockbook-iOS/Screens/SettingsView.swift, clients/apple/Lockbook-macOS/AppDelegate.swift, clients/apple/Lockbook-macOS/ContentView.swift, clients/apple/Lockbook-macOS/ItemView.swift, clients/apple/Lockbook-macOS/macos.entitlements, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/Util.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/FileMetadata.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/lockbook.xcodeproj/xcshareddata/xcschemes/Lockbook-iOS.xcscheme, clients/apple/lockbook.xcodeproj/xcshareddata/xcschemes/Lockbook-macOS.xcscheme, clients/cli/Cargo.lock, core/Cargo.lock, core/src/lib.rs, core/src/loggers.rs, server/Cargo.lock
Closes 261
- New colors
- File creation screen
- Folder view
- Path snacks
- Black/White navigation button
- Long press for go-to-root
UI Change Slideshow:
=> iOS Bug Fixes Round 1

core/tests/account_service_tests.rs, server/src/file_service.rs
=> server: Empty usernames should be invalid.

.github/workflows/build.yml
Stop the notifications on builds!
=> Stop Spamming Slack

clients/windows/FileExplorer.xaml, clients/windows/Package.appxmanifest, clients/windows/windows.csproj, dev_utils/create_core_for_windows.bat, dev_utils/create_windows_app_bundle.bat, docs/README.md, docs/building.md, public_site/config.toml
+ Closes #228 
+ Closes #316
+ Closes #269
Creates a release: https://github.com/lockbook/lockbook/releases/tag/windows-0
Updates our website and readme
=> Windows Work

clients/linux/src/backend.rs, clients/linux/src/gui.rs, clients/linux/src/intro.rs
As the files are synced, their paths show up underneath the "Importing account..." loading caption.
Closes #377.
=> linux: Show sync progress while importing account.

clients/linux/Cargo.lock, clients/linux/Cargo.toml, clients/linux/src/gui.rs, clients/linux/src/main.rs, clients/linux/src/menubar.rs, clients/linux/src/messages.rs
=> linux: Add the About dialog which opens via the new 'Help -> About' menuitem.

clients/linux/src/account.rs
* The Account screen consists of a `Sidebar` and an `Editor`. Break the `Editor` component into a `HeaderBar` and `WorkSpace`.
* Wrap the `WorkSpace` in a `GtkScrolledView` so that the textarea, for example, scrolls with excess lines instead of expanding.
* Align the naming and structuring pattern.
* Add space after number of files not synced.
* Misc.
=> linux: Refactor the Account screen code.

clients/apple/Shared/Book/ActionsView.swift, clients/apple/lockbook.xcodeproj/project.pbxproj
Self explanatory, SwiftUI only!
=> Missing Delete error and dismiss

.gitignore, dev_utils/create_core_for_windows.bat
1. don't commit the dll
2. update the script
3. gitignore the dll
=> Cleanup windows scripts

clients/linux/res/app.css, clients/linux/src/account.rs, clients/linux/src/app.rs, clients/linux/src/backend.rs, clients/linux/src/error.rs, clients/linux/src/filetree.rs, clients/linux/src/main.rs, clients/linux/src/messages.rs, clients/linux/src/util.rs
=> linux: Implement rename and restructure error handling

core/src/lib.rs
The `UiError` variant of the `Error` enum is used throughout `lib.rs` (almost 50 times) as `Error::UiError`. That's two explicit references to the fact that it's an Error, not counting that the thing that comes next almost always has Error in the name as well (ex; `Error::UiError(MigrationError::{Variant})`.
Therefore, I tidied up by adding a `use` statement for the `UiError` variant. This way, much like for the `Result` and `Option` enums where we can just use `Ok, Err` and `Some, None` respectively, we can just say `UiError(Error)` for `Error::UiError`.
The other solution I decided against (for a couple reasons) was changing the `UiError` variant to be just `Ui` so statements would read like `Error::Ui(Error)`.
=> core: Refactor to use the UiError variant of the Error enum.

clients/linux/src/backend.rs
I realized instead of using the `errs` module pattern (which isolates the error mapping functions so imports and code isn't cluttered with numerous and lengthy error enuming), I could create a macro that accomplishes the same thing without the module boilerplate.
=> linux: Simplify the core error handling pattern even more.

core/src/lib.rs
The `Unexpected` variant of core's `Error` enum takes a `String`. In _every_ instance that `Error::Unexpected` is used, it is provided a `String` that is constructed via the `format!` macro, making the pattern `Error::Unexpected(format!(...))` appear quite often.
This PR creates and employs a macro with the same signature as the `format!` macro, but that returns the repetitive Unexpected error building pattern, so:
* `Error::Unexpected(format!(...))` is now just `unexpected!(...)`, and
* this still allows for a simple string literal to be passed as well: `unexpected!("error message")`
=> core: Create a macro for the 'Error::Unexpected(format!())' pattern.

clients/linux/src/account.rs, clients/linux/src/app.rs, clients/linux/src/backend.rs, clients/linux/src/error.rs, clients/linux/src/filetree.rs, clients/linux/src/intro.rs, clients/linux/src/messages.rs, clients/linux/src/util.rs
=> linux: Refactor code around syncing, its channel design, and the UI.

clients/windows/lockbook/Settings.xaml, clients/windows/lockbook/Settings.xaml.cs, clients/windows/lockbook/lockbook.csproj
=> windows: export account string + qr code

clients/windows/core/Core.cs, clients/windows/core/CoreModel.cs, clients/windows/lockbook/App.xaml.cs, clients/windows/lockbook/FileExplorer.xaml.cs, clients/windows/lockbook/Startup.xaml, clients/windows/lockbook/Startup.xaml.cs, clients/windows/lockbook/lockbook.csproj, clients/windows/test/CoreServiceTest.cs
=> windows: migrations

core/tests/sync_service_tests.rs
* Primarily, create a macro for asserting the number of work units.
* A couple other small tidies.
=> core: clean sync tests

clients/android/gradle/wrapper/gradle-wrapper.properties
=> android: update gradle to 6.7

clients/linux/src/app.rs, clients/linux/src/menubar.rs
Clippy updated ands is unhappy, just making it happy.
=> linux: make clippy happy

clients/cli/src/main.rs, clients/cli/src/remove.rs
Removing a folder will not show the total number of folders and documents being removed, just the documents
fixes #505
=> cli: removing a folder will only show the number of documents being removed

clients/windows/core/Core.cs, clients/windows/core/CoreModel.cs, clients/windows/core/Utils.cs, clients/windows/lockbook/App.xaml, clients/windows/lockbook/App.xaml.cs, clients/windows/lockbook/FileExplorer.xaml, clients/windows/lockbook/FileExplorer.xaml.cs, clients/windows/lockbook/Properties/AssemblyInfo.cs, clients/windows/lockbook/Settings.xaml, clients/windows/lockbook/Settings.xaml.cs, clients/windows/lockbook/SignUp.xaml, clients/windows/lockbook/SignUp.xaml.cs, clients/windows/lockbook/Startup.xaml, clients/windows/lockbook/Startup.xaml.cs, clients/windows/test/CoreServiceTest.cs, core/src/c_interface.rs
=> windows: refactor, utf-8 ffi, prompt for update

clients/android/app/src/main/res/layout/grid_layout_file_item.xml
=> no shadows for light mode tiles

clients/android/app/src/main/java/app/lockbook/model/HandwritingEditorViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/HandwritingEditorActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt
=> android: fixed crashes when a user exits while a drawing is still loading

.github/workflows/integration.yml
=> infra: prep containers now run in parallel

docs/README.md, docs/installing-iOS-iPadOS.md, docs/installing-macos.md
Preview: https://github.com/lockbook/lockbook/tree/readme-updates#feature-matrix
=> docs: add feature matrix

clients/apple/Notepad/Sources/NotepadSwift/Notepad.swift, clients/apple/Shared/Components/NotepadView.swift, clients/apple/Shared/Views/AccountView.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift, docs/README.md
- Updates readme matrix
- Uses human readable string usage from core #608
- Styles markdown document on open fixes #630
=> Apple Human Readable String and Readme

clients/android/app/src/main/java/app/lockbook/screen/TextEditorActivity.kt
=> android: a document that opens and fails to load text will delete everything on exit

clients/android/app/src/main/java/app/lockbook/screen/DrawingActivity.kt, clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt, clients/android/app/src/main/res/layout/activity_drawing.xml, clients/android/app/src/main/res/values-night/colors.xml, clients/android/app/src/main/res/values/colors.xml, clients/android/app/src/main/res/values/styles.xml
In this PR, the drawingview now has a white background in light mode. Also, the loading screen is white in light mode now.
Tablet Screenshot
<details>
</details>
fixes #624
=> android: white drawing background in light mode

clients/apple/iOS/FileListView.swift
=> apple: scroll move view

clients/android/app/src/main/java/app/lockbook/App.kt, clients/android/app/src/main/java/app/lockbook/model/AlertModel.kt, clients/android/app/src/main/java/app/lockbook/model/BiometricModel.kt, clients/android/app/src/main/java/app/lockbook/model/FileModel.kt, clients/android/app/src/main/java/app/lockbook/model/GeneralViewAdapter.kt, clients/android/app/src/main/java/app/lockbook/model/ListFilesViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/SyncModel.kt, clients/android/app/src/main/java/app/lockbook/screen/DrawingActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/ImportAccountActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/InitialLaunchFigureOuter.kt, clients/android/app/src/main/java/app/lockbook/screen/ListFilesActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt, clients/android/app/src/main/java/app/lockbook/screen/LogActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/NewAccountActivity.kt, clients/android/app/src/main/java/app/lockbook/screen/SettingsFragment.kt, clients/android/app/src/main/java/app/lockbook/screen/TextEditorActivity.kt, clients/android/app/src/main/java/app/lockbook/ui/CreateFileDialogFragment.kt, clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt, clients/android/app/src/main/java/app/lockbook/ui/MoveFileDialogFragment.kt, clients/android/app/src/main/java/app/lockbook/ui/RenameFileDialogFragment.kt, clients/android/app/src/main/java/app/lockbook/util/Errors.kt
In this PR, I cleaned up and consolidated different parts of the App. 
fixes #595
=> android: refactor code

clients/linux/Cargo.lock, clients/linux/Cargo.toml, clients/linux/src/app.rs
<details>
</details>
fixes #675
=> linux: have a window icon

clients/linux/src/filetree.rs, containers/Dockerfile.cli, containers/Dockerfile.core, containers/Dockerfile.linux, containers/Dockerfile.server, core/src/service/file_encryption_service.rs, core/src/storage/db_provider.rs
I fixed the new lint errors that have been popping up.
fixes #681
=> backend: fix lint errors

clients/linux/src/app.rs
=> linux: a deleted file does not keep its editor open

clients/linux/src/account.rs
<details>
</details>
fixes #693
=> linux: file tree is scrollable

clients/linux/src/app.rs
=> linux: renaming a file updates the header and window title

clients/apple/Notepad/Sources/NotepadSwift/Markdown/MarkdownNode.swift, clients/apple/Shared/Components/NotepadView.swift, clients/apple/Shared/Config/LockbookMarkdownConfig.swift, clients/apple/lockbook.xcodeproj/project.pbxproj
- Supports highlighting of links: `[henlo](ftp://uranus.net)`
- macOS editor now supports "undo"
=> apple: April 2021 Tweaks 2

docs/lifecycle.md
@SmailBarkouch this is how you should handle #695 when you get to it
=> docs: how periodic events should be handled by clients

clients/linux/src/app.rs, clients/linux/src/messages.rs
=> linux: background sync and save wont start if there is no account

clients/linux/Cargo.lock, clients/linux/Cargo.toml, utils/dev/build-lockbook-debian/ppa-lockbook-desktop/debian/control, utils/dev/build-lockbook-debian/ppa-lockbook-desktop/debian/rules, utils/dev/build-lockbook-debian/ppa-lockbook/debian/control, utils/dev/build-lockbook-debian/ppa-lockbook/debian/rules, utils/dev/build-lockbook-debian/release_linux_cli_debian.sh, utils/dev/build-lockbook-debian/release_linux_desktop_debian.sh
=> infra: fixed debian release scripts and source packages

core/libs/models/src/api.rs, core/src/service/sync_service.rs, core/tests/sync_service_tests.rs, server/admin/Cargo.lock, server/index_db/create_db.sql, server/server/sqlx-data.json, server/server/src/file_index_repo.rs, server/server/src/file_service.rs
=> server: don't allow new files in deleted folders

clients/linux/Cargo.lock, clients/linux/src/account.rs
=> linux: resolved document scrolling idiosyncrasies

clients/android/app/build.gradle, clients/linux/Cargo.lock, utils/dev/bump_aur_version.sh, utils/dev/deploy_public_site.sh, utils/dev/measure_coverage.sh, utils/dev/release_android.sh, utils/dev/release_linux_cli.sh, utils/dev/release_macos_cli_bump_brew.sh, utils/dev/run_server_with_devtest_dbs.sh, utils/dev/run_server_with_qa_dbs.sh
=> infra: fix dev scripts and android release apk is installable on debug devices

core/src/lib.rs, core/src/service/drawing_service.rs
=> core: split drawing error

clients/cli/src/export_drawing.rs, core/src/c_interface.rs, core/src/lib.rs, core/src/service/drawing_service.rs
=> core: added optional render theme

clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt, clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt, clients/android/app/src/main/res/layout/activity_drawing.xml
=> android: no more configuration change crashes in DrawingView

Cargo.lock, clients/linux/Cargo.toml, clients/linux/src/account.rs, containers/Dockerfile.linux, docs/guides/building.md, utils/dev/build-lockbook-debian/ppa-lockbook-desktop/debian/control, utils/dev/build-lockbook-debian/ppa-lockbook-desktop/debian/rules, utils/dev/build-lockbook-debian/ppa-lockbook/debian/rules
=> linux: spell check

core/src/lib.rs, core/src/model/client_conversion.rs, core/src/repo/account_repo.rs, core/src/repo/db_version_repo.rs, core/src/repo/document_repo.rs, core/src/repo/file_metadata_repo.rs, core/src/repo/local_changes_repo.rs, core/src/repo/local_storage.rs, core/src/service/account_service.rs, core/src/service/db_state_service.rs, core/src/service/drawing_service.rs, core/src/service/file_compression_service.rs, core/src/service/file_encryption_service.rs, core/src/service/file_service.rs, core/src/service/integrity_service.rs, core/src/service/path_service.rs, core/src/service/sync_service.rs, core/src/service/usage_service.rs, core/tests/account_service_tests.rs, core/tests/file_service_tests.rs
introduces `CoreError` which virtually every function returns instead of returning individual errors
=> core: error simplification

clients/apple/iOS/Drawing/DrawingLoader.swift
=> apple: remove debug info

clients/linux/src/account.rs, clients/linux/src/app.rs, clients/linux/src/backend.rs, clients/linux/src/filetree.rs
=> linux: added drag and drop

clients/cli/src/copy.rs
=> cli: able to copy bytes in cli

clients/linux/src/app.rs, clients/linux/src/filetree.rs, clients/linux/src/menubar.rs
=> linux: filetree tweaks and icons

.github/workflows/monitor.yml, server/server/src/main.rs, utils/dev/page_if_server_down.sh
=> server: allow un-auth'd requests for build info for monitoring purposes

core/tests/file_service_tests.rs, core/tests/get_usage_tests.rs, core/tests/storage_backend_tests.rs
=> core: removed all the variables holding config references

clients/android/app/src/main/res/menu/menu_list_files.xml, clients/android/app/src/main/res/values/strings.xml
=> android: fixed layout menu hint

clients/android/app/src/main/java/app/lockbook/model/TextEditorViewModel.kt
=> android: save on exit

clients/linux/src/account.rs, clients/linux/src/app.rs, clients/linux/src/backend.rs, clients/linux/src/error.rs, clients/linux/src/filetree.rs, clients/linux/src/messages.rs, clients/linux/src/util.rs
In this PR I added the ability to paste and drop images and files into gtksourceview. 
When an image is pasted or dropped it will automatically be imported and a link to it will be added in the document. The same goes for uris.
=> linux: paste and drop images and uris into gtksourceview and have them create links

clients/cli/src/copy.rs, clients/cli/src/error.rs, clients/linux/src/backend.rs, core/src/lib.rs, core/src/service/import_export_service.rs
=> core: better import collision error

clients/apple/iOS/Drawing/DrawingView.swift
This whole bit does need to be reworked, but this fixes a regression introduced in the refactor
=> apple: fix drawings

clients/apple/Shared/Components/BottomBar.swift, clients/apple/Shared/Stateful Logic/AccountService.swift, clients/apple/Shared/Stateful Logic/OnboardingState.swift, clients/apple/Shared/Stateful Logic/SyncService.swift
=> apple: properly deal with offline sync attempts

docs/design-ux/search.md
this RFC specs out the various ways we're going to perform search within lockbook.
=> docs: search rfc

docs/design-ux/file-types.md
This RFC tries to figure out how we deal with files we're not going to engineer explicit support for.
=> docs: file-types rfc

clients/cli/src/backup.rs, clients/cli/src/calculate_usage.rs, clients/cli/src/copy.rs, clients/cli/src/edit.rs, clients/cli/src/export_drawing.rs, clients/cli/src/export_private_key.rs, clients/cli/src/import_private_key.rs, clients/cli/src/list.rs, clients/cli/src/main.rs, clients/cli/src/move_file.rs, clients/cli/src/new.rs, clients/cli/src/new_account.rs, clients/cli/src/print.rs, clients/cli/src/remove.rs, clients/cli/src/rename.rs, clients/cli/src/status.rs, clients/cli/src/sync.rs, clients/cli/src/utils.rs, clients/cli/src/validate.rs, clients/cli/src/whoami.rs, core/src/lib.rs
=> cli: eliminate all non-main.rs instances of -> !

clients/cli/src/error.rs, clients/cli/src/validate.rs, core/src/service/integrity_service.rs
=> cli: better handling of unreadable events

utils/dev/release_macos_cli_bump_brew.sh
update release scripts to generate a single binary for cli on the 2 apple platforms
=> infra: universal macos cli + fix brew release scripts

clients/windows/core/CoreModel.cs, clients/windows/core/CoreService.cs, clients/windows/lockbook/FileExplorer.xaml.cs, clients/windows/lockbook/Package.appxmanifest, clients/windows/lockbook/SignUp.xaml.cs, clients/windows/lockbook/lockbook.csproj, clients/windows/test/CoreServiceTest.cs, utils/dev/create_core_for_windows_aarch64.bat, utils/dev/create_windows_app_bundle.bat
also some config changes for release builds
=> windows: fix core integration

clients/windows/core/CoreModel.cs, clients/windows/core/Draw.cs, clients/windows/lockbook/Draw.cs, clients/windows/lockbook/FileExplorer.xaml, clients/windows/lockbook/FileExplorer.xaml.cs, clients/windows/lockbook/lockbook.csproj, clients/windows/test/DrawTest.cs, core/src/external_interface/c_interface.rs, core/src/service/file_service.rs
https://user-images.githubusercontent.com/6198756/144779523-ff95bde9-2d17-4949-b180-ab4ecefdf365.mp4
fixes #312
=> windows: drawing

core/src/service/file_encryption_service.rs
Retrieving an `AESKey` for a file required decrypting the same parents repeatedly. Caching already decrypted keys saves a lot of time.
An instance of this improvement is with `lockbook list`.
Before:
```
./lockbook list  0.10s user 0.01s system 98% cpu 0.110 total
```
After:
```
./lockbook list  0.01s user 0.01s system 98% cpu 0.018 total
```
=> core: create key_cache to avoid redundant decryption

clients/linux/src/app.rs, clients/linux/src/settings.rs
This PR moves the settings code from app into settings. No UI changes.
=> linux: organize settings ui code

Cargo.lock, clients/apple/Shared/Stateful Logic/DocumentLoader.swift, clients/apple/Shared/Stateful Logic/OnboardingState.swift, clients/apple/Shared/Views/DocumentView.swift, clients/apple/Shared/Views/FileCell.swift, clients/apple/Shared/Views/OnboardingView.swift, clients/apple/iOS/FileListView.swift, clients/apple/iOS/NewFileSheet.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/macOS/OutlineView/OutlineRow.swift, core/Cargo.toml, core/src/model/errors.rs, core/src/pure_functions/drawing.rs, core/src/repo/account_repo.rs, core/src/repo/last_updated_repo.rs, core/src/service/account_service.rs, core/src/service/db_state_service.rs, core/src/service/drawing_service.rs, core/src/service/file_encryption_service.rs, core/src/service/file_service.rs, core/src/service/import_export_service.rs, core/src/service/path_service.rs, core/src/service/usage_service.rs
+ all non-changes
+ fix double commits by using newer onsubmit
+ fix documents that got stuck in a loading state due to failures
+ empty documents that are drawings are represented as `Drawing::default()`
+ more logs in a handful of places
+ debug logs when unexpecteds are returned out of core
=> apple: new-file bug-fixes

clients/linux/src/app.rs, clients/linux/src/main.rs, clients/linux/src/syncing.rs
Move syncing related UI code out of `app.rs`
=> linux: organize syncing related code

clients/linux/src/account.rs, clients/linux/src/app.rs, clients/linux/src/filetree.rs
This is a tidy PR focused on the `filetree.rs` code.
=> linux: refactor filetree code

docs/design-tech/sync.md
=> docs: wrap sync docs

core/tests/switch_account_tier_test.rs
This is more what I was going for, what do you think?
=> keep the loop but do a match statement on the first level

clients/apple/Editor/TextKit/IndexConverter.swift, clients/apple/iOS/FileListView.swift, clients/apple/lockbook.xcodeproj/project.pbxproj
1. fixes #1011 
2. fixes #1012
=> apple: 2 bugfixes

clients/apple/Editor/TextKit/Parser.swift, clients/apple/Shared/Stateful Logic/SyncService.swift, clients/apple/Shared/Views/BottomBar.swift
=> apple: handle upgrades better

containers/Dockerfile.admin_cli, containers/Dockerfile.cli, containers/Dockerfile.core, containers/Dockerfile.linux, containers/Dockerfile.performance, containers/Dockerfile.server, core/libs/models/src/file_metadata.rs, core/src/external_interface/c_interface.rs, core/src/model/filename.rs, core/src/pure_functions/drawing.rs, core/src/pure_functions/files.rs, core/src/service/test_utils.rs, server/admin/src/delete_account.rs, server/server/src/config.rs
=> infra: upgrade to rust 1.59 and fix all clippy warnings

core/src/lib.rs, core/src/service/log_service.rs
=> core+server: cleanup logs some more

clients/cli/src/new.rs
=> cli: delete a new file if it's canceled / aborted

core/libs/models/src/api.rs, core/libs/test_utils/src/lib.rs, core/src/service/api_service.rs, core/tests/delete_file_tests.rs, core/tests/exhaustive_sync/experiment.rs, core/tests/sync_service_tests.rs, server/admin/src/delete_account.rs, server/server/src/account_service.rs, server/server/src/config.rs, server/server/src/file_service.rs, utils/dev/run-server.sh
+ [x] Fix db equality checks
+ [x] Properly purge accounts when server is running non-prod
+ [x] Write a failing test surrounding a file server thinks core should have pruned
+ [x] fix said file error
+ [x] Investigate a stuck fuzzer run
=> server: fuzzer driven development

clients/apple/Editor/TextKit/IndexConverter.swift, clients/apple/macOS/FileTree/TreeView.swift
=> apple: fix editor bugs

clients/apple/Shared/LockbookApp.swift, clients/apple/iOS/Info.plist
=> apple: fixes #1056

Cargo.lock, core/Cargo.toml, core/libs/crypto/Cargo.toml, core/libs/models/Cargo.toml, server/server/Cargo.toml
This reverts commit 0ea8ba483ee732eee30940390e73a6ce1e8ea108.
=> revert "core,server: upgrade libsecp256k1 dependency (#1138)"

clients/linux/lb-api/src/lib.rs, clients/linux/src/app/imp_open_file.rs
=> linux: open .draw documents

clients/android/app/src/main/res/layout/fragment_text_editor.xml
=> android: fix text editor width

docs/README.md, docs/guides/install/cli.md, public_site/index.html, public_site/styles.css
+ fixes: #1019
+ fixes #1197
+ fixes: #1018
+ fixes: #990
=> docs: misc fixes

clients/cli/src/main.rs
=> cli: simply use LOCKBOOK_PATH as is if it is set

clients/cli/src/main.rs
=> cli: no hyphens

clients/android/app/src/main/java/app/lockbook/model/ImportAccountViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/ImportAccountActivity.kt, clients/android/app/src/main/res/layout/activity_import_account.xml, clients/android/app/src/main/res/values/strings.xml
=> android: show import sync errors

clients/android/app/src/main/java/app/lockbook/model/MoveFileViewModel.kt
=> android: fix parent folder icon in move file dialog

clients/android/app/src/main/java/app/lockbook/model/FilesListViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/StateViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt, clients/android/app/src/main/res/values/strings.xml
=> android: basic quick notes

clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt
=> android: fix document icons

clients/android/app/src/main/java/app/lockbook/model/FilesListViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/MainScreenActivity.kt
=> android: close editor when open file is deleted

server/server/src/router_service.rs
before (during heavy concurrent load): 
disaster: you can see that there are multiple overlapping pieces of metadata with each log entry.
after:
I misread the docs here: https://docs.rs/tracing/latest/tracing/struct.Span.html#method.enter
It says `in_scope` is for _synchronous_ code.
fixes #1250
=> server: fix async log spans

clients/cli/src/debug.rs, core/libs/shared/src/access_info.rs, core/libs/shared/src/core_ops.rs, core/libs/shared/src/core_tree.rs, core/libs/shared/src/file_like.rs, core/libs/shared/src/file_metadata.rs, core/libs/shared/src/lazy.rs, core/libs/shared/src/lib.rs, core/libs/shared/src/path_ops.rs, core/libs/test_utils/src/lib.rs, core/src/model/errors.rs, core/src/service/document_service.rs, core/src/service/drawing_service.rs, core/src/service/file_service.rs, core/src/service/import_export_service.rs, core/src/service/integrity_service.rs, core/src/service/path_service.rs, core/src/service/search_service.rs, core/src/service/share_service.rs, core/src/service/sync_service.rs, core/src/service/usage_service.rs, core/tests/integrity_tests.rs, core/tests/sharing_tests.rs, server/server/src/file_service.rs
done: prevent users from performing invalid operations on one device
todo: resolve conflicts that arise when performing sharing operations across devices
=> core: sharing operation error handling

Cargo.lock, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/cli/Cargo.toml, clients/linux/Cargo.toml, core/Cargo.toml, server/server/Cargo.toml, server/server/src/lib.rs
=> bump versions

utils/dev-tool/src/main.rs, utils/dev-tool/src/server.rs, utils/dev-tool/src/utils.rs
=> infra: fix CI

server/server/src/main.rs
=> server: page on incomplete write

.github/workflows/integration.yml, core/tests/exhaustive_sync/trial.rs
=> infra: set rust version in ci to 1.63

clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt
=> android: fix folders not showing

utils/dev-tool/src/server.rs
=> infra: ci was running the wrong server

utils/dev/create_core_for_windows.bat, utils/dev/create_core_for_windows_aarch64.bat, utils/dev/create_windows_app_bundle.bat
Should have been a part of https://github.com/lockbook/lockbook/pull/1284
=> infra: delete old windows scripts

Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/account/modals/help.rs, clients/egui/src/account/modals/new_file.rs, clients/egui/src/account/modals/settings/account_tab.rs, clients/egui/src/account/syncing.rs, clients/egui/src/account/tabs/markdown/mod.rs, clients/egui/src/main.rs, clients/egui/src/widgets/subscription.rs
https://github.com/emilk/egui/releases/tag/0.19.0
=> egui: upgrade from 0.18.0 to 0.19.0

Cargo.lock, core/Cargo.toml, core/libs/shared/Cargo.toml, core/src/model/drawing.rs
I upgraded some deps to cut down on the total number of things we have to compile. Info in each commit message (will be rebase merged).
=> core,shared: upgrade some deps

clients/android/app/src/main/java/app/lockbook/ui/UsageBarPreference.kt, clients/android/app/src/main/res/layout/activity_upgrade_account.xml, clients/android/app/src/main/res/values/strings.xml, clients/egui/build.rs, clients/linux/src/ui/usage_settings.rs, clients/linux/src/ui/usage_upgrade.rs, docs/README.md, docs/design-tech/billing.md, public_site/index.html, server/server/src/lib.rs
=> all: change mentions of premium cost to 2.99 and premium data cap to 30 gb

clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt, clients/android/app/src/main/java/app/lockbook/model/FileModel.kt, clients/android/app/src/main/java/app/lockbook/model/MoveFileViewModel.kt, core/libs/shared/src/core_ops.rs, core/src/service/file_service.rs, core/tests/sharing_tests.rs
=> core, android: fix move and resolve links in get_children

clients/egui/src/account/modals/mod.rs, clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/theme/icons.rs
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Closes #1311.
=> egui: polish settings tabs

clients/apple/Editor/TextKit/Storage.swift, clients/apple/Editor/macOS/CustomNSTextView.swift, clients/apple/Shared/Stateful Logic/SyncService.swift
+ [x] https://github.com/lockbook/lockbook/issues/1337
+ [x] https://github.com/lockbook/lockbook/issues/1339
+ [x] https://github.com/lockbook/lockbook/issues/1209
=> Assorted apple bugfixes

clients/android/app/src/main/java/app/lockbook/model/FilesListViewModel.kt, clients/android/app/src/main/java/app/lockbook/util/Errors.kt
=> android: stop offline spam

server/server/src/file_service.rs
only construct the ServerTree for the user making the request
=> server: get-updates optimization

clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt, clients/android/app/src/main/java/app/lockbook/model/DetailsScreenLoaderViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/DrawingViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/StateViewModel.kt, clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt, clients/android/app/src/main/java/app/lockbook/util/Errors.kt, clients/android/app/src/main/res/values/strings.xml, clients/android/core/src/main/java/app/lockbook/core/core.kt, core/libs/shared/src/drawing.rs, core/src/external_interface/java_interface.rs, core/src/model/drawing.rs, core/tests/drawing_tests.rs
=> android: fixed android crashes from egui drawings

core/libs/shared/src/file_metadata.rs, core/libs/shared/src/secret_filename.rs, core/libs/shared/src/signed_file.rs
=> doc: partial eq

clients/admin/src/main.rs, core/libs/shared/src/api.rs, core/libs/shared/src/core_ops.rs, core/src/lib.rs, core/src/model/errors.rs, core/src/service/admin_service.rs, core/src/service/file_service.rs, core/src/service/log_service.rs, server/server/src/account_service.rs, server/server/src/document_service.rs, server/server/src/error_handler.rs, server/server/src/file_service.rs, server/server/src/loggers.rs, server/server/src/router_service.rs
=> core, server: visibility investments

clients/admin/src/account.rs, clients/admin/src/disappear.rs, clients/admin/src/main.rs, clients/admin/src/validate.rs, core/libs/shared/src/api.rs, core/src/lib.rs, core/src/model/errors.rs, core/src/service/admin_service.rs, server/server/src/error_handler.rs, server/server/src/file_service.rs, server/server/src/router_service.rs
+ categorized commands into their own files
+ properly distinguish between validating a single account and the server
+ author a server wide validation which makes sure the server is not in an invalid state (checks documents & indexes)
+ fixes  #1374
=> admin: server-wide validations

clients/admin/src/info.rs, clients/admin/src/main.rs, core/libs/shared/src/api.rs, core/src/lib.rs, core/src/model/errors.rs, core/src/service/admin_service.rs, server/server/src/error_handler.rs, server/server/src/file_service.rs, server/server/src/router_service.rs
run on my root:
```
❯ admin file-info 77e2bded-aada-45bf-bfce-777488ec1b8d
TREE                                                        TYPE|HMAC|DEL|SHARE|MODIFIED
77e2bded-aada-45bf-bfce-777488ec1b8d                        dir |none|no |no   |1 month ago
├── 8e3bdd63-3f30-4399-89ac-b28978557698                    dir |none|no |no   |1 month ago
│   ├── aef91c36-43f3-4fbc-a9ee-22c60093d3c1                dir |none|no |no   |1 month ago
│   │   ├── e2bb6f0e-78cf-408b-a8e4-616622da8e70            doc |some|no |no   |1 month ago
│   │   ├── 96bb4220-5dc7-419c-916f-96478f37b235            doc |some|no |no   |1 month ago
│   │   ├── 9d0a10f9-1619-4be2-867f-4461ba1d4b35            doc |some|no |no   |3 days ago
│   │   ├── 3761cb51-433c-41ca-afe5-642fa88eb37c            doc |some|no |no   |1 …
```
=> admin: print tree context for file id

clients/admin/src/info.rs, core/src/lib.rs
```
id:			38a547b3-3889-4b10-a853-70e43368f55c
file_type:		Folder
parent:			e884f84a-e31d-4aae-a048-1ae1b68b3f28
owner:			parth
explicitly_deleted:	false
document_hmac:		false
user_access_keys:
->	encrypted_by: parth
encrypted_for: smail
mode: Write
deleted: false
->	encrypted_by: parth
encrypted_for: steve
mode: Write
deleted: false
->	encrypted_by: parth
encrypted_for: travis
mode: Write
deleted: false
TREE                                                        TYPE|HMAC|DEL|SHARE|MODIFIED
201a4ace-8c36-4eae-b982-181816a24b5d                        dir |none|no |no   |1 month ago
└── e884f84a-e31d-4aae-a048-1ae1b68b3f28                    dir |none|no |no   |1 month ago
└── 38a547b3-3889-4b10-a853-70e43368f55c                dir |none|no |yes  |4 days ago
├── …
```
=> admin: additional file info

clients/android/app/src/main/java/app/lockbook/model/SearchDocumentsViewModel.kt, core/src/service/search_service.rs, core/tests/search_service_tests.rs
=> android, core: search fix

core/src/service/search_service.rs, core/tests/search_service_tests.rs
=> core: fix basic search errors with links

clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Views/BookView.swift, clients/apple/Shared/Views/NewFileSheet.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/lockbook.xcworkspace/xcshareddata/swiftpm/Package.resolved
fixes #1107 
<details>
https://user-images.githubusercontent.com/20663038/197412474-e051c886-0cec-45b0-bb25-a0926181a17a.MOV
</details>
<details>
https://user-images.githubusercontent.com/20663038/197413409-ef9ad906-df57-421b-b2d9-a367a2bff873.MOV
</details>
<details>
https://user-images.githubusercontent.com/20663038/197414330-50ea424e-bfe7-4226-a642-d2671a87ed94.mov
</details>
=> apple: post file action niceness

clients/apple/Shared/Views/BookView.swift, clients/apple/Shared/Views/NewFileSheet.swift, clients/apple/iOS/OutlineView/SheetState.swift
=> apple: fix selected file types error

core/libs/shared/src/core_ops.rs, core/libs/shared/src/core_tree.rs, core/libs/shared/src/lazy.rs, core/libs/shared/src/path_ops.rs, core/libs/shared/src/staged.rs, core/libs/shared/src/tree_like.rs, core/libs/shared/src/validate.rs, core/libs/shared/tests/tree_composition_tests.rs, core/libs/shared/tests/tree_tests.rs, core/libs/test_utils/src/assert.rs, core/src/service/document_service.rs, core/src/service/file_service.rs, core/src/service/import_export_service.rs, core/src/service/integrity_service.rs, core/src/service/path_service.rs, core/src/service/search_service.rs, core/src/service/share_service.rs, core/src/service/sync_service.rs, core/src/service/usage_service.rs, core/tests/integrity_tests.rs, core/tests/validate_tests.rs
* separate mutable StagedTree functions
* remove StagedTreeRef
* StagedTree accepts immutable staged
=> core (refactor): StagedTree updates

.github/workflows/integration.yml, Cargo.lock, utils/dev-tool/src/main.rs, utils/dev-tool/src/workspace.rs
Fixes: #1262
I haven't tested this yet, but it should work in theory.
=> CI should fail a PR if Cargo.lock changes 

docs/guides/install/README.md, docs/guides/install/android.md, docs/guides/install/iOS-iPadOS.md, docs/guides/install/macos.md, public_site/index.html
=> public_site: update store links on readme and website  

core/src/external_interface/c_interface.rs
* `get_and_get_children_recursively`
* `get_path_by_id`
* `validate`
=> add a few missing core endpoints to the c_interface

clients/android/app/src/main/java/app/lockbook/ui/ShareFileFragment.kt, clients/android/app/src/main/res/layout/chip_share.xml, clients/android/lint.xml, libs/core/Makefile
Changes include...
- Fixed some crashes associated with viewing sharees (introduced from when the original PR was moved between git histories)
- Got rid of UI signifying a sharee can be removed (as of right now core does not allow this action)
- Added `krishma` to the list of users who can share
=> android: sharing fixes

public_site/eula.html, public_site/privacy-policy.html, public_site/styles.css
context: public_site
<details>
</details>
=> public_site: add eula and privacy policy

docs/eula.md, public_site/eula.html
=> public_site: fix broken links in eula

clients/admin/src/indexes.rs, libs/core/libs/shared/src/api.rs, libs/core/tests/admin_tests.rs, server/server/src/file_service.rs
code based on server schema v2 migration deleted in this commit: https://github.com/lockbook/lockbook/commit/ea5ecb9c7e36af5b3571d1c2ce0e49329ca26852#
=> admin/server: add support for more indexes to rebuild; fix existing one

libs/core/src/service/sync_service.rs, libs/core/tests/admin_tests.rs, server/server/src/account_service.rs, server/server/src/file_service.rs, server/server/src/metrics.rs
fixes https://github.com/lockbook/lockbook/issues/1521
=> core/server: fix index integrity violations during admin ops

libs/editor/egui_editor/src/cursor.rs, libs/editor/egui_editor/src/events.rs, libs/editor/egui_editor/src/test_input.rs
=> editor: cmd & alt backspace

clients/apple/Shared/Views/BookView.swift
=> apple: empty new folder name

utils/releaser/src/linux/cli.rs
=> aur: fix build fail

clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift
=> apple: fix read and write access in sharing

clients/apple/Editor/macOS/EditorView.swift, libs/editor/SwiftEditor/Sources/Editor/CustomMTK.swift, libs/editor/SwiftEditor/Sources/Editor/MetalEditor.swift
a workaround till iOS is in and more of this can be replaced
=> macOS: fix editor crash

clients/android/app/build.gradle, utils/releaser/src/utils.rs
=> infra: fix android build

clients/apple/Shared/Views/NewFileSheet.swift, clients/apple/macOS/TreeView/DataSource.swift
+ cannot share root
+ cannot create drawings on macOS (for now)
=> macOS: apple reviewer feedback

libs/editor/egui_editor/src/events.rs
fixes #1559 
also fixes an issue where hitting return in an empty list item would insert an unintended newline
https://user-images.githubusercontent.com/6198756/218320414-be787169-c93e-4eff-a999-fa337c95a0af.mov
=> editor: insert newlines before non-list annotations when cursor at layout start

libs/editor/egui_editor/src/draw.rs
=> editor: bold numbered list numbers

libs/core/libs/shared/src/validate.rs, libs/core/tests/sharing_tests.rs
=> core: fix path conflict resolution bug

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Stateful Logic/CurrentDocument.swift, clients/apple/Shared/Stateful Logic/DI.swift, clients/apple/Shared/Views/ListFileCell.swift, clients/apple/Shared/Views/NewFileSheet.swift, clients/apple/iOS/FileListView.swift, clients/apple/iOS/FileTreeView.swift, clients/apple/iOS/OutlineView/OutlineBranch.swift, clients/apple/macOS/FileListView.swift, clients/apple/macOS/TreeView/DataSource.swift, clients/apple/macOS/TreeView/FileTreeView.swift
Users can now create a new file using `Cmd+n`.
=> apple: new file shortcut

libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/test_input.rs
=> editor: fix crash

Cargo.lock, libs/core/Cargo.toml, libs/core/libs/shared/Cargo.toml, libs/core/libs/shared/src/server_ops.rs, libs/core/libs/shared/src/server_tree.rs, libs/core/src/service/api_service.rs, server/server/Cargo.toml, server/server/src/account_service.rs, server/server/src/billing/app_store_service.rs, server/server/src/billing/billing_service.rs, server/server/src/billing/google_play_service.rs, server/server/src/billing/stripe_service.rs, server/server/src/document_service.rs, server/server/src/error_handler.rs, server/server/src/file_service.rs, server/server/src/lib.rs, server/server/src/main.rs, server/server/src/metrics.rs, server/server/src/router_service.rs, server/server/src/schema.rs
More code can be deleted once we actually delete hmdb (next release) for now we need it for the migration.
salient changes to look over (@tvanderstad):
+ [x] migration
+ [x] tree impls
+ [x] admin_validate_server
other tests: 
+ [x] @SmailBarkouch can you just run all our billing tests when you get a moment (sanity check)
=> server: hmdb -> db-rs

libs/editor/SwiftEditor/Sources/Editor/CustomMTK.swift, libs/editor/egui_editor/src/apple/apple_ffi.rs, libs/editor/egui_editor/src/apple/keyboard.rs, libs/editor/egui_editor/src/lib.rs
fixes #1574 
fixes #1569
fixes #1573
=> editor: integration bufixes

.gitignore, libs/core_external_interface/Makefile
@SmailBarkouch did I do android right?
=> core: fix a makefile

libs/core/libs/shared/src/api.rs, libs/core/tests/sharing_tests.rs, server/server/src/file_service.rs
also adds validation to admin cli
=> server: remove implicitly deleted files from server share index

clients/apple/macOS/Info.plist, utils/releaser/src/android/core.rs, utils/releaser/src/apple/core.rs
one of the problems from last night
=> infra: fix wrong build location in scripts

libs/editor/egui_editor/src/cursor.rs, libs/editor/egui_editor/src/test_input.rs
=> editor: word advance segmentation fix

libs/editor/egui_editor/src/events.rs
=> editor: don't consider clicks outside galleys as 0 char offset

clients/egui/src/account/tabs/markdown.rs, libs/editor/egui_editor/src/editor.rs
=> editor: get inner rect of scroll area for interact rect

utils/releaser/src/android/mod.rs
=> releaser: release android to production automatically

libs/editor/egui_editor/src/buffer.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/events.rs, libs/editor/egui_editor/src/test_input.rs
fixes https://github.com/lockbook/lockbook/issues/1577
=> editor: clickable links

clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Views/BookView.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/FfiError.swift, clients/apple/lockbook.xcodeproj/xcshareddata/xcschemes/Lockbook (macOS).xcscheme, clients/apple/macOS/TreeView/DataSource.swift, clients/apple/macOS/TreeView/FileTreeView.swift, libs/core_external_interface/src/c_interface.rs
Users can now drag files in and out of Lockbook macOS.
**Demonstration**
<details>
https://user-images.githubusercontent.com/20663038/228348335-1c03e8d8-6973-403d-a077-df16be9da5a5.mov
</details>
fixes #842
=> apple: macOS import and export file tree support

libs/editor/egui_editor/src/cursor.rs, libs/editor/egui_editor/src/events.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/test_input.rs
=> editor: fix advance word

libs/editor/egui_editor/src/events.rs
fixes https://github.com/lockbook/lockbook/issues/1611
@steverusso UAT this before merging!
=> editor: delete key support

clients/egui/src/account/syncing.rs
Checks last item for https://github.com/lockbook/lockbook/issues/1676
@Parth UAT this if you can.
=> egui: save open tabs before performing sync

Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/account/mod.rs, clients/egui/src/account/modals/new_file.rs, clients/egui/src/account/modals/search.rs, clients/egui/src/account/tree/mod.rs, clients/egui/src/account/tree/node.rs, clients/egui/src/account/workspace.rs, clients/egui/src/main.rs, clients/egui/src/onboard.rs, clients/egui/src/theme/mod.rs, clients/egui/src/theme/palette.rs, libs/editor/egui_editor/Cargo.toml, libs/editor/egui_editor/src/draw.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/main.rs, utils/winstaller/Cargo.toml
This doesn't unbreak the settings tabs.
Increases total project deps from 814 to 863, total egui client deps from 485 to 554.
Closes #1675.
=> egui,editor,winstaller: upgrade egui related deps

clients/cli/src/share.rs
=> cli: fix share table output

clients/apple/Shared/Stateful Logic/SearchService.swift, clients/apple/Shared/Views/SearchWrapperView.swift, clients/apple/iOS/FileListView.swift, clients/apple/iOS/FileTreeView.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/macOS/FileListView.swift, clients/apple/macOS/TreeView/DataSource.swift, clients/apple/macOS/TreeView/FileTreeView.swift
Demonstration
<details>
https://user-images.githubusercontent.com/20663038/232334105-d612c90a-279a-4f51-9275-69c4c22dd5c6.mov
</details>
fixes #1725
=> apple: macOS document and path search

clients/cli/src/main.rs
=> cli: improve delete warning messages

server/server/src/metrics.rs
=> server: fix metrics panic

server/server/src/metrics.rs
fix overcounting of active users
=> server: metrics problem 2

libs/editor/egui_editor/src/input/canonical.rs
=> editor: cmd+click to open links

Cargo.lock, libs/editor/egui_editor/Cargo.toml, libs/editor/egui_editor/src/editor.rs
=> editor: generate random id for scroll area

clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/account/modals/settings/usage_tab.rs
=> egui: load usage info out of frame so settings dialog doesn't freeze app

clients/apple/Shared/Views/BottomBar.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/File.swift, clients/apple/iOS/FileListView.swift, clients/apple/iOS/FileTreeView.swift, clients/apple/macOS/FileListView.swift
In addition, I made a small code refactor to the bottom bar.
fixes #1737
=> android: fix move between shared folders

clients/apple/Shared/Views/SuggestedDocs.swift
=> apple: fix macOS suggested document crashes

libs/editor/egui_editor/src/apple/ios_ffi.rs
=> editor: fix auto insert list items on iOS

libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
=> apple: editor handles command+a

libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
=> apple: handle iPad trackpad and scrollwheel gestures

clients/apple/Shared/Views/BeforeYouStart.swift
=> apple: fix backup button in onboarding sheet

clients/egui/src/main.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/galleys.rs
=> editor: clip line width 

libs/editor/egui_editor/src/input/canonical.rs
=> editor: fix jump by words

clients/egui/src/account/mod.rs, clients/egui/src/account/tree/mod.rs, clients/egui/src/account/tree/node.rs, libs/editor/egui_editor/src/editor.rs
=> egui: fix light mode

clients/egui/src/widgets/button_group.rs
=> egui: higher button_group contrast

libs/editor/SwiftEditor/Sources/Editor/macMTK.swift, libs/editor/egui_editor/src/apple/macos_ffi.rs
=> apple: remove hard-coded mouse location for scrolling

libs/editor/egui_editor/src/editor.rs
fixes: #1815
looks very strange on iOS otherwise
=> editor: pure white / black for integrations

libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/input/advance.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/click_checker.rs, libs/editor/egui_editor/src/input/events.rs
fixes https://github.com/lockbook/lockbook/issues/1843
before:
https://github.com/lockbook/lockbook/assets/6198756/22b07ee9-bf47-4e76-a2cc-2bc20c1f15fb
after:
https://github.com/lockbook/lockbook/assets/6198756/c0009a51-87ed-4927-bded-17680cb0ce1e
=> editor: fix ios menu taps

libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/1746
before:
https://github.com/lockbook/lockbook/assets/6198756/f2b62c00-4a75-408d-85b6-f73503e6173b
after:
https://github.com/lockbook/lockbook/assets/6198756/b9ddcc1e-5f29-43b5-b456-de879f51df71
=> editor: insert new list items using enter anywhere in item text

clients/apple/Shared/Stateful Logic/BillingService.swift, clients/apple/Shared/Stateful Logic/SettingsService.swift, clients/apple/Shared/Stateful Logic/SyncService.swift, clients/apple/Shared/Views/BottomBar.swift
=> apple: fix premium usage bar

clients/android/app/src/main/java/app/lockbook/ui/UsageBarPreference.kt, clients/android/app/src/main/res/layout/preference_usage_bar.xml, clients/android/app/src/main/res/values/strings.xml
<details>
</details>
fixes #1808
=> android: premium usage caption

libs/editor/egui_editor/src/apple/common_ffi.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/element.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/events.rs, libs/editor/egui_editor/src/input/mutation.rs
=> editor: toggle selection style

libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/1904
fixes https://github.com/lockbook/lockbook/issues/1906
fixes https://github.com/lockbook/lockbook/issues/1905
prereq for https://github.com/lockbook/lockbook/issues/1838
https://github.com/lockbook/lockbook/assets/6198756/2f57cbf6-4a91-45d0-9ede-546246ec18db
=> editor: toggle style refinements

libs/editor/egui_editor/src/editor.rs
This reduces code duplication and supports reporting when the cursor is in e.g. a bold italic region for the toolbar
=> editor: report multiple inline cursor styles

libs/editor/egui_editor/src/editor.rs
fixes https://github.com/lockbook/lockbook/issues/1895
=> editor: set text without re-initializing

clients/egui/src/account/mod.rs, clients/egui/src/account/modals/file_picker.rs, clients/egui/src/account/modals/mod.rs
=> egui: drag file from outside

clients/apple/Shared/Views/SearchWrapperView.swift, clients/apple/iOS/FileListView.swift, clients/apple/iOS/FileTreeView.swift
=> apple: hide bottom bar (and breadcrumb) in search

libs/core/tests/exhaustive_sync/coordinator.rs, libs/core/tests/exhaustive_sync/stats.rs, libs/core/tests/exhaustive_sync/worker.rs
=> fuzzer: added some timing code

libs/core/libs/shared/src/lazy.rs, libs/core/tests/sharing_tests.rs
=> core: fix filenonexistent bug on deleted shares

clients/egui/src/account/workspace.rs
fixes #1926
<details>
</details>
=> egui: empty state ui for workspaces 

libs/editor/egui_editor/src/appearance.rs, libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/draw.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/layouts.rs, libs/editor/egui_editor/src/style.rs, libs/editor/egui_editor/src/test_input.rs
fixes https://github.com/lockbook/lockbook/issues/1960
=> editor: support rules

libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/bounds.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/style.rs, libs/editor/egui_editor/src/test_input.rs
fixes https://github.com/lockbook/lockbook/issues/1981 (not #1933)
also assumes https for urls without a scheme
https://github.com/lockbook/lockbook/assets/6198756/1a2f989b-a77b-4ff5-85fd-d47fee97573a
=> editor: support toggle link style

libs/editor/egui_editor/src/bounds.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/test_input.rs
fixes https://github.com/lockbook/lockbook/issues/1931
=> editor: snap cursor to valid locations

clients/egui/src/account/mod.rs
=> egui: close the tab of a rectenlty deleted file

clients/egui/src/account/mod.rs, clients/egui/src/account/modals/settings/mod.rs
fixes #1876 
this PR has the side effect of adding animations to the sidebar as show in the demo
https://github.com/lockbook/lockbook/assets/66345861/d3f15929-e7a5-4669-b22a-1be9d6e05f67
=> egui: fix modals non responsivness bug 

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Stateful Logic/OnboardingState.swift, clients/apple/Shared/Stateful Logic/SearchService.swift, clients/apple/Shared/Stateful Logic/SyncService.swift, clients/apple/Shared/Views/BottomBar.swift, clients/apple/Shared/Views/OnboardingView.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift, clients/apple/SwiftLockbookCore/Tests/SwiftLockbookCoreTests/SwiftLockbookCoreTests.swift, libs/core_external_interface/src/c_interface.rs
fixes part of #1896
fixes #1102
=> apple: sync status everywhere and sync bug fixes

libs/editor/egui_editor/src/galleys.rs
fixed an issue with toggling a todo list item where the text started with a captured character sequence
=> editor: fix toggle todo list item

libs/editor/egui_editor/src/appearance.rs, libs/editor/egui_editor/src/apple/ios_ffi.rs, libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/bounds.rs, libs/editor/egui_editor/src/draw.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/input/advance.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/click_checker.rs, libs/editor/egui_editor/src/input/cursor.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/1799
fixes https://github.com/lockbook/lockbook/issues/2003
fixes https://github.com/lockbook/lockbook/issues/2004
fixes https://github.com/lockbook/lockbook/issues/2005
fixes https://github.com/lockbook/lockbook/issues/2006
fixes https://github.com/lockbook/lockbook/issues/2008
fixes https://github.com/lockbook/lockbook/issues/2010
=> editor: assorted fixes

libs/editor/egui_editor/src/appearance.rs, libs/editor/egui_editor/src/ast.rs, libs/editor/egui_editor/src/bounds.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/offset_types.rs, libs/editor/egui_editor/src/test_input.rs
based on https://github.com/lockbook/lockbook/pull/2012
fixes https://github.com/lockbook/lockbook/issues/2013
https://github.com/lockbook/lockbook/assets/6198756/bf18d91e-02b1-4e0d-b96d-ec7352d36ceb
=> editor: cursor-based capture

Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/account.rs, clients/cli/src/debug.rs, clients/cli/src/edit.rs, clients/cli/src/imex.rs, clients/cli/src/list.rs, clients/cli/src/main.rs, clients/cli/src/share.rs
+ completion errors are silent (in cli-rs)
+ tab completion doesn't work if there's a mismatched subcommand (in cli-rs)
+ commands either require an account or an account and root (also sync) and produce nice errors
=> cli: fix some bugs

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Stateful Logic/DocumentService.swift, clients/apple/Shared/Views/DocumentTabView.swift, clients/apple/Shared/Views/DocumentView.swift, libs/editor/SwiftEditor/Sources/Editor/EditorState.swift, libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift, libs/editor/egui_editor/src/apple/ios_ffi.rs
fixes: https://github.com/lockbook/lockbook/issues/1774
=> apple: iOS and iPadOS undo redo support

clients/apple/Shared/Views/DocumentTabView.swift
=> apple: close tab with middle click

clients/egui/src/widgets/toolbar.rs, libs/editor/egui_editor/src/apple/common_ffi.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/2034
fixes https://github.com/lockbook/lockbook/issues/2035
https://github.com/lockbook/lockbook/assets/6198756/3fdde85d-9cdb-4982-af21-4ecadb7ee66a
=> editor: toggle block style refinements

libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/click_checker.rs, libs/editor/egui_editor/src/input/cursor.rs
fixes https://github.com/lockbook/lockbook/issues/2016
https://github.com/lockbook/lockbook/assets/6198756/634aeaa3-737b-4757-b304-5eadd122d565
=> editor: record and use pointer drag start offset

libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/input/cursor.rs
fixes https://github.com/lockbook/lockbook/issues/2026
https://github.com/lockbook/lockbook/assets/6198756/bd880b76-e308-4b61-ba60-d62390979e90
=> editor: detect/output text pointer

libs/editor/egui_editor/src/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/2024
https://github.com/lockbook/lockbook/assets/6198756/869f3456-0097-486b-9ac0-7f8368b0c34c
=> editor: fix yeeting of cursor when clicking between galleys

libs/editor/egui_editor/src/appearance.rs, libs/editor/egui_editor/src/bounds.rs, libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/2027
https://github.com/lockbook/lockbook/assets/6198756/4cb5fad5-e399-4c2a-99c2-7a38f83f7acb
=> editor: uncaptured syntax as text for word bounds

libs/editor/egui_editor/src/editor.rs
fixes https://github.com/lockbook/lockbook/issues/2020
=> editor: don't flash test text in prod editor

libs/editor/egui_editor/src/appearance.rs, libs/editor/egui_editor/src/buffer.rs, libs/editor/egui_editor/src/editor.rs, libs/editor/egui_editor/src/input/canonical.rs, libs/editor/egui_editor/src/input/events.rs, libs/editor/egui_editor/src/input/mutation.rs, libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/2021
https://github.com/lockbook/lockbook/assets/6198756/c2c4f7b5-4b6b-4706-a8e9-e6805370f9b0
=> editor: adjustable font size

libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
fixes the issue with macOS not compiling
=> apple: conditionally compile iOSUndoManager

clients/egui/src/account/modals/search.rs
=> egui: imrpove style of path search 

clients/egui/src/account/modals/settings/general_tab.rs, clients/egui/src/account/modals/settings/mod.rs
fixes egui component of #1739
https://github.com/lockbook/lockbook/assets/66345861/b8cf7480-1b60-4624-9fad-650e11b299ee
=> egui: show version number

libs/editor/egui_editor/src/ast.rs
fixes https://github.com/lockbook/lockbook/issues/2062
=> editor: ast capture fix

libs/editor/egui_editor/src/galleys.rs, libs/editor/egui_editor/src/images.rs
fixes https://github.com/lockbook/lockbook/issues/2030
fixes https://github.com/lockbook/lockbook/issues/2065
=> editor: improved handling for failed & duplicate images

clients/apple/Shared/Views/SearchWrapperView.swift
=> apple: fix search blank screen

clients/apple/Shared/Views/DocumentView.swift, libs/editor/SwiftEditor/Sources/Editor/macMTK.swift
=> apple: fix macOS undo redo buttons

libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
=> apple: fix ipad deindent

libs/editor/SwiftEditor/Sources/Editor/macMTK.swift
=> apple: use IBeam cursor when hovering over editor

libs/editor/SwiftEditor/Sources/Editor/EditorState.swift, libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
=> apple: the keyboard is closed by default when opening a document

clients/apple/Shared/Stateful Logic/DocumentService.swift, libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift, libs/editor/SwiftEditor/Sources/Editor/macMTK.swift, libs/editor/egui_editor/src/apple/ios_ffi.rs
=> apple: drop images/documents/text into editor

clients/apple/Shared/Stateful Logic/DocumentService.swift, clients/apple/Shared/Views/DocumentView.swift, clients/apple/iOS/FileListView.swift
https://github.com/lockbook/lockbook/assets/821972/2cceb232-b7a9-493f-8c3c-4c5a19e38d2a
=> apple: fix opening links on iOS

libs/editor/egui_editor/src/apple/common_ffi.rs, libs/editor/egui_editor/src/apple/macos_ffi.rs
An incremental fix to the ipad scrolling issue.
=> apple: ipad fix scroll

docs/guides/build/linux.md, docs/guides/releasing.md
=> docs: update releaser docs

libs/core/libs/shared/src/filename.rs
=> core & server: larger filenames

public_site/index.html
Fixes https://github.com/lockbook/lockbook/issues/2167
Happy Hacktoberfest!
=> Updated & fixed core library link

clients/egui/src/account/tabs/pdf_viewer.rs
as a side effect, you can now zoom out through right click
=> egui: pdf toolbar

libs/content/editor/egui_editor/src/appearance.rs, libs/content/editor/egui_editor/src/ast.rs, libs/content/editor/egui_editor/src/bounds.rs, libs/content/editor/egui_editor/src/editor.rs, libs/content/editor/egui_editor/src/galleys.rs
fixes https://github.com/lockbook/lockbook/issues/2212
https://github.com/lockbook/lockbook/assets/6198756/c0b2854b-c28d-464c-bbce-640c3bf814d2
=> editor: conditional character capture refinements

clients/cli/src/account.rs
=> cli: augment status command

libs/content/editor/egui_editor/src/input/canonical.rs
fixes https://github.com/lockbook/lockbook/issues/2170
=> editor: windows ctrl+home/end

clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Stateful Logic/SettingsService.swift, clients/apple/Shared/Views/AppView.swift, clients/apple/Shared/Views/BookView.swift, clients/apple/Shared/Views/BottomBar.swift, clients/apple/Shared/Views/ListFileCell.swift, clients/apple/Shared/Views/RenameFolderSheet.swift, clients/apple/iOS/OutlineView/OutlineContextMenu.swift, clients/apple/iOS/OutlineView/SheetState.swift, clients/apple/iOS/SettingsView.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/macOS/Settings/UsageSettingsView.swift, clients/apple/macOS/TreeView/DataSource.swift, clients/apple/macOS/TreeView/MenuItems.swift
fixes #2107 
fixes #2188 
fixes #2219
fixes #2095
fixes #2223
=> apple: assorted fixes

clients/egui/src/account/tabs/pdf_viewer.rs
=> egui: pdf sidebar and zoom shortcut enhancments

clients/egui/src/account/mod.rs, clients/egui/src/account/tabs/markdown.rs, libs/content/editor/egui_editor/src/android/android_ffi.rs, libs/lb/lb-rs/libs/shared/src/filename.rs
=> egui: new file experience bug fixes

clients/apple/Shared/LockbookApp.swift, libs/content/editor/SwiftEditor/Sources/Editor/macMTK.swift, libs/content/editor/egui_editor/src/apple/macos_ffi.rs
fixes https://github.com/lockbook/lockbook/issues/2194
https://github.com/lockbook/lockbook/assets/6198756/54bd3e97-5933-4526-a851-3b79125b47d8
=> macos: modifier-only events to editor

Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/account/tabs/svg_editor/eraser.rs, clients/egui/src/account/tabs/svg_editor/main.rs, clients/egui/src/account/tabs/svg_editor/mod.rs, clients/egui/src/account/tabs/svg_editor/pen.rs, clients/egui/src/account/tabs/svg_editor/toolbar.rs, clients/egui/src/account/tabs/svg_editor/util.rs
https://github.com/lockbook/lockbook/assets/66345861/d57180cb-9e00-4bb5-b052-b6c9add65275
=> egui: eraser for svg editor  

clients/egui/src/account/tabs/svg_editor/eraser.rs, clients/egui/src/account/tabs/svg_editor/history.rs, clients/egui/src/account/tabs/svg_editor/main.rs, clients/egui/src/account/tabs/svg_editor/mod.rs, clients/egui/src/account/tabs/svg_editor/pen.rs, clients/egui/src/account/tabs/svg_editor/toolbar.rs
fixes #2261 
https://github.com/lockbook/lockbook/assets/66345861/e00acdc8-52bd-47ce-ac29-434f43089402
=> egui: redo/undo for svg editor

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Views/SearchWrapperView.swift, clients/apple/iOS/FileTreeView.swift
=> apple: search flow refinements

libs/lb/lb-rs/src/service/activity_service.rs, libs/lb/lb-rs/src/service/search_service.rs
=> apple: incorporate document activity in search results

.vscode/settings.json, Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/account/tabs/svg_editor/eraser.rs, clients/egui/src/account/tabs/svg_editor/history.rs, clients/egui/src/account/tabs/svg_editor/main.rs, clients/egui/src/account/tabs/svg_editor/mod.rs, clients/egui/src/account/tabs/svg_editor/pen.rs, clients/egui/src/account/tabs/svg_editor/selection.rs, clients/egui/src/account/tabs/svg_editor/toolbar.rs, clients/egui/src/account/tabs/svg_editor/util.rs, clients/egui/src/main.rs, clients/egui/src/theme/icons.rs, clients/egui/src/theme/mod.rs
fixes #2265 #1915 
https://github.com/lockbook/lockbook/assets/66345861/ec1b05b5-5043-422b-9352-6a67e676950f
<details>
</details>
<details>
</details>
=> egui: seleciton tool for the svg editor  

.vscode/settings.json, clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt, clients/android/app/src/main/java/app/lockbook/model/SearchDocumentsViewModel.kt, clients/android/lb-rs/src/main/java/app/lockbook/core/core.kt, clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Stateful Logic/DocumentService.swift, clients/apple/Shared/Stateful Logic/SearchService.swift, clients/apple/Shared/Views/BookView.swift, clients/apple/Shared/Views/PathSearchActionBar.swift, clients/apple/Shared/Views/SearchWrapperView.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift, clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/Search.swift, clients/egui/src/account/full_doc_search.rs, clients/egui/src/account/mod.rs, libs/lb/lb-rs/libs/shared/src/document_repo.rs, libs/lb/lb-rs/src/lib.rs, libs/lb/lb-rs/src/model/errors.rs, libs/lb/lb-rs/src/service/api_service.rs, libs/lb/lb-rs/src/service/search_service.rs, libs/lb/lb-rs/tests/search_service_tests.rs, libs/lb/lb_external_interface/src/c_interface.rs, libs/lb/lb_external_interface/src/java_interface.rs, libs/lb/lb_external_interface/src/lib.rs
fixes #2282
fixes #2216
Significantly improved the speed of path and content search. In addition, there were small UI changes to the apple platforms for path search.
=> core, apple: improved path and content search

Cargo.lock, clients/egui/src/account/tabs/svg_editor/eraser.rs, clients/egui/src/account/tabs/svg_editor/history.rs, clients/egui/src/account/tabs/svg_editor/main.rs, clients/egui/src/account/tabs/svg_editor/mod.rs, clients/egui/src/account/tabs/svg_editor/pen.rs, clients/egui/src/account/tabs/svg_editor/selection.rs, clients/egui/src/account/tabs/svg_editor/toolbar.rs, clients/egui/src/account/tabs/svg_editor/util.rs, clients/egui/src/account/tabs/svg_editor/zoom.rs
fixes #2264 
https://github.com/lockbook/lockbook/assets/66345861/f632a9d9-dbfa-4ab8-8b30-84936eb43ec5
=> workspace: svg editor zoom

clients/egui/src/account/tabs/svg_editor/main.rs, clients/egui/src/account/tabs/svg_editor/toolbar.rs
=> workspace: svg editor tools active indicator & tools keyboard shortcuts  

Cargo.lock, libs/content/editor/egui_editor/Cargo.toml, libs/content/editor/egui_editor/src/images.rs
fixes https://github.com/lockbook/lockbook/issues/2258
Note: you currently have to close and re-open your markdown tab for your drawing to refresh
https://github.com/lockbook/lockbook/assets/6198756/6f198983-07bf-45eb-b93c-1e884d8b2328
=> editor: inline drawings

libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/util.rs
=> fix canvas crash caused by an empty path 

Cargo.lock, clients/egui/Cargo.toml, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/svg_editor/history.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/workspace.rs
=> canvas img support

Cargo.lock, clients/egui/Cargo.toml, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/svg_editor/history.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/workspace.rs
Reverts lockbook/lockbook#2340
=> Revert "canvas img support"

Cargo.lock, clients/egui/Cargo.toml, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/svg_editor/history.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/workspace.rs
=> canvas: image support

clients/egui/src/account/mod.rs, libs/content/workspace/src/workspace.rs
fixes [#2399](https://github.com/lockbook/lockbook/issues/2399)
=> egui: fix broken keyboard shortcuts 

clients/apple/macOS/TreeView/DataSource.swift, clients/apple/macOS/TreeView/MenuItems.swift
=> macOS: create new drawing

libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/macMTK.swift
=> macOS: hide cursor in drawings

clients/egui/src/account/mod.rs, clients/egui/src/model.rs, clients/egui/src/onboard.rs, clients/egui/src/splash.rs, libs/content/workspace/src/background.rs, libs/content/workspace/src/output.rs, libs/content/workspace/src/syncing.rs, libs/content/workspace/src/workspace.rs
=> egui: restore badge for new pending shares

clients/egui/src/account/mod.rs, libs/content/workspace-ffi/src/lib.rs, libs/content/workspace/src/output.rs, libs/content/workspace/src/syncing.rs
fixes #2404 
but also fixes other state sharing related issues
=> egui: refresh file tree when needed

clients/egui/src/account/mod.rs
=> egui: fix zen mode

Cargo.lock, clients/cli/Cargo.toml, clients/cli/src/lb_fs.rs, clients/cli/src/main.rs, libs/lb-fs/src/core.rs, libs/lb-fs/src/lib.rs, libs/lb-fs/src/main.rs, libs/lb-fs/src/mount.rs, libs/lb/lb-rs/src/service/log_service.rs
QA'd linux
QA'd macOS
fixes #2406 
fixes #2369
=> cli: lb-fs

clients/apple/Shared/Views/BookView.swift, clients/apple/iOS/FileListView.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceState.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceView.swift, libs/content/workspace-ffi/src/apple/ios_ffi.rs
Demonstration:
<details>
https://github.com/lockbook/lockbook/assets/20663038/62f9cc0c-254f-409c-b13b-ffcd43b854c6
</details>
fixes #2385 
fixes #2384
=> iOS: drag to exit workspace

libs/content/workspace/src/tab/svg_editor/selection.rs
=> canvas: fix crash on selection

libs/content/workspace/src/tab/pdf_viewer.rs, libs/content/workspace/src/workspace.rs
fixes most issues for mobile like:
- hiding the sidebar
- low res image output
what it's missing:
- panning is buggy (true for both mobile and desktop) 
- no multi touch zoom (true for mobile and desktop)
fixes [#2386](https://github.com/lockbook/lockbook/issues/2386)
=> workspace: pdf viewer for mobile 

clients/apple/Shared/Stateful Logic/FileService.swift
=> apple: fix new file freeze

docs/README.md, docs/guides/cli-completions.md
* notes for debugging CLI completions
* notes specific to bash, zsh, and fish
* link to homebrew doc for completions
* link to build system releaser
=> docs: CLI completions guide

clients/linux/src/window.rs
fixes https://github.com/lockbook/lockbook/issues/2483
=> linux: support wayland by disabling wayland

clients/linux/src/input/key.rs, clients/windows/src/input/key.rs
fixes https://github.com/lockbook/lockbook/issues/2365
=> windows/linux: emit keys in addition to text

clients/egui/src/account/mod.rs, clients/egui/src/account/modals/file_picker.rs, clients/egui/src/account/modals/mod.rs, clients/windows/src/input/file_drop.rs
fixes https://github.com/lockbook/lockbook/issues/2495
fixes https://github.com/lockbook/lockbook/issues/2358
=> windows: file drop fixes

libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/macMTK.swift
=> apple: correctly set `openDoc` state

clients/apple/Shared/Stateful Logic/SearchService.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceView.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift, libs/content/workspace/src/theme/icons.rs, libs/content/workspace/src/widgets/toolbar.rs
Screenshots:
<details>
</details>
=> apple: more toolbar buttons

clients/apple/iOS/SettingsView.swift, public_site/styles.css, public_site/tos.html
=> apple: EULA to TOS

libs/content/workspace/src/tab/svg_editor/clip.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/pen.rs
=> canvas: paste images 

clients/apple/Shared/Views/LogoutConfirmation.swift, clients/apple/iOS/SettingsView.swift, clients/apple/lockbook.xcodeproj/project.pbxproj, clients/apple/macOS/WindowManager.swift
=> ios: logout

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Stateful Logic/SearchService.swift, clients/apple/Shared/Views/ListFileCell.swift, clients/apple/Shared/Views/RenameFileSheet.swift, clients/apple/Shared/Views/SearchWrapperView.swift, clients/apple/Shared/Views/SuggestedDocs.swift, clients/apple/iOS/OutlineView/OutlineBranch.swift, clients/apple/macOS/TreeView/FileTreeView.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceState.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceView.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/macMTK.swift, libs/content/workspace-ffi/src/apple/common_ffi.rs, libs/content/workspace-ffi/src/apple/ios_ffi.rs
=> apple: send rename and delete operations into workspace

libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift
=> apple: fixed workspace consuming shortcuts

clients/apple/iOS/FileTreeView.swift
=> apple: fix workspace shrinking when sidebar is hidden

clients/egui/src/account/mod.rs
=> egui: fix modal crop

clients/egui/src/account/mod.rs, libs/content/editor/egui_editor/src/main.rs, libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/mod.rs, libs/content/workspace/src/workspace.rs
=> editor: preserve scroll state across tabs

libs/content/workspace/src/tab/svg_editor/selection.rs
=> canvas: fix selection overflow

server/server/src/billing/app_store_client.rs
https://github.com/lockbook/lockbook/pull/2595#discussion_r1545925426
=> server: get_trans fix

docs/CONTRIBUTING.md
=> docs: more details to contributing

libs/content/workspace/src/tab/svg_editor/selection/mod.rs, libs/content/workspace/src/tab/svg_editor/selection/rect.rs, libs/content/workspace/src/widgets/button.rs
fixes: #2492
https://github.com/lockbook/lockbook/assets/66345861/63470709-9ef3-4e13-84b8-48457beeaff2
=> canvas: add delete button on selection

libs/content/workspace/src/tab/svg_editor/pen.rs
https://github.com/lockbook/lockbook/assets/66345861/8a94d020-f80d-48a2-a481-82316e915016
=> canvas: tweak catmull tension to remove cusp

libs/content/workspace/src/tab/svg_editor/history.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/selection/mod.rs, libs/content/workspace/src/tab/svg_editor/util.rs
requested by @CoreyCole 
https://github.com/lockbook/lockbook/assets/66345861/5951835f-a74d-4b3e-9572-77d93cb0e853
=> canvas: add shape snapping

clients/apple/macOS/TreeView/FileTreeView.swift, libs/content/workspace/src/workspace.rs
=> apple, workspace: fix file tree selection and selected file inconsistency

clients/egui/src/account/modals/search.rs, clients/egui/src/account/syncing.rs, clients/egui/src/account/tree/node.rs, clients/egui/src/model.rs, libs/content/workspace/src/theme/icons.rs, libs/content/workspace/src/widgets/button.rs, libs/content/workspace/src/widgets/button_group.rs, libs/content/workspace/src/workspace.rs
=> egui: bring back colors to file tree

libs/content/workspace/src/tab/markdown_editor/galleys.rs
fixes https://github.com/lockbook/lockbook/issues/1983
=> editor: render tab-only paragraphs

clients/linux/src/input/key.rs, clients/linux/src/input/pointer.rs, clients/windows/src/input/mouse.rs, clients/windows/src/window.rs
=> linux/windows: add zoom event

Cargo.lock, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/content/workspace/src/tab/markdown_editor/mod.rs, libs/content/workspace/src/tab/mod.rs, libs/content/workspace/src/tab/svg_editor/clip.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2570
tested on windows with https://github.com/lockbook/lockbook/pull/2636
=> workspace: import pasted images to sibling folder

libs/content/workspace/src/workspace.rs
helpful for me debugging SVGs. sometimes i'd want to look at the text of svg instead of the render. previously, i'd change the file type to md and then close and open the tab again. this pr streamlines the process and automatically reloads the document with appropriate rendering pipeline on a file type change.
=> workspace: reload file on file type change

libs/content/workspace/src/tab/svg_editor/eraser.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/tab/svg_editor/util.rs, libs/content/workspace/src/tab/svg_editor/zoom.rs, libs/content/workspace/src/theme/visuals.rs, libs/content/workspace/src/workspace.rs
=> canvas: zoom controls and eraser thickness 

libs/content/workspace/src/workspace.rs
=> workspace: disable tooltips on touch devices

libs/content/workspace/src/tab/svg_editor/selection/mod.rs
=> canvas: fix selection intent mismatch

utils/winstaller/src/main.rs
tested by running the installer locally (from target/.../release/)
=> winstaller: fixes after egui update

libs/content/workspace/src/tab/markdown_editor/images.rs
https://github.com/lockbook/lockbook/assets/6198756/7fc19b7c-cb30-4775-8eb4-902ac7fac9cb
=> editor: fix inline canvas renders

libs/content/workspace/src/tab/markdown_editor/appearance.rs, libs/content/workspace/src/tab/markdown_editor/style.rs
fixes https://github.com/lockbook/lockbook/issues/2655
=> editor: scale monospace font

libs/content/workspace/src/workspace.rs
macos-only fix for https://github.com/lockbook/lockbook/issues/2610
=> workspace: fix cmd+shift+8

libs/content/workspace/src/tab/markdown_editor/input/mutation.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2585
=> editor: fix crash when deleting end of doc newline after numbered list

libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift
Demonstration:
https://github.com/lockbook/lockbook/assets/20663038/f7eb9044-48c6-4fc3-99ff-45fcecb9bdf8
Notes
+ Suggestions are not working properly, and it will be fixed in a later PR altogether (since it has more issues on its own).
fixes #1864
=> ios: floating cursor support

libs/content/workspace/src/tab/svg_editor/mod.rs
=> canvas: fix phantom strokes

libs/content/workspace-ffi/src/apple/keyboard.rs
fixes https://github.com/lockbook/lockbook/issues/2614
=> workspace: interpret some numpad keycodes

clients/apple/Shared/LockbookApp.swift, clients/apple/iOS/ConstrainedHomeView.swift, clients/apple/macOS/DesktopHomeView.swift
=> macOS: search bar in sidebar

libs/content/workspace/src/tab/svg_editor/pen.rs
fixes #2759 
https://github.com/user-attachments/assets/1054f1be-b8aa-43f3-952b-75dd66d454ce
=> canvas: fix dancing lines

clients/android/app/build.gradle
=> android: update target sdk to 34

clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt, clients/android/app/src/main/java/app/lockbook/model/SettingsViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/SettingsFragment.kt, clients/android/app/src/main/java/app/lockbook/util/Errors.kt, clients/android/app/src/main/res/drawable/baseline_admin_panel_settings_24.xml, clients/android/app/src/main/res/drawable/ic_baseline_paid_24.xml, clients/android/app/src/main/res/values/strings.xml, clients/android/app/src/main/res/xml/settings_preference.xml, clients/android/lb-rs/src/main/java/app/lockbook/core/core.kt, libs/lb/lb-rs/src/lib.rs, libs/lb/lb_external_interface/src/c_interface.rs, libs/lb/lb_external_interface/src/java_interface.rs, public_site/account-deletion.html, public_site/delete-account.html, public_site/styles.css
fixes #2804
fixes #2805
fixes #2800
New "Logout" and "Delete Account" options:
New "Delete Account" page:
=> website, android: delete account site and add logout and delete account options in settings

libs/content/workspace/src/tab/svg_editor/eraser.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/tab/svg_editor/util.rs
=> canvas make the eraser brush accurate

clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Util.swift, clients/apple/Shared/Views/CreateFolderSheet.swift, clients/apple/Shared/Views/PlatformView.swift, clients/apple/Shared/Views/RenameFileSheet.swift, clients/apple/Shared/Views/SelectFolderView.swift, clients/apple/iOS/OutlineView/SheetState.swift, clients/apple/macOS/TreeView/DataSource.swift
fixes #2433 
fixes #1108
iOS:
https://github.com/user-attachments/assets/22157355-4453-4017-be1b-979160a56fe3
iPadOS:
https://github.com/user-attachments/assets/61470997-1e5b-465d-a8f6-bfbc4cbd4f68
macOS:
https://github.com/user-attachments/assets/a3aa1144-480b-4169-8208-78eb057ae8d1
=> apple: rename and create folder sheet redesign

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift
tested with mouse & trackpad
fixes https://github.com/lockbook/lockbook/issues/2820
=> macos: fix mouse scroll

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2784
fixes https://github.com/lockbook/lockbook/issues/2778
https://github.com/user-attachments/assets/5e479060-6ddd-4ac7-94d1-d68e92282585
=> workspace: fix tab shortcuts, scroll to active tab

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift, libs/content/workspace-ffi/src/apple/api.rs, libs/content/workspace-ffi/src/apple/ios/api.rs, libs/content/workspace-ffi/src/apple/macos/api.rs
fixes #2835 
This PR also adds kinetic scrolling.
https://github.com/user-attachments/assets/4436e274-d6f8-4ab1-b378-95c74d571bcd
=> iPadOS: pointer support for workspace

libs/content/workspace/src/tab/markdown_editor/ast.rs
fixes https://github.com/lockbook/lockbook/issues/2764
https://github.com/user-attachments/assets/87aa437d-d744-437e-be8e-c131253dc1d3
=> editor: tab bug fix

libs/content/workspace-ffi/src/apple/ios/api.rs
fixes https://github.com/lockbook/lockbook/issues/2840
=> ios: fix selection rects

libs/content/workspace/src/widgets/toolbar.rs
=> wrap toolbar header from h6 to h1

Cargo.lock, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/parser.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/renderer.rs, libs/content/workspace/src/tab/svg_editor/selection/mod.rs, libs/content/workspace/src/tab/svg_editor/selection/rect.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/theme/icons.rs
enjoy watching me struggle figuring out how to end a video recording 
https://github.com/user-attachments/assets/9672e036-9914-46e5-99b1-1adfca09a690
=> canvas: layers

libs/content/workspace/src/tab/svg_editor/pen.rs
=> canvas: fix stroke connecting on non touch screens

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift
=> apple: fix new file workspace button

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2753
=> workspace: close tab on pointer release

libs/content/workspace/src/output.rs
fixes https://github.com/lockbook/lockbook/issues/2865
=> workspace: grammar

Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/account/mod.rs, clients/egui/src/account/modals/mod.rs, clients/egui/src/account/modals/search.rs, clients/egui/src/account/syncing.rs, clients/egui/src/account/tree/mod.rs, clients/egui/src/account/tree/node.rs, clients/egui/src/main.rs, clients/linux/Cargo.toml, clients/linux/src/input/pointer.rs, clients/linux/src/window.rs, clients/windows/Cargo.toml, clients/windows/src/input/mouse.rs, clients/windows/src/window.rs, libs/content/editor/egui_editor/Cargo.toml, libs/content/workspace-ffi/Cargo.toml, libs/content/workspace-ffi/src/apple/api.rs, libs/content/workspace-ffi/src/apple/init.rs, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/markdown_editor/draw.rs, libs/content/workspace/src/tab/svg_editor/selection/rect.rs, libs/content/workspace/src/theme/icons.rs, libs/content/workspace/src/widgets/button.rs, libs/content/workspace/src/widgets/button_group.rs, libs/content/workspace/src/widgets/progress_bar.rs, libs/content/workspace/src/widgets/switch.rs, libs/content/workspace/src/widgets/toolbar.rs, libs/content/workspace/src/workspace.rs, utils/winstaller/Cargo.toml
fixes https://github.com/lockbook/lockbook/issues/2610
=> all: update to egui 0.28.1

clients/apple/iOS/ConstrainedHomeView.swift, clients/apple/iOS/FilePathBreadcrumb.swift
=> iOS: stop scroll snap

libs/content/workspace/src/tab/mod.rs, libs/content/workspace/src/workspace.rs
=> editor: fix collaborative editing self-conflict

libs/content/workspace/src/widgets/toolbar.rs
request: https://discord.com/channels/1014184997751619664/1026211549678936214/1293617361974460650
fixes https://github.com/lockbook/lockbook/issues/2914
=> editor: add missing toolbar buttons

libs/content/workspace-ffi/src/apple/keyboard.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2907
https://github.com/user-attachments/assets/1c78346f-5da5-47da-a837-a3d393492a2b
=> add support for cmd+shift+[ and ]

libs/lb/lb-rs/src/text/buffer.rs
fixes https://github.com/lockbook/lockbook/issues/2920
=> editor: fix undo checkpoints

libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs
=> canvas: reverse elements insertion order and increase highlighter thickness

libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/workspace.rs
=> editor: layout fixes

libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/find.rs
=> editor: make find in doc prettier

libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/theme/icons.rs
=> canvas: zoom lock

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2897
=> editor: fix tab close on pointerless devices

libs/content/workspace/src/tab/markdown_editor/ast.rs, libs/content/workspace/src/tab/markdown_editor/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/2839
https://github.com/user-attachments/assets/4c5422de-cdcb-4282-8001-67bcf849155f
=> editor: indent to your heart's content

clients/apple/macOS/TreeView/FileTreeView.swift
fixes https://github.com/lockbook/lockbook/issues/2910
=> macOS: fix cmd-n and cmd-shift-n

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift
=> iOS: fix text input pen crashes

libs/content/workspace-ffi/src/lib.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2955
=> workspace: prettier tab strip

libs/content/workspace/src/tab/markdown_editor/appearance.rs, libs/content/workspace/src/tab/markdown_editor/ast.rs, libs/content/workspace/src/tab/markdown_editor/draw.rs, libs/content/workspace/src/tab/markdown_editor/galleys.rs, libs/content/workspace/src/tab/markdown_editor/input/mutation.rs, libs/content/workspace/src/tab/markdown_editor/layouts.rs, libs/content/workspace/src/tab/markdown_editor/style.rs
fixes https://github.com/lockbook/lockbook/issues/2450
fixes https://github.com/lockbook/lockbook/issues/2957
fixes https://github.com/lockbook/lockbook/issues/2958
<details>
</details>
=> editor: pretty code blocks & block quotes

libs/content/workspace-ffi/src/apple/keyboard.rs
fixes https://github.com/lockbook/lockbook/issues/2762
=> workspace: add macos delete key keycode

Cargo.lock, libs/content/workspace-ffi/src/apple/init.rs, libs/content/workspace-ffi/src/lib.rs, libs/content/workspace/Cargo.toml, libs/content/workspace/src/tab/svg_editor/eraser.rs, libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/parser.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/renderer.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/theme/icons.rs, libs/content/workspace/src/theme/palette.rs, libs/content/workspace/src/widgets/button.rs
https://github.com/user-attachments/assets/d218b1fe-afb5-4b53-9d45-3f73cb502057
the toolbar with a ui overlay
=> canvas: ui overlay 

libs/content/workspace/src/workspace.rs
=> workspace: hide tab strip when <= 1 tabs

libs/lb/lb-rs/src/text/buffer.rs
fixes https://github.com/lockbook/lockbook/issues/2908
see test cases for documentation of changed behavior
=> lbrs: concurrent edits choose a winner

clients/egui/src/account/mod.rs, libs/content/workspace/src/background.rs, libs/content/workspace/src/syncing.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2749
fixes https://github.com/lockbook/lockbook/issues/2295
todo
=> workspace: save then sync + sync way more often

clients/linux/src/input/key.rs, clients/windows/src/input/key.rs
fixes https://github.com/lockbook/lockbook/issues/2980
=> windows/linux: support cutting and copying from non-editor sources

libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/lb/lb-rs/src/text/buffer.rs
fixes https://github.com/lockbook/lockbook/issues/2983
fixes https://github.com/lockbook/lockbook/issues/2994
=> editor: don't scroll when checking checkbox / don't dismiss virtual keyboard when text wraps

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2995
<details>
</details>
=> editor: mobile title visual updates

libs/content/workspace/src/tab/markdown_editor/ast.rs, libs/content/workspace/src/tab/markdown_editor/draw.rs, libs/content/workspace/src/tab/markdown_editor/galleys.rs, libs/content/workspace/src/tab/markdown_editor/input/canonical.rs, libs/content/workspace/src/tab/markdown_editor/layouts.rs, libs/content/workspace/src/tab/markdown_editor/style.rs
fixes https://github.com/lockbook/lockbook/issues/2979
<details>
</details>
=> editor: code block language badges

libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs
fixes https://github.com/lockbook/lockbook/issues/3003
<details>
</details>
=> canvas: add background

libs/content/workspace/src/tab/markdown_editor/appearance.rs, libs/content/workspace/src/tab/markdown_editor/draw.rs, libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/galleys.rs, libs/content/workspace/src/tab/markdown_editor/input/cursor.rs, libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/content/workspace/src/theme/icons.rs
=> editor: visual refinements to paragraph spacing and checkboxes

libs/content/workspace/src/tab/markdown_editor/draw.rs
addresses https://github.com/lockbook/lockbook/pull/3023#issuecomment-2442022801
=> editor: visual refinements to paragraph spacing and checkboxes pt 2

libs/lb/lb-rs/src/text/buffer.rs
fixes https://discord.com/channels/1014184997751619664/1299485512226046014/1299487331044294747
=> editor: fix collaborative editing crash

libs/content/workspace/src/tab/markdown_editor/draw.rs
fixes https://github.com/lockbook/lockbook/issues/3027
=> editor: fix end of document heading and block quote rendering

libs/content/workspace/src/tab/svg_editor/mod.rs
=> canvas: fix overflowing toolbar fix

libs/content/workspace/src/workspace.rs
=> workspace: fix mobile title light mode color

docs/CONTRIBUTING.md, docs/QA.md, docs/SEVERITY.md
- Update CONTRIBUTING.md to highlight PR desc requirements
- Create a SEVERITY guidelines for some shared language around defect prioritization
- Specify our QA procedure
=> docs: document some processes

clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt, clients/android/app/src/main/java/app/lockbook/screen/MainScreenActivity.kt, clients/android/app/src/main/java/app/lockbook/util/ThemeMode.kt, clients/android/app/src/main/res/drawable/outline_brightness_2_24.xml, clients/android/app/src/main/res/layout/header_navigation_drawer_files_list.xml, clients/android/app/src/main/res/values/strings.xml, clients/android/app/src/main/res/xml/settings_preference.xml
fixes #3067
https://github.com/user-attachments/assets/4cfbb167-6357-4ea6-931b-709e9999da33
=> android: manual theme setting

Cargo.lock, clients/linux/Cargo.toml, clients/linux/src/input/key.rs, clients/linux/src/window.rs, docs/guides/build/linux.md
<details>
<summary>Demo</summary>
https://github.com/user-attachments/assets/7517fa68-29e8-45c2-a99f-46164ff349b9
</details>
+ [x] cleanup
+ [x] spawn egui Text events
+ [ ] test
fixes #2982
=> linux: support keymaps

clients/egui/src/account/mod.rs, clients/egui/src/splash.rs
fixes https://github.com/lockbook/lockbook/issues/3080
fixes https://github.com/lockbook/lockbook/issues/3085
=> egui: app lifecycle refinements

libs/content/workspace/src/tab/markdown_editor/input/mutation.rs
...and by line I mean paragraph, is in lines that are separated by newline characters ignoring text wrapping.
fixes https://github.com/lockbook/lockbook/issues/3081
=> editor: cut/copy lines when selection is empty

libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/content/workspace/src/tab/markdown_editor/input/mod.rs
fixes https://github.com/lockbook/lockbook/issues/3006
fixes https://github.com/lockbook/lockbook/issues/3078
=> editor: input refinements

clients/linux/src/window.rs, clients/windows/src/window.rs, libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift, libs/content/workspace-ffi/src/android/response.rs, libs/content/workspace-ffi/src/apple/api.rs, libs/content/workspace-ffi/src/apple/ios/response.rs, libs/content/workspace-ffi/src/apple/macos/response.rs, libs/content/workspace-ffi/src/response.rs, libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/content/workspace/src/theme/icons.rs
going with a non-native approach for the context menu
fixes https://github.com/lockbook/lockbook/issues/2025
fixes https://github.com/lockbook/lockbook/issues/2919
<details>
https://github.com/user-attachments/assets/eaaef7b4-0107-4faa-b018-cc04203082a8
</details>
=> editor: context menu with clipboard ops

libs/content/workspace/src/syncing.rs, libs/content/workspace/src/tab/mod.rs, libs/content/workspace/src/workspace.rs
<details>
<summary>Demo</summary>
https://github.com/user-attachments/assets/ad7f90df-e860-4d34-a279-c13af059913e
</details>
=> workspace: queue sync reloads instead of reloading on save

clients/android/app/src/main/java/app/lockbook/screen/WorkspaceFragment.kt
=> android: fix AOSP keyboard character duplication

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift, libs/content/workspace-ffi/src/apple/ios/api.rs, libs/content/workspace/src/tab/svg_editor/eraser.rs, libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/selection.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/tab/svg_editor/util.rs, utils/dev/autorun-apple.sh
=> canvas: support draw only with apple pencil

Cargo.lock, server/server/Cargo.toml, server/server/src/loggers.rs
=> server: use a gcp optimized log format

libs/content/workspace/src/tab/svg_editor/eraser.rs
=> canvas: add pen hover for eraser

libs/content/workspace/src/tab/svg_editor/toolbar.rs
=> canvas: dismiss tool controls

clients/egui/src/account/modals/confirm_delete.rs, clients/egui/src/account/modals/file_picker.rs, clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/account/modals/settings/usage_tab.rs, clients/egui/src/model.rs, clients/linux/src/input/clipboard_paste.rs, clients/linux/src/input/file_drop.rs, libs/content/workspace/src/tab/markdown_editor/ast.rs, libs/content/workspace/src/tab/svg_editor/path_builder.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/widgets/subscription.rs, libs/content/workspace/src/workspace.rs, libs/lb/lb-rs/Cargo.toml, libs/lb/lb-rs/src/lib.rs, libs/lb/lb-rs/src/logic/lazy.rs, libs/lb/lb-rs/src/logic/server_file.rs, libs/lb/lb-rs/src/service/account.rs, libs/lb/lb-rs/src/svg/buffer.rs, libs/lb/lb-rs/tests/core_ops_tests.rs, rust-toolchain.toml, utils/dev-tool/src/android.rs, utils/releaser/src/secrets.rs
=> infra: bump rust version

libs/content/workspace/src/tab/svg_editor/renderer.rs, libs/lb/lb-rs/src/svg/element.rs
=> canvas: invalidate mesh cash on drastic zoom

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift, libs/content/workspace-ffi/src/apple/api.rs, libs/content/workspace-ffi/src/apple/ios/api.rs
fixes https://github.com/lockbook/lockbook/issues/3002
=> macOS: notify pointer gone to workspace

clients/egui/src/lib.rs, clients/linux/src/window.rs, clients/windows/src/window.rs, libs/content/workspace-ffi/src/android/init.rs, libs/content/workspace-ffi/src/apple/init.rs, libs/content/workspace-ffi/src/lib.rs
=> workspace: anti aliasing 

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift
=> iPadOS: fix kinetic scroll

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift, libs/content/workspace-ffi/src/apple/ios/api.rs, libs/content/workspace/src/tab/markdown_editor/input/canonical.rs
fixes #3142
https://github.com/user-attachments/assets/505caf91-f793-4d61-b67d-12df6b912435
=> iPadOS: support editor navigation and selection using arrow keys

libs/lb/lb-rs/src/service/activity.rs
=> lb: fix suggested docs

clients/apple/Shared/Stateful Logic/AccountService.swift, clients/apple/Shared/Stateful Logic/BillingService.swift, clients/apple/Shared/Stateful Logic/DI.swift, clients/apple/Shared/Stateful Logic/ErrorService.swift, clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Stateful Logic/ImportExportService.swift, clients/apple/Shared/Stateful Logic/OnboardingState.swift, clients/apple/Shared/Stateful Logic/SettingsService.swift, clients/apple/Shared/Stateful Logic/ShareService.swift, clients/apple/Shared/Stateful Logic/SyncService.swift, clients/apple/Shared/Views/AppView.swift, clients/apple/iOS/OutlineView/OutlineBranch.swift, clients/apple/lockbook.xcodeproj/project.pbxproj
And a little error naming refactor.
=> apple: fix error dialogs

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift
fixes https://github.com/lockbook/lockbook/issues/3157
=> iPadOS: notify workspace when "only draw with apple pencil" state changes

Cargo.lock, server/Cargo.toml, server/src/loggers.rs, server/src/router_service.rs
+ I wrote a better tracing subscriber for gcp's structured logging format: https://github.com/lockbook/tracing-gcp
+ using the features in that crate I added more context to our primary request handler
=> server: good ass logs

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/WorkspaceState.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/WorkspaceView.swift
fixes https://github.com/lockbook/lockbook/issues/2747
=> iOS: remove old exit doc gesture

clients/apple/ShareExtension/ShareViewController.swift, clients/apple/Shared/Stateful Logic/FileService.swift, clients/apple/Shared/Views/AppView.swift
=> apple: fix sharing into iOS

libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/tab/markdown_editor/input/mutation.rs, libs/content/workspace/src/workspace.rs
fixes #3179 
fixes #3178 
fixes #3048
=> iOS/editor: native cursor & padding interaction improvements

libs/content/workspace/src/tab/svg_editor/pen.rs
=> canvas: accurate hover preview in fixed thickness mode

libs/content/workspace/src/tab/svg_editor/toolbar.rs, utils/dev/autorun-apple.sh
=> canvas: ensure color swatches are clicked with a drag

libs/content/workspace/src/tab/svg_editor/renderer.rs
=> canvas: fix tool island flicker

libs/content/workspace/src/show.rs
diff mostly due to change in indentation
=> workspace: don't crash when closing tabs other than final tab

Cargo.lock, clients/egui/src/account/mod.rs, clients/egui/src/account/modals/settings/general_tab.rs, clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/settings.rs, libs/content/workspace-ffi/src/android/init.rs, libs/content/workspace-ffi/src/apple/init.rs, libs/content/workspace/Cargo.toml, libs/content/workspace/src/show.rs, libs/content/workspace/src/workspace.rs
in lieu of the [old pr](https://github.com/lockbook/lockbook/pull/3192)
=> workspace: persistence

Cargo.lock, clients/egui/src/account/mod.rs, clients/egui/src/account/modals/settings/general_tab.rs, clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/settings.rs, libs/content/workspace-ffi/src/android/init.rs, libs/content/workspace-ffi/src/apple/init.rs, libs/content/workspace/Cargo.toml, libs/content/workspace/src/show.rs, libs/content/workspace/src/workspace.rs
Reverts lockbook/lockbook#3273
=> Revert "workspace: persistence"

clients/egui/src/account/mod.rs, clients/egui/src/account/tree.rs
fixes [#3264](https://github.com/lockbook/lockbook/issues/3264)
fixes [#2717](https://github.com/lockbook/lockbook/issues/2717)
fixes https://github.com/lockbook/lockbook/issues/3303 (although a probably-egui bug sometimes prevents it from scrolling properly - tested by opening a file with cmd+L search)
fixes [#3304](https://github.com/lockbook/lockbook/issues/3304)
<details>
https://github.com/user-attachments/assets/9090f68b-1755-43ee-b473-ad640e41a133
</details>
=> egui: file tree refinements

clients/egui/src/account/mod.rs, clients/egui/src/account/modals/help.rs, libs/content/workspace/src/tab/markdown_editor/editor.rs, libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/3308
fixes https://github.com/lockbook/lockbook/issues/2692
=> egui/workspace: misc refinements

clients/egui/src/account/tree.rs
fixes https://github.com/lockbook/lockbook/issues/3234
=> egui: auto scroll file tree when dragging

clients/egui/src/account/full_doc_search.rs
=> egui: fix search results crash for docs with special characters

libs/lb/lb-rs/src/service/search.rs
=> lb-rs: visibility into some search index maintenance

clients/cli/src/input.rs, libs/lb/lb-rs/src/service/events.rs, libs/lb/lb-rs/src/service/search.rs, libs/lb/lb-rs/src/service/sync.rs
=> lb-rs: fix initial sync search index

clients/egui/src/account/modals/confirm_delete.rs
output is pretty clear from the code diff
fixes #3305
=> egui: better delete confirmation message

clients/egui/src/account/modals/settings/account_tab.rs, clients/egui/src/account/modals/settings/mod.rs, clients/egui/src/lib.rs, libs/lb/lb-c/src/lib.rs, libs/lb/lb-java/src/lib.rs
fixes #3263 
fixes #3300 
<details>
https://github.com/user-attachments/assets/6bfff882-7e36-430b-8fba-4f825bc513c8
</details>
todo:
=> egui: logout and passphrase export

libs/lb/lb-rs/src/logic/core_ops.rs, libs/lb/lb-rs/src/service/account.rs, libs/lb/lb-rs/tests/sharing_tests.rs
=> lb-rs: populate last_modified_by properly

libs/content/workspace/src/show.rs, libs/lb/lb-rs/src/model/account.rs
Also adds users to beta users list (their approval is required). This change allows us to release the new landing page and other improvements even though there's a resource leak with mind map right now.
=> workspace: beta-only mind map 

libs/content/workspace/src/show.rs
=> workspace: placeholder message when there are no suggestions

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift, libs/content/workspace/src/tab/image_viewer.rs
fixes https://github.com/lockbook/lockbook/issues/3404
=> workspace/apple: case insensitive image file extensions

libs/content/workspace/src/tab/image_viewer.rs, libs/content/workspace/src/tab/pdf_viewer.rs
fixes https://github.com/lockbook/lockbook/issues/3403
=> workspace: extreme bg for images and pdfs

libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/macMTK.swift, libs/content/workspace-ffi/src/apple/macos/api.rs
fixes https://github.com/lockbook/lockbook/issues/3380
=> macOS: fix german keyboard input

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/3390
=> workspace: reload file when sync pulls an update (regression)

libs/content/workspace/src/show.rs
QA'd:
- platforms:
- macos
- egui on macos
- ios (ipad)
- ios (iphone)
- actions:
- tap to rename
- tab close button
- click in md near top of screen
- draw in svg near top of screen
- open a pdf
- open an image
=> workspace: always show tabs

.github/workflows/bump-versions.yml
so far this seems to work on the github hosted runner
=> infra: workflow that bumps versions

libs/content/workspace/src/tab/svg_editor/selection.rs
=> canvas: fix scaling history bug

utils/releaser/src/version.rs
Thought about also also adding the deletion of the bump branch, any thoughts on that ?
=> infra: auto merging version bump commit into master

libs/content/workspace/src/tab/mod.rs, libs/content/workspace/src/tab/svg_editor/pen.rs, libs/content/workspace/src/tab/svg_editor/renderer.rs, libs/content/workspace/src/tab/svg_editor/selection.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs, libs/content/workspace/src/workspace.rs, libs/lb/lb-rs/src/model/svg/buffer.rs, libs/lb/lb-rs/src/model/svg/element.rs, libs/lb/lb-rs/src/service/sync.rs
Reverts lockbook/lockbook#3521
=> Revert "canvas: pen pressure senstivity (noncompliant)"

Cargo.lock, clients/egui/Cargo.toml, clients/egui/src/theme.rs
=> linux: fix dark & light mode detection

libs/content/workspace/src/tab/svg_editor/renderer.rs
=> canvas: fix minimap thickness bug

libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/mod.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs
=> canvas: enforce max lower zoom level and extend grid range

libs/content/workspace/src/tab/svg_editor/clip.rs, libs/content/workspace/src/tab/svg_editor/gesture_handler.rs, libs/content/workspace/src/tab/svg_editor/toolbar.rs
=> canvas: autoselect and auto size image on paste

libs/content/workspace/src/file_cache.rs
fixes annoying issue where tab titles got stuck saying Loading...
=> workspace: remove un-needed network call

libs/content/workspace/src/tab/svg_editor/renderer.rs, libs/content/workspace/src/tab/svg_editor/selection.rs, libs/lb/lb-rs/src/service/logging.rs
=> canvas: stretch scaling

libs/content/workspace/src/tab/svg_editor/toolbar/tools_island.rs
=> canvas: better pen thickness presets

clients/apple/Shared/Widgets/SyncButton.swift, clients/apple/iOS/Widgets/StatusBarView.swift, clients/apple/macOS/Widgets/StatusBarView.swift
=> apple: new status bar

clients/apple/Shared/LockbookApp.swift, clients/apple/Shared/Screens/OutOfSpaceAlert.swift, clients/apple/Shared/Screens/UpgradeAccountView.swift, clients/apple/Shared/State/AppState.swift, clients/apple/Shared/State/BillingState.swift, clients/apple/Shared/State/HomeState.swift, clients/apple/Shared/Widgets/SyncButton.swift, clients/apple/iOS/Screens/HomeView.swift, clients/apple/iOS/Screens/SettingsView.swift, clients/apple/iOS/Widgets/FileTreeView.swift, clients/apple/macOS/Screens/HomeView.swift, clients/apple/macOS/Screens/SettingsView.swift
fixes https://github.com/lockbook/lockbook/issues/3170
<details>
https://github.com/user-attachments/assets/e254a3e9-7777-40b5-a46f-824c0060e3b5
https://github.com/user-attachments/assets/39f1f14c-c6d7-4751-bacd-d6e2009839c8
</details>
=> apple: fix out of space experience

clients/apple/Shared/State/SettingsViewModel.swift, clients/apple/iOS/Screens/SettingsView.swift, clients/apple/macOS/Screens/SettingsView.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/Lb/Billing.swift
=> apple: cancel subscription

clients/apple/macOS/Widgets/FileTree/FileTreeView.swift
fixes https://github.com/lockbook/lockbook/issues/3563
=> macOS: filetree icons resist shrinking

libs/content/workspace/src/show.rs, libs/content/workspace/src/tab/markdown_editor/mod.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/image/cache.rs, libs/content/workspace/src/tab/mod.rs
=> workspace: open relative links

Cargo.lock, libs/content/workspace-ffi/SwiftWorkspace/create_libs.sh, libs/content/workspace/Cargo.toml
=> workspace: use latest comrak from git

libs/content/workspace/src/tab/markdown_editor/widget/block/container/alert.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/code.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/footnote_reference.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/link.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/mod.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/text.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/wiki_link.rs, libs/content/workspace/src/tab/markdown_editor/widget/utils/text_layout.rs
fixes "links not clickable on mobile" from https://github.com/lockbook/lockbook/issues/3627
=> editor: clickable links on mobile

clients/android/app/src/main/java/app/lockbook/billing/BillingClientLifecycle.kt
=> android: fix an error occured upon opening the app

clients/apple/Shared/LockbookApp.swift
=> apple: remove unsupported multi-window

clients/android/app/src/main/java/app/lockbook/model/FilesListViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt, clients/android/app/src/main/java/app/lockbook/util/FileItemViewHolder.kt, clients/android/app/src/main/res/layout/layout_suggested_docs.xml, clients/android/app/src/main/res/values/strings.xml, libs/lb/lb-java/lib/src/main/java/net/lockbook/Lb.java
does the android portion of #2337
https://github.com/user-attachments/assets/701c37f7-292b-4bd1-bf1d-4180d977cc46
=> android: remove entries from suggested docs

clients/android/app/src/main/java/app/lockbook/model/SearchDocumentsViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/WorkspaceViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/MainScreenActivity.kt, clients/android/app/src/main/java/app/lockbook/util/WorkspaceView.kt
=> android: fix search crash

libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/3684
=> ws: close tabs without skill issues

clients/android/app/src/main/java/app/lockbook/screen/MainScreenActivity.kt, libs/content/workspace/src/tab/svg_editor/toolbar/viewport_island.rs
=> canvas: fix inf to notebook switch logic

libs/content/workspace-ffi/src/android/api.rs, libs/content/workspace-ffi/src/apple/ios/api.rs, libs/content/workspace/src/tab/markdown_editor/input/canonical.rs, libs/content/workspace/src/tab/markdown_editor/input/events.rs, libs/content/workspace/src/tab/markdown_editor/input/mod.rs, libs/content/workspace/src/tab/markdown_editor/input/mutation.rs, libs/content/workspace/src/tab/markdown_editor/widget/block/container/task_item.rs
https://github.com/user-attachments/assets/2513fe86-6206-42c4-b531-c3a452062146
=> editor: fix checkbox advancing cursor on desktop

clients/android/app/src/main/java/app/lockbook/model/FilesListViewModel.kt, clients/android/app/src/main/java/app/lockbook/model/StateViewModel.kt, clients/android/app/src/main/java/app/lockbook/screen/FilesListFragment.kt, clients/android/app/src/main/java/app/lockbook/screen/MainScreenActivity.kt, clients/android/app/src/main/java/app/lockbook/ui/CreateFileDialogFragment.kt
fixes: #1913 
https://github.com/user-attachments/assets/4f9e9cc1-077e-4efd-af68-a6d8c93f8b89
=> adnroid: new new file experience

clients/android/app/src/main/res/values/strings.xml
=> android: change pending share screen text

clients/apple/Shared/State/HomeState.swift, clients/apple/iOS/Widgets/FileTreeView.swift, clients/apple/macOS/Widgets/FileTree/FileTreeView.swift
=> apple: close settings/pending shares/upgrade account when file tree is clicked

libs/content/workspace/src/tab/markdown_editor/widget/block/leaf/thematic_break.rs, libs/content/workspace/src/tab/markdown_editor/widget/mod.rs
fixes https://github.com/lockbook/lockbook/issues/3728
https://github.com/user-attachments/assets/2633a9eb-cda1-4d23-bc2f-1ec00e882c89
=> editor: fix thematic break editing experience

clients/android/app/src/main/res/layout/activity_upgrade_account.xml, clients/android/app/src/main/res/values/strings.xml, docs/README.md, libs/lb/lb-rs/src/model/api.rs, libs/lb/lb-rs/tests/get_usage_tests.rs, utils/lbdev/src/ci/mod.rs, utils/lbdev/src/local/mod.rs, utils/lbdev/src/main.rs
=> server: expand free tier 1mb --> 25mb

clients/apple/Shared/Screens/ImportFilePicker.swift, clients/apple/Shared/Screens/SelectFolderSheet.swift, clients/apple/Shared/State/SelectFolderViewModel.swift, clients/apple/Shared/State/SheetInfo.swift, clients/apple/Shared/Utils/FileOpsSheets.swift, clients/apple/Shared/Utils/OnLbLinkViewModifier.swift, clients/apple/iOS/Screens/HomeView.swift
fixes #3352
Demo:
https://github.com/user-attachments/assets/79ac2ce9-21b9-49e9-aa78-fb9b9b27ca2c
=> apple: added importing from within iOS

libs/content/workspace/src/tab/markdown_editor/widget/inline/code.rs, libs/content/workspace/src/tab/markdown_editor/widget/inline/mod.rs
fixes https://github.com/lockbook/lockbook/issues/3745
=> editor: fix inline code spans

clients/apple/Shared/State/SettingsViewModel.swift, clients/apple/Shared/Widgets/PendingSharesIcon.swift, clients/apple/Shared/Widgets/SyncButton.swift, libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/Lb/Events.swift, libs/lb/lb-c/src/lib.rs, libs/lb/lb-c/src/mem_cleanup.rs
=> apple: add sync tooltip info, show failed sync errors, and offline error messages

clients/android/app/src/main/java/app/lockbook/screen/WorkspaceFragment.kt, clients/android/app/src/main/java/app/lockbook/ui/CreateFileDialogFragment.kt, libs/content/workspace/src/show.rs, libs/content/workspace/src/workspace.rs
=> android: collapse file name under the menu bar

clients/apple/Shared/Screens/ShareFileSheet.swift
=> apple: fix text in sharesheet

clients/android/app/src/main/res/layout/fragment_files_list.xml
fixes: #3202 
https://github.com/user-attachments/assets/1bf8a1a6-bac5-4b96-be44-e7d3ac04cb99
https://github.com/user-attachments/assets/e0a96e47-8556-4500-b6d0-4642ba25d9a4
=> android: fix weird file tree pulling behavior

libs/lb/lb-rs/src/service/account.rs, libs/lb/lb-rs/tests/account_service_tests.rs
Markdown is a language for easily formatting your documents. This document can help you get started.
To style text, wrap your text in the corresponding characters.
| Style         | Syntax              | Example           |
|---------------|---------------------|-------------------|
| emphasis      | `*emphasis*`        | *emphasis*        |
| strong        | `**strong**`        | **strong**        |
| strikethrough | `~~strikethrough~~` | ~~strikethrough~~ |
| underline     | `__underline__`     | __underline__     |
| code          | ``code``            | `code`            |
| spoiler       | `||spoiler||`       | ||spoiler||       |
| superscript   | `^superscript^`     | ^superscript^     |
| subscript     | `~subscript~`       | ~subscript~       |
To make text into a link, wrap it …
=> lbrs: new welcome doc
