lockbook/lockbook

- Makefile
- containers/Dockerfile.cli
- containers/Dockerfile.core
- containers/Dockerfile.integration_tests
- containers/Dockerfile.server
- core/src/lib.rs
- core/src/repo/account_repo.rs
- core/src/repo/db_provider.rs
- core/src/repo/file_metadata_repo.rs
- core/src/repo/file_repo.rs
- core/src/service/auth_service.rs
- core/src/service/file_encryption_service.rs
- docs/building.md
Removes NoneError/TryTrait in core, which was keeping us on nightly, then sets channel to stable in dockerfiles and removes references from readme. Uses `.ok_or(())` for options and replaces `NoneError` with `()`.
> Moves all builds to rust stable

- .gitignore
- Makefile
- core/src/client.rs
- core/src/lib.rs
- core/src/model/crypto.rs
- core/src/model/local_changes.rs
- core/src/model/work_unit.rs
- core/src/repo/db_provider.rs
- core/src/repo/local_changes_repo.rs
- core/src/service/account_service.rs
- core/src/service/file_encryption_service.rs
- core/src/service/sync_service.rs
- dev_utils/fmt_all.sh
- docker-compose.yml
- integration_tests/src/account_service_tests.rs
- integration_tests/src/sync_service_tests.rs
- server/src/file_service.rs
Added integration tests that that exercised:
+ Creating an account
+ Exporting an account string
+ Importing an account string
+ Syncing early account state
+ Creating files and folders and syncing
+ Editing files and folders and syncing
The cool thing about these tests is that I assert various repo level things must be exactly the same post syncs (all files in db1 == all files in db2). Let's me catch all sorts of small errors that would get missed if you were just making sure `id`s or file contents are equal.
Also added some `dev_utils` and added the command I used to free up several hundred gigabytes on our compute node and locally.
> Sync integration tests and bugfixes

- clients/cli/src/edit.rs
- clients/cli/src/new.rs
reorder file creation to happen later, create a uuid folder for no file system conflicts, and create a file inside there with `file_metadata.name`. Editor will pickup this and name tabs accordingly. And will also pickup file extension for syntax highlighting.
> Expose name to editor for syntax highlighting

- public_site/layouts/index.html
- public_site/layouts/partials/introduction.html
This PR moves the main title heading to just above the other content and makes each section of text one paragraph instead of multiple. Due to these changes, the `main` element was also given a `max-width`.
It also includes a small syntax fix.
> website: Move the main title heading and compress the text.

- clients/cli/Cargo.lock
- clients/cli/Cargo.toml
- core/src/repo/local_changes_repo.rs
- core/tests/sync_service_tests.rs
`LocalChangesRepo` successfully is able to handle the following:
(no changes, a.content == "hi")
"hi" -> "bye" -- 1 change
"bye" -> "hi" -- 0 changes
But it did the following 
(no changes, a.content == "hi")
"hi" -> "hi" -- 1 change
This happened because it had no previous checksum to compare "hi" to.
This explicitly handles this (very common) edge case.
> Make sure not really changing a file doesn't change a file

- clients/windows/FileExplorer.xaml
- clients/windows/FileExplorer.xaml.cs
- clients/windows/windows.csproj
we used to save (and encrypt) on every keystroke. now we batch saves takes the CPU utilization from like 25% back to barely measurable.
closes #225
> Make autosave far more CPU efficient

- clients/cli/src/init.rs
sample output:
```
~/code/lockbook/clients/cli 239-cli-whitespace* ❯ lockbook init
Enter a Username: travis 22
[2020-08-24 11:01:52] [lockbook_core::service::account_service ] [INFO ]: Checking if account already exists
[2020-08-24 11:01:52] [lockbook_core::service::account_service ] [INFO ]: Creating new account for travis 22
[2020-08-24 11:01:52] [lockbook_core::service::account_service ] [INFO ]: Generating Key...
[2020-08-24 11:01:52] [lockbook_core::service::account_service ] [INFO ]: Generating Root Folder
[2020-08-24 11:01:52] [lockbook_core::service::account_service ] [INFO ]: Sending username & public key to server
Username is not a-z || 0-9
```
```
~/code/lockbook/clients/cli 239-cli-whitespace* 2s ❯ lockbook init
Enter a Username: travis22
[2020-08-24 11:01:57] …
```
> Makes CLI not accept usernames with whitespace

- core/src/service/account_service.rs
- core/src/service/auth_service.rs
- core/src/service/file_encryption_service.rs
- core/src/service/file_service.rs
- core/src/service/sync_service.rs
Currently, `PhantomData` is being used to suppress `field is never read` warnings. `PhantomData` is described with the following excerpt ([3rd para](https://doc.rust-lang.org/nomicon/phantom-data.html)) from [The Rustonomicon](https://doc.rust-lang.org/nomicon/index.html) (a book on "The Dark Arts of Unsafe Rust"):
> We do this using PhantomData, which is a special marker type. PhantomData consumes no space, but simulates a field of the given type for the purpose of static analysis. This was deemed to be less error-prone than explicitly telling the type-system the kind of variance that you want, while also providing other useful things such as the information needed by drop check.
I think the more idiomatic way of suppressing unused warnings is to prefix the fields with an underscore:
* …
> refactor: Remove the use of PhantomData in favor of underscore.

- clients/cli/Cargo.lock
- clients/cli/Cargo.toml
- clients/cli/src/backup.rs
- clients/cli/src/copy.rs
- clients/cli/src/export_private_key.rs
- clients/cli/src/import_private_key.rs
- clients/cli/src/main.rs
- clients/cli/src/new_account.rs
You can now `lockbook backup`. This will create a folder named `LOCKBOOK_BACKUP_2020-09-26` in your `pwd`. It will create all your content in this directory, folders and all. It will also create a `lockbook.index`, this makes restoring via `lockbook copy` much more straightforward.
```
[~/test]: lockbook backup 
Creating an index to keep track of 6 files
Creating 4 folders
Writing 5 documents
```
Restore is implemented by making `copy` more powerful. 
+ `lockbook copy` now takes a target file on your local file system *and a target location within your lockbook for where you want this file to end up*. 
+ It also takes an optional `--edit` flag which tells CLI to overwrite the content of this this file if it already exists. 
+ If your specified lockbook destination is a folder it will take …
> Backup and Restore via CLI

- clients/android/lint.xml
- clients/apple/Shared/Book/BookView.swift
A force unwrap optional is causing a crash when creating a new account, because at some dubstep there are no items so force-getting the head of a list fails. Solved with optionals!
> Apple Crash on New Account

- clients/linux/src/backend.rs
- clients/linux/src/gui.rs
- clients/linux/src/main.rs
- clients/linux/src/menubar.rs
- clients/linux/src/messages.rs
- clients/linux/src/util.rs
* Create a util mod (for now just has bytes to human readable string function).
* Add method on `LbCore` to use core `get_usage` function.
* Create the usage dialog interface.
* Add a `Msg` and Menubar item for opening the new usage dialog.
Closes #306.
> linux: Show Account usage in a dialog.

- clients/linux/Cargo.lock
- clients/linux/Cargo.toml
- clients/linux/src/account.rs
- clients/linux/src/backend.rs
- clients/linux/src/editmode.rs
- clients/linux/src/filetree.rs
- clients/linux/src/gui.rs
- clients/linux/src/intro.rs
- clients/linux/src/main.rs
- clients/linux/src/menubar.rs
- clients/linux/src/messages.rs
- containers/Dockerfile.linux
This PR primarily concerns the redesign of the Account screen header and the enhancements made to Open (aka. "search") by using fuzzy finding as well as a better Export Account and Delete Files UX. Some notes:
* The Account screen before, at the topmost level, was broken into two parts: the Sidebar and Editor. It is now broken into three parts: the Header, Sidebar, and Editor.
* The Header contains a text field, which can be focused via the `Ctrl-L` shortcut.
* The text field completion uses fuzzy finding. The results are sorted in descending order of fuzzy scoring (higher score means closer match).
* The Open dialog code is therefore gone now.
* The Export Account dialog is redesigned:
* A QR code is generated now. It takes enough time to do so that a loader is necessary, so it is shown …
> linux: Redesigned account screen header, enhanced search, redesign Export Account dialog, and other misc refactors.

- clients/cli/Cargo.lock
- server/src/main.rs
Tested via `lsof`, leaked before, does not leak now
Closes #322
> Server no longer leaks a resource

- clients/cli/src/calculate_usage.rs
* The units are in 1000s, changed to 1024s.
* The variable names represent a _single_ unit, so the plurality was dropped.
* A tuple is used to reduce the match statement by only getting the necessary parts and calculating afterwards instead of calculating and printing each in place.
> cli: Refactor calculate_usage code.

- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/intro.rs
Aside from the error handling pattern:
* The sync progress prefix is not customizable since it's not hardcoded in LbCore::sync
* Sync errors from lockbook_core are not specific to each work unit (could not reach server and client needs update). Therefore, those aren't tracked anymore. Sync just returns on one of those errors. If this changes in the future, and there are errors specific to a work unit that shouldn't halt the whole sync process, it's an easy adjustment.
* The work units (as well as the total) are sent down the channel as well with Work (so the specific instances can saying "syncing x (i / total)." This is also necessary for a progress bar (a future possibility).
> linux: Refactor sync error handling and improve sync ui. 

- clients/linux/src/backend.rs
- core/src/lib.rs
This also now makes the switch to using `map_err` for the `create_account` and `import_account` functions.
> core: Refactor to return Account when creating or importing one. 

- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/filetree.rs
* The purpose of `LbCore` is to encapsulate lockbook core functionality and add any additional functionality for the linux client. The layout of the code should reflect that, so it has been reordered to do so.
* All lockbook core errors are now handled with the `core_to_lb_err` macro. Some adjustments were made in the rest of the code base to accommodate the fact that errors are now handled as `LbError`s instead of `String`.
> linux: Refactors and cleanup related to core error handling.

- containers/Dockerfile.csharp_interface_tests
- containers/Dockerfile.kotlin_interface_tests
When originally running the csharp and kotlin test prep images, they would take minutes to finish building. This was due to the starting image, core. Core would cause both of these to recompile, though the reason is not directly known why. In this pull request, rather than the starting image being core, it is now ubuntu for both and core is only used on one of the last steps to pull the binary from.
fixes #465
> infra: fix cacheing problems for kotlin and csharp prep images

- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/main.rs
* This moves the db migration check and task into the initialization of a `LbCore` handle.
* Additionally, the user's `Account` is now stored within the `LbCore` handle instead of being read each time it is needed. This is now done in the initialization, as well as when an Account is created or imported.
> linux: Refactor init code for connecting to core and store the user Account.

- clients/android/app/src/main/java/app/lockbook/screen/InitialLaunchFigureOuter.kt
- clients/android/app/src/main/java/app/lockbook/screen/SettingsFragment.kt
Biometric subtitle is now more accurate. The rename was prompted by the fact biometric is not always a fingerprint, it can be face unlock or some other type of biometric verification.
fixes #535
> android: changed biometric verification subtitle

- clients/android/app/src/main/java/app/lockbook/ui/HandwritingEditorView.kt
Instead of saving strokes and points that happen outside of the drawable canvas, we now round them to their nearest max or min. 
For this PR I was originally planning to not save any points at all that left, but that had some unintended consequences with the way the strokes were being logged already. Fast strokes composed of few points that went off the edge of the drawable canvas would disappear many pixels before the edge since their last point would disappear. The fix may not be that difficult, but there are other instances that would have to be accounted for in that format. To get past this, I would have to add a lot of unneeded complexity, for something that isn't better imo.
fixes #532
> android: extraneous drawing stroke points are rounded to their nearest max or min

- clients/android/app/src/main/java/app/lockbook/ui/HandwritingEditorView.kt
Originally, whenever `restoreFromModel` was called, it would create an unfaithful recreation of the drawing due to its improper use of pressure. It was called when a drawing was initially being loaded up and when a stroke was being erased. Now it correctly uses each pressure value.
fix #542
> android: fix the drawingview's unfaithful restore from model function 

- clients/android/app/src/main/java/app/lockbook/model/HandwritingEditorViewModel.kt
- clients/android/app/src/main/java/app/lockbook/screen/HandwritingEditorActivity.kt
- clients/android/app/src/main/java/app/lockbook/ui/HandwritingEditorView.kt
Drawings were being reset when a user exited the drawing screen of the app, without fully closing it, and then reentered it through android's task manager (not sure about the official name).
This turned out to be a bug involving a callback that would repeatedly bring back the state of the drawing to the backup drawing's state. This backup drawing was stored in the viewmodel (which survives configuration changes the activity cannot), and was used during a configuration change like a screen rotation. The callback would be fired on the first launch of an activity, and also when an activity was restarted from a pause (like the senario above). It called a function that would check to see if the backup was occupied and if it was, it would override the main drawing.
fixes #545
> android: fixed drawing deletion bug involved with paused activities

- containers/Dockerfile.android
- containers/Dockerfile.kotlin_interface_tests
- containers/docker-compose-integration-tests.yml
In this PR, both the android and kotlin interface tests dockerfiles now start with a gradle image.
This is good since... 
- Gradle will always be cached
- There is no need to install java since it comes with the gradle image
fixes #485
> infra: android and kotlin interface tests dockerfiles start with a gradle image

- clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt
- clients/android/app/src/main/java/app/lockbook/model/FileModel.kt
- clients/android/app/src/main/java/app/lockbook/model/ListFilesViewModel.kt
- clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt
- clients/android/app/src/main/java/app/lockbook/util/Converters.kt
- clients/android/app/src/main/java/app/lockbook/util/Structures.kt
- clients/android/app/src/test/java/app/lockbook/CalculateWorkTest.kt
- clients/android/app/src/test/java/app/lockbook/ExecuteWorkTest.kt
- clients/android/app/src/test/java/app/lockbook/SyncAllTest.kt
- clients/android/core/src/main/java/app/lockbook/core/core.kt
- core/src/java_interface.rs
In this PR I fixed the a long time error involving the snackbar popping in and out whilst trying to sync. It was discovered this was due to the bad sync algorithm that was out of order, and had the wrong statements altogether. I also did some renaming of CoreModel's sync functions to be more in line with core's.
fix #423
> android: resolved sync errors involving the snackbar popping in and out

- core/src/lib.rs
In this PR I fixed `get_last_synced_human_string`. The function gave a wrong duration due to incorrectly parsing the time it was given.
fix #573
> core: fixed get last synced human string outputting the wrong duration

- clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt
- clients/android/app/src/main/res/layout/fragment_list_files.xml
- clients/android/app/src/main/res/values/styles.xml
- clients/android/lint.xml
In this PR, FABs will appear horizontally on small screens that are landscape. I chose to do this since there will be multiple visual glitches if the screen is too small to fit the FABs. So to circumvent this, I wanted the FABs to appear along the larger side, in portrait it will stay the same (appear vertically), in landscape it will be horizontally.
I also shrunk the distance between the FABs a bit to help out.
Screenshot of a small device in landscape using this PR:
<details>
</details>
fixes #548
> android: new FABs appear horizontally on small screens

- clients/android/lint.xml
- containers/Dockerfile.kotlin_interface_tests
- containers/docker-compose-integration-tests.yml
In this PR I shortened the prep and test time for kotlin interface tests by only compiling the tests in the prep phase and only running those compiled tests in the test phase.
Before:
After:
fixes #553
**There may be a way to shorten the time more, I explain what I mean [here](https://github.com/lockbook/lockbook/issues/553#issuecomment-776302414).**
> infra: shorten kotlin interface tests prep and run time

- clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt
- clients/android/app/src/main/java/app/lockbook/model/LinearRecyclerViewAdapter.kt
- clients/android/app/src/main/java/app/lockbook/model/ListFilesViewModel.kt
- clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt
- clients/android/app/src/main/res/values/strings.xml
- clients/android/core/src/main/java/app/lockbook/core/core.kt
- clients/android/lint.xml
- core/src/java_interface.rs
This PR, I fix a previous error where I used get last synced human string, and instead utilize the metadata version for the date.
fixes #592
> android: use metadata version in file descriptions to show when the file was updated synced

- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/util.rs
In this PR, I utilize `get_usage_human_string`, and get rid of the duplicate logic used to do the same thing.
KDE Screenshot
<details>
</details>
fixes #609
> linux: use get_usage_human_string

- clients/apple/Shared/Components/FileCell.swift
- clients/apple/Shared/Components/NestedList.swift
- clients/apple/Shared/Stateful Logic/GlobalState.swift
- clients/apple/Shared/Views/BookView.swift
- clients/apple/Shared/Views/EditorView.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/FileMetadata.swift
- clients/apple/iOS/FileListView.swift
- clients/apple/lockbook.xcodeproj/project.pbxproj
- clients/apple/macOS/OutlineRow.swift
- clients/apple/macOS/OutlineView.swift
- Modifies iOS `SyntheticCell` to be more generic (removes weird double `TextField` for just a pre-populated suffix)
- iOS move dialog
- macOS drag & drop move
- macOS `SyntheticCell` rename
https://user-images.githubusercontent.com/2370497/111727744-e15aad00-8841-11eb-8e5b-bf9e0a0b80de.mov
https://user-images.githubusercontent.com/2370497/111727491-5b3e6680-8841-11eb-90a4-cc738129e435.mov
fixes #509 
fixes #511 
fixes #510
> Apple Move/Rename

- clients/cli/src/copy.rs
- clients/cli/src/error.rs
- clients/cli/src/export_drawing.rs
- clients/cli/src/import_private_key.rs
- clients/cli/src/main.rs
- clients/cli/src/remove.rs
- server/Cargo.lock
```
lockbook 0.2.20
A secure and intuitive notebook.
USAGE:
lockbook <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
SUBCOMMANDS:
backup                Backup your Lockbook files and structure to the current directory
copy                  Copy a file from your file system into your Lockbook
edit                  Open a document for editing
errors                Print out what each error code means
export-drawing        Export a drawing as an image
export-private-key    Export your private key, if piped, account string, otherwise qr code
get-usage             How much space does your Lockbook occupy on the server
help                  Prints this message or the help of the given subcommand(s)
import-private-key    Import an account …
```
> cli: touchup errors and docs

- clients/apple/Notepad/Sources/NotepadSwift/Markdown/MarkdownEngine.swift
- clients/apple/Shared/Components/NotepadView.swift
- clients/apple/Shared/Config/Colors.swift
- clients/apple/Shared/Config/LockbookMarkdownConfig.swift
- clients/apple/Shared/Stateful Logic/GlobalState.swift
- clients/apple/Shared/Views/EditorView.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/FfiError.swift
- clients/apple/SwiftLockbookCore/Tests/SwiftLockbookCoreTests/Contracts/ErrorEnumTests.swift
- clients/apple/iOS/FileListView.swift
- clients/apple/lockbook.xcodeproj/project.pbxproj
- clients/apple/lockbook.xcworkspace/xcshareddata/swiftpm/Package.resolved
- clients/apple/macOS/FileListView.swift
- clients/apple/macOS/ImageLoader.swift
- clients/windows/core/CoreModel.cs
- clients/windows/test/CoreServiceTest.cs
- core/src/c_interface.rs
- core/src/lib.rs
fixes #649
You can view drawings as image in macOS
https://user-images.githubusercontent.com/2370497/112770078-d696d980-8ff2-11eb-86dd-a4ebfe578c05.mov
fixes #648 
Smart quotes and other **wonk-AF** characters will not busk the render with their dirty bounds!
fixes #645
> apple: Fixing file deletion, view drawings as image, fixing markdown bounds

- clients/android/app/src/main/java/app/lockbook/screen/SettingsFragment.kt
- clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt
In this PR, a stroke's width is now used in determining whether something can be erasing. Before, there would be a fixed distance around a stroke point, and only when you entered that would you erase it. This fixed distance was hardwired at `20`, but now this distance around the point is based on stroke girth. This gives a predictable and normal erasing feeling.
fixes #658
> android: erasing will take into account the stroke's width

- clients/android/app/src/main/res/values/styles.xml
In this PR, the dark themes for the settings dialogs were corrected. Originally, in darkmode these dialogs would have grey backgrounds. This is because they could not be themed the same way as the other dialogs, like move file and rename, so they defaulted to global theme which did not specifically account for these dialogs.
<details>
</details>
<details>
</details>
fixes #656
> android: correct darkmode theme for setting dialogs

- clients/android/app/src/main/java/app/lockbook/model/AlertModel.kt
- clients/android/app/src/main/java/app/lockbook/model/DrawingViewModel.kt
- clients/android/app/src/main/java/app/lockbook/model/FileModel.kt
- clients/android/app/src/main/java/app/lockbook/model/ListFilesViewModel.kt
- clients/android/app/src/main/java/app/lockbook/model/MoveFileViewModel.kt
- clients/android/app/src/main/java/app/lockbook/model/SyncModel.kt
- clients/android/app/src/main/java/app/lockbook/model/TextEditorViewModel.kt
- clients/android/app/src/main/java/app/lockbook/screen/ListFilesActivity.kt
- clients/android/app/src/main/java/app/lockbook/screen/ListFilesFragment.kt
- clients/android/app/src/main/res/values/strings.xml
In this PR, I resolved a long standing error involving sync messages. Whenever a user would try to sync using the swipe to refresh functionality, the sync info message did not always appear. This was due android itself lacking a queue functionality. So when snackbars appeared in succession, like they did with syncing, then it did guarantee that the message would always be shown. Luckily, a library we already used called snackprogressbar (which can be forked in need be), implemented this functionality already. So I just utilized it and fixed the bug.
fixes: #567
> android: sync snackbar messages don't always appear

- clients/android/app/src/main/AndroidManifest.xml
- clients/android/app/src/main/java/app/lockbook/screen/DrawingActivity.kt
- clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt
In this PR, I fix a long time issue involving the drawing view. If you keep rotating and getting in and out of the app while in the drawing screen, then you may crash due to this bug. This was due to the improper handling of the drawing thread whenever it was being ended. I ended up having to get rid of all the old thread logic and replaced it with something that is more concise and cleaner the long run. Its important to note, **I do not entirely know what caused this error**, this was only present on my tablet, my mobile device (Google Pixel 3) had nothing of the sort. What I did know is that it happened while the thread was closing and I must have improperly handled it, possibly in a way that only offended the tablet (the log messages were different too), that of which was solved after …
> android: fixed bad allocation error while drawing

- clients/linux/src/account.rs
- clients/linux/src/settings.rs
+ By default the file tree opens without showing debugging related columns (id & type)
+ Use `SourceView`'s syntax highlighting based on file name:
> linux: end user default settings and enable syntax highlighting

- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/auto_save.rs
- clients/linux/src/main.rs
- clients/linux/src/messages.rs
- clients/linux/src/settings.rs
+ [x] Change window title based on open file
+ [x] Be able to detect when a file is dirty
+ [x] Add a `+` or `*` to the window title if the current file is dirty
+ [x] Warn prior to dirty file changes (fixes #381)
+ [x] Create setting to auto save dirty files after a configurable delay, default to auto save after 2 seconds of being idle
+ [x] Auto save dirty files (fixes #373)
> linux: editor lifecycle improvements

- clients/linux/src/app.rs
* use `LbApp::refresh_sync_status` method where possible, or...
* send the `RefreshSyncStatus` message from within the closures
> linux: tidy code regarding the updating of the sync status

- clients/linux/src/settings.rs
> linux: settings use defaults on missing fields

- clients/linux/src/main.rs
If an error occurred while initializing `Settings` or `LbCore`, we call `launch_err` to post a dialog for this error. The problem is, you can't post a dialog if gtk+ is not initialized, and we initialize gtk+ on the very last line of the main function with `gtk_app.run(&[])`. So if an error happens, it will crash when attempting to run the dialog. So `gtk::init().unwrap()` has been added so we can successfully run dialogs before the `GtkApp` itself is run.
fixes #703
> linux: gtk is initialized before settings and lbcore

- clients/cli/src/calculate_usage.rs
- core/libs/models/src/api.rs
- core/src/lib.rs
- core/src/service/usage_service.rs
+ Make bytes -> human string fn more generally available
+ Calculate the size of all uncompressed docs
Strangely the performance of this depends heavily on whether `--release` is on. 
Will require a server deploy before this is functional. Server deploy blocked by recent changes to server and the need for a prod wipe.
> core: measure uncompressed usage

- clients/cli/src/edit.rs
- clients/cli/src/new.rs
- clients/cli/src/new_account.rs
- clients/cli/src/remove.rs
- clients/cli/src/utils.rs
Adds windows support for the CLI. Terminal editors are not supported because of difficulty directing controlling terminal's standard in to the editor (Windows does not have an equivalent for `/dev/tty`).
Sample output:
```
C:\Users\tvand\code\lockbook\clients\cli>lockbook new test123/testy-test8
LOCKBOOK_EDITOR not set, assuming vim
Terminal editors are not supported on windows! Set LOCKBOOK_EDITOR to a visual editor.
Your editor indicated a problem, aborting and cleaning up
```
Closes #409
Closes #410
> windows cli: usability

- clients/linux/src/app.rs
- clients/linux/src/filetree.rs
- clients/linux/src/messages.rs
In this PR, if you sync a move it will show on the file tree, all whilst keeping the folders that were already open, open.
fixes #689
> linux: syncing a move will refresh the file tree

- clients/linux/src/filetree.rs
This bug originated from [this](https://github.com/lockbook/lockbook/pull/737). Whenever the file tree was populated, using the `fill` method from the `FileTree` struct, it triggered the `on_selection_change` closure. This closure is meant to modify the availability of the pop up items (the options that appear when you right click a file) since a new file was selected. But it assumed (using an `.unwrap()`) that there was at least one file in the tree. The problem was, when `fill` is used, the filetree was cleared and added back all its children. Usually this was just called once when the app was opened, which was before the `on_selection_change` closure was added to the tree. Now it was being used while the closure was already there. The fix was to just get rid of the unwrap and allow for …
> linux: fixed sync crashes and selection is preserved

- clients/android/app/src/main/java/app/lockbook/screen/DrawingActivity.kt
- clients/android/app/src/main/java/app/lockbook/ui/DrawingView.kt
- clients/android/app/src/main/java/app/lockbook/util/Drawing.kt
In this PR, white and black will switch values in the `drawingview` depending on whether the device is in darkmode or lightmode. This means that if you are in lightmode and drawing with the black `ColorAlias`, it will become the white `ColorAlias` in darkmode. Effectively allowing strokes to visible regardless of the theme.
Recorded Example:
<details>
https://user-images.githubusercontent.com/20663038/119876015-696dca80-bef5-11eb-9c6a-46ca5fb2f4a4.mp4
</details>
fixes #668
> android: drawingview's white and black color values switch depending on device theme

- server/server/src/account_service.rs
- server/server/src/config.rs
- server/server/src/file_content_client.rs
- server/server/src/file_index_repo.rs
- server/server/src/file_service.rs
- server/server/src/lib.rs
- server/server/src/loggers.rs
- server/server/src/main.rs
I came here to fix the logging. What I found was that the entire server state was being cloned multiple times per request, including the postgres connection pool. I don't really know how that worked at all.
* let the postgres connection pool handle reconnecting
* makes server state immutable and unclonable
* fixes pagerduty logging
* bubbles up internal errors to single point
* only logs request if response is internal error
Fixes #757
> server: less nonsense, better logging

- clients/android/app/src/main/java/app/lockbook/model/CoreModel.kt
- clients/android/app/src/main/java/app/lockbook/ui/UsageBarPreference.kt
- clients/android/app/src/main/java/app/lockbook/util/Converters.kt
- clients/android/app/src/main/java/app/lockbook/util/CoreData.kt
- clients/android/app/src/test/java/app/lockbook/GetUncompressedUsageTest.kt
- clients/android/core/src/main/java/app/lockbook/core/core.kt
- clients/apple/Shared/Views/AccountView.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/FileUsage.swift
- clients/apple/SwiftLockbookCore/Tests/SwiftLockbookCoreTests/Scenarios/UsageTests.swift
- clients/cli/src/calculate_usage.rs
- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/error.rs
- clients/linux/src/messages.rs
- clients/windows/core/CoreModel.cs
- clients/windows/core/CoreService.cs
- clients/windows/lockbook/FileExplorer.xaml.cs
- clients/windows/lockbook/Settings.xaml.cs
- clients/windows/test/CoreServiceTest.cs
- core/src/c_interface.rs
- core/src/java_interface.rs
- core/src/lib.rs
- core/src/service/usage_service.rs
- core/tests/get_usage_tests.rs
- utils/dev/create_core_for_windows.bat
Originally, when you suspended your laptop you may have been greeted with a "Could not reach server" dialog. To counter this, we now have a bottom bar where messages will be shown regarding sync. Depending on the result of the sync, as well as the host of other things, a message will be displayed. All in all, this PR is made to be in accordance with [this](https://github.com/lockbook/lockbook/blob/master/docs/design-ux/navigation.md).
fixes #760
> linux: could not reach server dialog does not appear when computer is suspended

- clients/apple/Shared/Config/Colors.swift
Colors were lost in two ways for two different reasons.
The ways they were lost:
+ switching between light and dark mode
+ using things like lasso select + duplicate
The reasons they were lost:
+ apple uses _slightly_ different colors depending on some contexts (dark mode, accessibility settings). They only differ slightly, and for now I just picked one set and hard coded their values: https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/
+ when you use things like lasso select + duplicate, there was a slight difference in rounding. So I implemented a custom `==`  which will compare rgb with 2 decimal places of precision (`0.00-0.99`).
fixes #746
> apple: fix loss of colors

- Cargo.lock
- containers/Dockerfile.admin_cli
- containers/Dockerfile.server
- core/libs/models/src/api.rs
- server/server/Cargo.toml
- server/server/build.rs
- server/server/src/main.rs
* Adding a new API endpoint that returns package/build # and the corresponding git commit hash. These values are determined at build time.
* Pulling in [`shadow-rs`](https://github.com/baoyachi/shadow-rs) as a dependency for server to compute git hash.
* I'm not sure what the testing story is here, so lmk how/if I can test this out without integrating into clients.
closes #820
> server: add API endpoint for reporting server build info

- clients/apple/lockbook.xcodeproj/project.pbxproj
- containers/Dockerfile.swift_interface_tests
- core/Makefile
- docs/guides/building.md
+ modifies our xcode mac target build description to say we support any macOS
+ modifies our makefile to build for both intel & apple silicon and then uses lipo (not cargo lipo) to create a universal binary
+ updates our docs to include both targets for building for macos, either platform can create this universal application.
+ we can and probably should do this for our macOS binary as well
closes #847
> apple: apple silicon build infra

- clients/linux/src/filetree.rs
> linux: an error won't be thrown when file is moved into the same directory

- clients/cli/src/copy.rs
- clients/cli/src/error.rs
- clients/cli/src/main.rs
- clients/linux/src/backend.rs
- core/libs/models/src/file_metadata.rs
- core/src/lib.rs
- core/src/service/import_export_service.rs
- core/tests/import_export_file_tests.rs
Fix a bug where files that didn't exist weren't created, and documents names were treated as folders.
Additionally added support for posix shell `*`. This enables the most straightforward recovery from a backup:
```bash 
lockbook copy parth/* parth
```
bash will expand this to include all the top level folders in your root directory, and they will be copied in one folder at a time.
the universal restore command (from a backup dir): `lockbook copy $(lockbook whoami)/* $(lockbook whoami)`
I also simplified the contract for copy, the terminal argument (the destination) must always be a folder. We also no longer check before overwriting files in core (neither does the actual `cp` command).
closes #862
> cli: fix bug, and support globs for inputs 

- server/instances/haproxy/update-ssl-cert.sh
- utils/infra/setup.load-balancer.haproxy.sh
When certbot renews it's cert this will create the combined SSL pem that haproxy points to automatically.
Server will need to be restarted manually afterwards
closes #877
> infra: certbot SSL cert update script hook

- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/editmode.rs
- clients/linux/src/filetree.rs
- clients/linux/src/lbsearch.rs
- clients/linux/src/main.rs
- clients/linux/src/menubar.rs
- clients/linux/src/messages.rs
- clients/linux/src/util.rs
This PR removes the top search bar on the linux client in favor of a search dialog shown on `Ctrl-L` or `Ctrl-Space`. Additionally, the search functionality is placed into its own file. (There are a few minor cleanups sprinkled in as well.)
The spinner in the header bar was used for indicating to the user that a file was in the process of being saved. If we still want to notify the user when this happens, we need to come up with a different way. Otherwise, that last bit of code can go as well.
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
</details>
> linux: redesign search ui/ux

- clients/linux/src/backend.rs
- clients/linux/src/filetree.rs
Originally in the linux client, the filetree was populated using a chain of `get_children` calls, starting from the root. This was an inefficient process as it would require `core` to keep retrieving all the files using io operations, and matching to get the desired parent. 
In this PR, I call the exposed `lib.rs` function, `list_metadatas`, to get all the metadata. I match on these metadata to construct the file tree myself, so I don't make any more `core` calls.
On my local machine, with my lockbook containing `307` files and `14.54 mb` of compressed usage, these were the time differences between the new algorithm and the old one (the time it takes to load the file tree)
Debug Build:
`58524ms` old algorithm
`6ms` new algorithm
Release Build:
`4707ms` old algorithm
`1ms` new algorithm
> linux: populating file tree is quicker

- core/src/pure_functions/files.rs
- core/src/service/file_service.rs
- core/src/service/integrity_service.rs
also fix validate so it doesn't try to read deleted documents (which can be present locally when a sync doesn't finish gracefully)
> core: ignore path conflicts where one file is deleted

- clients/linux/src/app.rs
- clients/linux/src/filetree.rs
This PR fixes #885 so that renaming a file no longer breaks its icon, as well as makes it so that the window title is only changed to the renamed file's name if it is the file that is open.
> linux: fix / cleanup rename file

- clients/apple/Shared/Stateful Logic/OnboardingState.swift
- clients/apple/Shared/Views/AppView.swift
- clients/apple/Shared/Views/OnboardingView.swift
Apple detects that a user has pressed enter on a field by paying attention to `onCommit`. There's a strange behavior: if a button has a `.disabled` property (for example when the long computation begins), the commit is called twice. In the case of an import account this led to sync being called twice, which causes one of the operations to fail for one reason or another.
Perhaps related to #869
> apple: prevent double syncs on sign ups

- clients/apple/SwiftLockbookCore/Tests/SwiftLockbookCoreTests/SwiftLockbookCoreTests.swift
- core/src/service/account_service.rs
- core/tests/account_service_tests.rs
- core/tests/create_account_tests.rs
- server/server/src/file_index_repo.rs
Adds some logic in core which will lowercase usernames during signup, add some logic in server which will lowercase usernames in server before db constraints are checked.
The logic in core prevents you from entering a weird state where your (encrypted and therefore not verifiable by server) root name doesn't end up with a different case than you username.
closes https://github.com/lockbook/lockbook/issues/873
> server: make sure usernames are case sensitive

- core/src/pure_functions/files.rs
- core/tests/create_account_tests.rs
- core/tests/sync_service_tests.rs
path conflict code has a precondition that there must be no cycles in the file tree, otherwise we get caught in an inf loop.
also address a clippy warning
> core: check for cycles before checking for path conflicts

- clients/linux/src/backend.rs
- core/libs/models/src/api.rs
- core/libs/models/src/crypto.rs
- core/libs/models/src/file_metadata.rs
- core/libs/models/src/lib.rs
- core/libs/models/src/utils.rs
- core/src/lib.rs
- core/src/pure_functions/files.rs
- core/src/repo/metadata_repo.rs
- core/src/service/file_encryption_service.rs
- core/src/service/file_service.rs
- core/src/service/integrity_service.rs
- core/src/service/sync_service.rs
- core/src/service/test_utils.rs
- server/server/src/file_index_repo.rs
In this PR we rename `FileMetadata` to `EncryptedFileMetadata` and introduce a new `FileMetadata` trait which is implemented by `EncryptedFileMetadata` and `DecryptedFileMetadata`. Using the trait, we reduce code duplication in `files.rs`, which sets us up for re-using the tree validation logic in server.
> core: factor tree validation

- clients/linux/src/app.rs
- clients/linux/src/lbsearch.rs
- clients/linux/src/util.rs
Move remaining search related code out of `app.rs` and make a few minor refactors as a result.
> linux: organize (and refactor) search related code

- clients/linux/src/account.rs
- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/filetree.rs
- clients/linux/src/main.rs
- clients/linux/src/menubar.rs
- clients/linux/src/util.rs
This removes the `make_glib_chan` and `spawn` macros from `app.rs`, the `menu_set` one in `menubar.rs`, and the `closure` macro everywhere in favor of `glib::clone`.
> linux: remove certain macros

- server/admin/src/main.rs
- server/server/src/account_service.rs
- server/server/src/content/content_cache.rs
- server/server/src/content/document_service.rs
- server/server/src/content/file_content_client.rs
- server/server/src/content/mod.rs
- server/server/src/file_content_client.rs
- server/server/src/file_service.rs
- server/server/src/keys.rs
- server/server/src/lib.rs
- server/server/src/main.rs
Uses redis as an lru cache for documents.
creates document_service as the interface for server, which negotiates files that could be in redis or in s3.
closes: #954
> server: do s3 things async where possible

- Cargo.lock
- clients/cli/Cargo.toml
- clients/linux/Cargo.toml
- clients/linux/src/account.rs
- core/Cargo.toml
- core/libs/models/src/file_metadata.rs
- core/libs/models/src/tree.rs
- core/src/pure_functions/files.rs
- core/src/service/account_service.rs
- core/src/service/db_state_service.rs
- core/src/service/file_encryption_service.rs
- core/src/service/file_service.rs
- core/src/service/integrity_service.rs
- core/src/service/path_service.rs
- core/src/service/sync_service.rs
- core/src/service/test_utils.rs
- core/src/service/usage_service.rs
- server/server/Cargo.toml
- server/server/src/file_service.rs
- server/server/src/lib.rs
use T Y P E S A F E T Y  to make owners not be a string, which could cause different people to draw different conclusions about it's intended purpose, which is what happened as core saved a username and server saved a public key. It is now exclusively a public key, which is gonna make ownership checks on the server a breeze.
This is every type of breaking change that could happen.
fixes #949 
The line count bloat is all formatting, `account.public_key()` is longer than `account.username`, so a handful of functions are now formatted in the "tall" mode, rather than the horizontal "compact" mode.
> core: fix owners

- Cargo.lock
- server/server/Cargo.toml
The latest pagerduty includes the dependency feature flagging we need to eliminate native-tls use: https://github.com/polyverse/pagerduty-rs/pull/5
> server: upgrade pagerduty dependency

- containers/local.env
- core/src/repo/local_storage.rs
- core/tests/exhaustive_sync/experiment.rs
- core/tests/exhaustive_sync/trial.rs
- core/tests/exhaustive_sync_check.rs
- server/server/src/router_service.rs
+ fuzzer now deletes accounts once trials are concluded
+ small performance optimization, we now pause execution for much less time while calculating metrics every 10s. We take a snapshot of the experiments and release the mutex immediately.
+ adds a handful of debugging info to core
> fuzzer: garbage collection

- server/server/run-server
- utils/dev/run-server.sh
This is a script to run the server setup. It does the following:
* Starts redis, directing any output to `./redis-server.log`.
* Starts minio, directing any output to `./minio-server.log`.
* Configures minio once it is running (note: the `-p` flag is added to the make bucket command so the script won't fail if the bucket already exists).
* Compiles and runs the lockbook server (blocking here).
The script takes one optional argument: the data directory for the minio server. If none is provided, `/tmp/lbdev` is used.
> infra: add a simple script to run the lockbook server setup

- clients/cli/src/copy.rs
- clients/linux/src/app.rs
- clients/linux/src/backend.rs
- clients/linux/src/util.rs
- core/src/lib.rs
- core/src/service/import_export_service.rs
- core/tests/import_export_file_tests.rs
This PR improves the file importing functionality (touches `core` as well as the `cli` and `linux` clients).
I've found the current implementation to be limited in the following ways:
1. I want to know when the work of importing a single item has started _and finished_. Right now, there is only the option to be alerted when an item has started.
2. When the process of importing an item is done, a graphical client with a tree might want to add an entry at that point. In the case of `linux` for example, this would require the `FileMetadata` of the newly imported file.
To start, `import_file` in lib.rs is now `import_files` and takes _at least one_ `PathBuf` to import. (Same change made for the `import_file` function in `import_export_service`.)
Within …
> core: refactor importing files

- utils/dev/run-server.sh
* create the provided (or default) directory and `cd` into it when starting `redis` and `minio`
* use `command` to print out which programs are being used, or alternatively, to fail if one of them isn't found
* use `lsof` rather than `nc` for a slightly more robust way of listening for `minio`
> infra: improve dev server script

- clients/cli/src/utils.rs
The hard coded pat for windows does not work. The standard library exposes a function for temporary directory path location. 
Closes #410
> cli: better temporary directory detection

- Cargo.lock
- clients/linux/Cargo.toml
- clients/linux/lb-api/src/lib.rs
- clients/linux/src/app/imp_activate.rs
- clients/linux/src/app/imp_search.rs
- clients/linux/src/app/mod.rs
- clients/linux/src/ui/header_bar.rs
- clients/linux/src/ui/mod.rs
- clients/linux/src/ui/search_row.rs
- clients/linux/src/ui/titlebar.rs
- core/Cargo.toml
- core/src/lib.rs
- core/src/service/mod.rs
- core/src/service/search_service.rs
- core/tests/search_service_tests.rs
This PR creates a `search_service` in core and then implements the use of it within the linux client.
The `search_service` has a single function that fuzzy searches all file paths and returns the (sorted) ID, path, and score of any matches.
The search interface in linux is created from scratch (so to speak) using an overlay and a list box instead of using a gtk entry completion setup (as was the case in the old client). `Ctrl-space` and `Ctrl-L` are used to display a search input field in place of the app's title in the window's titlebar.
Closes #828.
> core+linux: add search in core and use it in linux client

- clients/linux/lb-api/src/lib.rs
- clients/linux/src/app/imp_activate.rs
- clients/linux/src/app/imp_file_copy_paste.rs
- clients/linux/src/app/mod.rs
- clients/linux/src/ui/account_screen.rs
- clients/linux/src/ui/filetree.rs
- clients/linux/src/ui/menu_item.rs
- clients/linux/src/ui/mod.rs
- clients/linux/style.css
This PR adds two options to the file tree's right click menu: `Cut` and `Paste`. Only a single file (excluding root) can currently be cut and pasted (aka: moved). Pasting will clear the file clipboard, and it will only be enabled in the menu if the file clipboard has content.
The size of file menu item buttons are decreased as well (specifically by reducing padding), which brings them more inline with other applications.
> linux: implement move via right click cut & paste

- clients/linux/src/app/imp_activate.rs
- clients/linux/src/app/imp_delete_files.rs
- clients/linux/src/app/imp_errors.rs
- clients/linux/src/app/imp_export_files.rs
- clients/linux/src/app/imp_file_copy_paste.rs
- clients/linux/src/app/imp_import_files.rs
- clients/linux/src/app/imp_rename_file.rs
- clients/linux/src/app/imp_save_file.rs
- clients/linux/src/bg.rs
- clients/linux/src/ui/account_screen.rs
- clients/linux/src/ui/filetree.rs
- clients/linux/src/ui/titlebar.rs
code:
* adopt a clearer pattern in more places of scoping cloned closure variables
* stop borrowing `Uuid`s
* use the account op channel for more things instead of gtk actions and their string names
ui:
* error dialog is nicer (proper title and icon, label margin balanced)
* search box is cleared on `Escape` instead of holding onto the input and results
> linux: miscellaneous refactors and cleanups

- clients/linux/src/app/imp_account_create.rs
- clients/linux/src/app/imp_account_import.rs
- clients/linux/src/app/imp_activate.rs
- clients/linux/src/ui/account_screen.rs
- clients/linux/src/ui/mod.rs
- clients/linux/src/ui/onboard_screen.rs
- clients/linux/style.css
The overall linux onboarding ux is a bit lacking from after the upgrade. This PR does the following:
* makes the initial screen nicer by adding the logo and a title.
* prompts the user to backup their private key immediately after they create an account.
* some miscellaneous onboard code cleanups.
Closes #1045.
> linux: improve onboard uiux

- clients/android/app/build.gradle
- clients/android/build.gradle
Added the billing permission to android. This is needed to enable billing features on the google play console. 
I previously had billing permissions because I uploaded an `apk` (from my branch) with the permission, but with the last new official release, the new permissions were revoked.
> android: added billing permission

- clients/linux/src/app/imp_activate.rs
- clients/linux/src/ui/account_screen.rs
Also, adjust window size and file tree sidebar width.
> linux: don't display full titlebar on onboard screen

- server/server/src/billing/billing_service.rs
Got rid of an internal error that should have been a regular (`NotAStripeCustomer`) error.
> Added error to get-credit-card endpoint

- clients/linux/src/app/imp_activate.rs
- clients/linux/src/ui/onboard_screen.rs
* The text field entry for a user's account string is now a password entry with a "peek icon" (Closes #1081).
* The labels for captions and errors on the onboard screen now wrap so that they don't trigger massive unexpected resizing of parent components and even the window (Closes #1072).
* A few miscellaneous onboard code cleanups.
> linux: a few onboard screen fixes

- clients/linux/src/app/imp_activate.rs
- clients/linux/src/app/imp_open_file.rs
- clients/linux/src/ui/account_screen.rs
- clients/linux/src/ui/filetree.rs
- clients/linux/src/ui/tab.rs
- clients/linux/src/ui/text_editor.rs
Along with some clean up, this PR improves the UI/UX around opening a document in the linux client. Instead of the UI locking while reading the document content, it opens the tab with a loading icon (a spinner) as the content and reads the content in a separate thread.
Closes #1082.
> linux: read document content in separate thread when opening file

- clients/linux/src/app/imp_activate.rs
This fixes a UI bug where a user was able to use all action shortcuts on the onboard screen. Since all those actions are for account related things, they're now setup only when the account screen is initialized.
Closes #1120.
> linux: only establish action shortcuts on the account screen

- clients/linux/lb-api/src/lib.rs
- clients/linux/src/app/imp_activate.rs
Notably, include `HOMEPATH` as a last resort so that the gtk app can behave normally on windows.
> linux: refactor how the data directory is determined

- clients/linux/src/app/imp_new_file.rs
- clients/linux/src/app/imp_settings_dialog.rs
- clients/linux/src/settings.rs
On by default, this allows the user to choose whether or not newly created documents are opened automatically.
Closes #1133.
> linux: add a setting to open newly created documents

- Cargo.lock
- core/Cargo.toml
- core/libs/crypto/Cargo.toml
- core/libs/models/Cargo.toml
- server/server/Cargo.toml
They released `0.7.0` less than a month ago it looks like. Built for me locally, so we should probably go back to using theirs for security reasons.
> core,server: upgrade libsecp256k1 dependency

- clients/linux/src/app/imp_new_file.rs
- clients/linux/src/ui/toggle_group.rs
Reorder the file types in the new file dialog to: Markdown, Plain Text, Folder. Also, add a `.txt` extension for plain text files.
> linux: reorder file types in new file dialog, add txt extension

- clients/linux/src/ui/usage_settings.rs
I learned how to make a custom tooltip with gtk, and this is much better (imo) than using a popover with a menu button.
Before:
After:
> linux: use a custom tooltip for usage compression stats

- core/src/model/errors.rs
Personally, I'm working in a lot of scenarios where errors are converted to `String`s. So if I'm calling a function that returns `UnexpectedError`, I can just `?` now instead of explicitly calling `.map_err(|err| err.0)?`.
> core: impl From<UnexpectedError> for String

- Cargo.lock
- clients/linux/lb-api/Cargo.toml
- clients/linux/lb-api/src/lib.rs
- clients/linux/lb-api/src/search.rs
- clients/linux/src/app/imp_search.rs
- clients/linux/src/ui/mod.rs
- clients/linux/src/ui/search_field.rs
- clients/linux/src/ui/titlebar.rs
- core/src/service/path_service.rs
Re-implement how files paths are searched. Instead of using core search service on each keystroke, the filtered paths are gathered once at the beginning.
Also, only search docs via titlebar, so closes #1130.
> linux: re-implement titlebar search

- clients/linux/lb-api/src/lib.rs
- core/libs/models/src/tree.rs
- core/libs/test_utils/src/lib.rs
- core/src/lib.rs
- core/src/pure_functions/files.rs
- core/src/service/account_service.rs
- core/src/service/billing_service.rs
- core/src/service/drawing_service.rs
- core/src/service/file_encryption_service.rs
- core/src/service/file_service.rs
- core/src/service/import_export_service.rs
- core/src/service/integrity_service.rs
- core/src/service/path_service.rs
- core/src/service/search_service.rs
- core/src/service/sync_service.rs
- core/src/service/usage_service.rs
- core/tests/exhaustive_sync/trial.rs
- core/tests/file_encryption_tests.rs
- core/tests/file_service_tests.rs
- core/tests/integrity_tests.rs
- core/tests/new_account_tests.rs
- core/tests/sync_fuzzer.rs
- core/tests/sync_service_tests.rs
- server/server/src/account_service.rs
- server/server/src/file_service.rs
- utils/dev/run-server.sh
With @vvmirkovic's `HashMap` changes, we saw agorithmic speedups in some instances, but regressions in other areas. Those regressions are largely caused by `O(n)` operations being more expensive with `HashMap`s, probably due to the lack of cache locality. This PR addresses all regressions, now core is faster in all situations compared to vecs (10 metas or 2000 metas).
In this PR I profile core and:
+ Stop scanning for root when we know root's id already ([a12dad2](https://github.com/lockbook/lockbook/pull/1145/commits/a12dad26731dd7bc67dc8357cf2e18165abd7a95))
+ Deal in terms of ids instead of `cloning` file metadatas, rework some algorithms to be `O(n)` instead of `O(n2)` ([1e49ed8](https://github.com/lockbook/lockbook/pull/1145/commits/1e49ed8f4323987151145469d14a3ee6b01137ba))
+ Rework …
> core: pre-sharing, pre-search, core data structure finalization

- clients/android/app/src/main/res/layout/fragment_text_editor.xml
The text editor now has a max width. This max width will get bigger for larger text, and smaller for smaller text. Regular mobile devices will not see any difference.
**Screenshots**
<details>
Regular Text Size
Large Text Size
Small Text Size
</details>
closes #1168
> android: max width texteditor

- Cargo.lock
- clients/cli/Cargo.toml
- clients/cli/src/backup.rs
- clients/cli/src/calculate_usage.rs
- clients/cli/src/copy.rs
- clients/cli/src/edit.rs
- clients/cli/src/error.rs
- clients/cli/src/export_drawing.rs
- clients/cli/src/export_private_key.rs
- clients/cli/src/import_private_key.rs
- clients/cli/src/list.rs
- clients/cli/src/main.rs
- clients/cli/src/move_file.rs
- clients/cli/src/new.rs
- clients/cli/src/new_account.rs
- clients/cli/src/print.rs
- clients/cli/src/remove.rs
- clients/cli/src/rename.rs
- clients/cli/src/status.rs
- clients/cli/src/sync.rs
- clients/cli/src/tree.rs
- clients/cli/src/utils.rs
- clients/cli/src/validate.rs
- clients/linux/lb-api/Cargo.toml
- clients/linux/lb-api/src/lib.rs
- clients/linux/lb-api/src/search.rs
- core/src/lib.rs
- core/src/service/billing_service.rs
Currently, a rust developer who wants to use core must include not only `lockbook_core` in their Cargo.toml, but also `lockbook_models` and `uuid`, leading to a somewhat clumsy setup. This PR re-exports essential things from core so that someone using core (currently the `cli` and `linux` clients) only needs to depend on the `lockbook_core` crate.
> core,clients: improve core reexports

- core/libs/models/src/drawing.rs
- core/src/lib.rs
- core/src/model/errors.rs
- core/src/pure_functions/drawing.rs
- core/src/service/drawing_service.rs
I've been working on drawing for the forthcoming egui client, and therefore came across a few things to refactor relating to drawing code in core. Mostly just additional derives or helpful methods in the draw model.
However, the main thing is that I discovered the `save_drawing` function in core takes the JSON serialized bytes as an argument, which is odd since `get_drawing` returns a `Drawing`. So I refactored that to take a `Drawing` and have the drawing service take care of the JSON serialization.
> core: drawing prep and refactors

- utils/dev/snap-packages/lockbook-desktop/snap/snapcraft.yaml
- utils/dev/snap-packages/lockbook/snap/snapcraft.yaml
The snap package for lockbook-desktop has not been up to date due to the lack of gtk4 support in the snapcraft store. Recently though, this has changed and we are now able to build the package.
We also added source tags to the `snapcraft.yaml` so only the release we want is built.
fixes #1172
> linux: snap package fix

- Cargo.lock
- core/Cargo.toml
- core/src/lib.rs
- core/src/model/errors.rs
- core/src/model/filename.rs
- core/src/service/search_service.rs
- core/tests/search_service_tests.rs
- docs/design-ux/search.md
Searching is an essential feature for lockbook. We already implemented search, but it worked only with file names and returned after scanning all the files. This search implementation will allow a user to get file names and contents while returning the results asynchronously as they come.
- `core/.../search_service.rs`: contains all the logic for this new implementation of search
This iteration of search works off of channels to supply asynchronous matches. Two channels exist, one dealing with sending and receiving search queries and the other with sending and receiving search results. The search algorithm will start by copying all the contents of `.md` and `.txt` files into memory, storing the data in an `Arc`. Once it has all the data, the search moves off into a separate thread. There …
> core: search

- core/src/service/usage_service.rs
I introduced this bug in 9c31141fc7997ab1a87353d811c8e68c9b459bef
Test with:
```
cargo test --color=always --test usage_service_tests
```
> core: fixed usage service human readable bug

- clients/cli/src/billing.rs
- clients/cli/src/debug.rs
- clients/cli/src/share.rs
- clients/linux/src/settings.rs
- clients/linux/src/ui/filetree.rs
- core/libs/shared/src/account.rs
- core/libs/shared/src/api.rs
- core/libs/shared/src/crypto.rs
- core/libs/shared/src/document_repo.rs
- core/libs/shared/src/file.rs
- core/libs/shared/src/file_metadata.rs
- core/libs/shared/src/filename.rs
- core/libs/shared/src/lib.rs
- core/libs/shared/src/path_ops.rs
- core/libs/shared/src/work_unit.rs
- core/src/model/errors.rs
- core/src/service/api_service.rs
- core/src/service/usage_service.rs
- server/admin/src/main.rs
I got rid of Clippy warnings that were stopping us from moving to this version.
> infra: support rust 1.63

- Cargo.lock
- Cargo.toml
- utils/releaser/Cargo.toml
- utils/releaser/src/main.rs
- utils/releaser/src/server.rs
- utils/releaser/src/utils.rs
Push a button to:
+ [x] Build server
+ [x] Release it to our server
In a different PR this will also release the various clients we have to the various distribution channels we use.
I didn't make it part of the existing devtool because the only thing I'd want from there is probably the `assert_success` bits. But even building apple for CI (linux) is different from building it for release. So I figured an isolated binary is probably going to be a better time for me.
> infra: create releaser

- clients/android/app/src/test/java/app/lockbook/MoveFileTest.kt
- clients/cli/src/debug.rs
- core/libs/shared/src/core_ops.rs
- core/libs/shared/src/file_like.rs
- core/libs/shared/src/file_metadata.rs
- core/libs/shared/src/lazy.rs
- core/libs/shared/src/lib.rs
- core/libs/shared/src/server_ops.rs
- core/libs/shared/src/server_tree.rs
- core/libs/shared/src/validate.rs
- core/src/model/errors.rs
- core/src/service/integrity_service.rs
- core/src/service/share_service.rs
- core/src/service/sync_service.rs
- core/tests/delete_and_list_tests.rs
- core/tests/move_file_tests.rs
- core/tests/sharing_tests.rs
- core/tests/sync_service_new_unsynced_client_tests.rs
- core/tests/sync_service_share_tests.rs
- server/server/src/file_service.rs
- test
test fixes:
* deleting a new modified document
* moving a folder with modified document children into a shared folder
* new deleted documents are no longer pushed
other fixes:
* root and deletion validations moved to shared code
* base/local copy on write semantics weren't being respected for documents
* certain document merge conflict resolutions would incorrectly raise validation errors
> core: assorted test fixes

- clients/egui/build.rs
The egui `build.rs` was structured in such a way that cargo builds on linux weren't being cached properly.
> egui: fix build.rs

- Cargo.lock
- clients/egui/src/account/modals/settings/account_tab.rs
- clients/egui/src/account/modals/settings/mod.rs
- clients/linux/Cargo.toml
- clients/linux/src/app/imp_settings_dialog.rs
- core/Cargo.toml
- core/src/lib.rs
- core/src/service/account_service.rs
This adds functionality to core to export account by returning the bytes of a qr code png so that clients can just worry about showing an image.
Closes #1308.
> core,egui: exporting account via qr code

- Cargo.lock
- core/src/service/search_service.rs
- core/tests/search_service_tests.rs
Search was crashing on android. The problem ended up being with the content window being miss-computed, and thus the matched indices were false. Sometimes, the matched indices would be larger than the content window, thus giving an out of bounds error.
The crash happened in android, but it was caused by core.
fixes #1293
> android, core: fix search crashes

- clients/egui/src/account/workspace.rs
- clients/egui/src/theme/icons.rs
This significantly improves the tabs we use for opened docs. Not only is it more polished, but there are also close buttons for each tab that work as expected (meaning clicking close won't focus the tab you are closing like the current gtk client). They also close on middle-click.
Before:
After:
Closes #1312.
> egui: improve appearance of opened doc tabs

- core/tests/exhaustive_sync/experiment.rs
- core/tests/exhaustive_sync/trial.rs
fuzzer would just wait for no current experiments to be running, but in reality it should additionally check if there are any pending experiments
> infra: refine fuzzer termination condition

- clients/egui/src/account/mod.rs
- clients/egui/src/account/syncing.rs
- clients/egui/src/account/tabs/image_viewer.rs
- clients/egui/src/account/tabs/mod.rs
- clients/egui/src/account/tree/mod.rs
- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/tree/state.rs
- clients/egui/src/account/workspace.rs
The egui client now:
* updates file tree state after a sync
* updates editor state after a sync
* updates editor state after an opened document is renamed
* has the ability to "restore" an opened document that was deleted during a sync
Closes #1313.
> egui: update tree and editor state after sync

- core/libs/shared/src/core_ops.rs
- core/tests/sync_service_tests.rs
fixes fuzzer test cases in #1373 (parth's bug remains non-reproducible)
> core: add and fix fuzzer test

- core/libs/shared/src/server_ops.rs
- core/libs/shared/src/server_tree.rs
- server/server/src/account_service.rs
- server/server/src/file_service.rs
- server/server/src/lib.rs
- server/server/src/main.rs
- server/server/src/metrics.rs
- server/server/src/schema.rs
Adds, maintains, and uses indexes for shared files and file children on server. Fuzzer TPS at ~120 TPS on my x64 Macbook Pro (up from 0, presumably at least a 100x performance improvement). Core and Server now spend plurality CPU time on cryptographic operations. CI finishes more than 1 minute faster.
logs from local fuzzer run:
```
Running tests/exhaustive_sync_check.rs (/Users/travis/Code/lockbook/target/release/deps/exhaustive_sync_check-7c4b9c922d339528)
running 1 test
Done: 0, Errors: 0, TPS: 0, Started: just now, Possibly Stalled: []
Done: 526, Errors: 0, TPS: 105, Started: just now, Possibly Stalled: []
Done: 1057, Errors: 0, TPS: 105, Started: just now, Possibly Stalled: []
Done: 1584, Errors: 0, TPS: 105, Started: just now, Possibly Stalled: []
Done: 2158, Errors: 0, TPS: 107, …
```
> server: restore performance after sharing

- core/src/lib.rs
- core/src/service/account_service.rs
- core/src/service/admin_service.rs
- core/src/service/api_service.rs
- core/src/service/billing_service.rs
- core/src/service/document_service.rs
- core/src/service/drawing_service.rs
- core/src/service/file_service.rs
- core/src/service/import_export_service.rs
- core/src/service/integrity_service.rs
- core/src/service/path_service.rs
- core/src/service/search_service.rs
- core/src/service/share_service.rs
- core/src/service/sync_service.rs
- core/src/service/usage_service.rs
- core/tests/api_service_tests.rs
- core/tests/auth_tests.rs
- core/tests/billing_tests.rs
- core/tests/change_document_content_tests.rs
- core/tests/create_file_tests.rs
- core/tests/delete_file_tests.rs
- core/tests/exhaustive_sync/trial.rs
- core/tests/get_document_tests.rs
- core/tests/get_subscription_info_tests.rs
- core/tests/move_file_tests.rs
- core/tests/new_account_tests.rs
- core/tests/rename_file_tests.rs
+ Parameterizes the networking components of core, so that when the fuzzer runs, it can:
+ create independent servers on the fly and run them in parallel
+ skip the networking stack and communicate directly in process with the server for lower latency and higher reliability
+ I was going to do `Box<dyn Requester>` but ran into [this limitation](https://doc.rust-lang.org/reference/items/traits.html#object-safety), `api_service::request` uses type parameters
> Not have any type parameters (although lifetime parameters are allowed),
+ type alias makes this not require any changes to existing clients, type aliasing `RequestContext` would allow this diff to be smaller, future tech debt for me to address.
> core: parameterize client 

- core/libs/shared/src/core_ops.rs
- core/tests/exhaustive_sync/experiment.rs
- core/tests/exhaustive_sync/trial.rs
I ran 100k trials locally without errors. ~TPS drops by about half for the initial trials, which are dominated by `SyncAndCheck`, which is now doing double the syncing and checking.~ I modified the order in which trials are run so that the initial TPS more closely matches the steady state TPS.
fixes https://github.com/lockbook/lockbook/issues/1398
> fuzzer: add multiple users and sharing ops

- core/libs/shared/src/core_ops.rs
- core/libs/shared/src/path_ops.rs
- core/libs/shared/src/validate.rs
- core/tests/sharing_tests.rs
- core/tests/sync_service_concurrent_change_tests.rs
This updates the `{path,id}_by_{id,path}` functions to match `resolve_and_finalize` and fixes resulting test failures. This also fixes an issue where cli was trying to rename the targeted file instead of the link when renaming a shared folder, resulting in an inappropriate `NotPermissioned` error (I suspect this is an error on other clients that have sharing implemented as well).
> core: resolve paths for links instead of linked files

- core/libs/shared/src/core_ops.rs
- core/libs/shared/src/document_repo.rs
- core/libs/test_utils/src/lib.rs
- core/src/lib.rs
- core/src/repo/schema_v2.rs
- core/src/service/document_service.rs
- core/src/service/drawing_service.rs
- core/src/service/import_export_service.rs
- core/src/service/sync_service.rs
- core/tests/document_tests.rs
- core/tests/get_usage_tests.rs
- core/tests/sharing_tests.rs
- core/tests/sync_service_concurrent_change_tests.rs
* document repo now refers to doc contents by id+hmac, not id+source, which allows us to store multiple versions on disk
* new document contents are written directly to disk without deleting old contents until after metadata changes are committed, making document writes atomic with their corresponding metadata writes
* document contents are no longer collected in memory e.g. as part of sync
> core: document management improvements

- core/src/model/errors.rs
This implements `fmt::Display` on `TestRepoError` so that a third party tool can just print out a message if they wanted to when using `validate`.
> core: impl display on test repo error

- clients/admin/src/main.rs
- core/libs/shared/src/symkey.rs
- server/server/src/main.rs
I don't believe these `extern crate` statements serve any purpose whatsoever.
> core,server,admin: remove useless extern crate statements

- core/libs/shared/src/file_metadata.rs
this allows devs to have `ToString` on `FileType`. it just uses the Debug text for now.
> shared: impl Display on FileType

- core/src/service/api_service.rs
- server/server/src/lib.rs
- server/server/src/router_service.rs
Changes were made on two fronts:
1. In the routes handler located in `router_service.rs` >  `core_req!`, a warp header filter was added for an `Accept` header which stores the core version. 
2. the `Requester` in `api_service.rs` was changed to inject the core version as an `Accept` header. As far as I understand, most core requests sent to the server pass through  `fn request` in `impl Requester for Network`
no tests were written. I'd love to have a discussion about the granularity of tests that we maintain. @Parth suggested a test for requests missing an `Accept` header, but I don't know if or why that's necessary. isn't the purpose of warp filters to validate the request? 
fixes: #1239
> core, server: core version should be stored in the header of the request 

- libs/core/libs/shared/src/core_ops.rs
- libs/core/libs/shared/src/validate.rs
- libs/core/tests/sync_service_share_tests.rs
- libs/core/tests/validate_tests.rs
* validate was not catching directly shared links
* sharing a link should be interpreted as sharing its target but wasn't
fixes #1461
> core: fix resharing files

- server/server/src/billing/app_store_client.rs
- server/server/src/billing/app_store_model.rs
- server/server/src/config.rs
The app store verifies our Storekit implementation by testing it out themselves. They do this using "sandbox testing," which utilizes our production server.
Formerly, this was not supported since I believed our production server would not need to have testing capabilities, but since then I have learned apple's app review team may need it.
> server: support sandbox testing requests

- clients/apple/iOS/FileTreeView.swift
In portrait on startup, the apple ipad client cannot see its file tree. This is because the file tree is a hidden drawer and no file is open so the screen appears empty.
I added a message on that screen so the understands what is going on.
<details>
</details>
> apple: ipad hidden file tree message

- clients/admin/src/indexes.rs
- clients/admin/src/main.rs
- libs/core/libs/shared/src/api.rs
- libs/core/src/lib.rs
- libs/core/src/model/errors.rs
- libs/core/src/service/admin_service.rs
- libs/core/tests/admin_tests.rs
- server/server/src/file_service.rs
- server/server/src/router_service.rs
+ delete account logic is incomplete #1521 
+ smail created an account and then shared some stuff to his main account and then deleted that account
+ that account's deletion eliminated files that smail owned and were shared to that account
+ smail now had files in his owned_files that no longer exist
+ this allows us to, on demand rebuild various indexes after admin action has been taken
+ wrote a lil test
> admin: rebuild indexes on demand

- Cargo.lock
- libs/core/Cargo.toml
- libs/core/libs/shared/Cargo.toml
- libs/core/libs/test_utils/Cargo.toml
- server/server/Cargo.toml
`async-stripe` I believe is the one locked into `0.8.1` which is the reason why the lock file is adding the new version.
The impetus for upgrading is that this version gives us the `Uuid::into_bytes` method.
> core,shared,server: upgrade uuid from 0.8.1 to 1.2.2

- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/lib.rs
A little oversight on my part: the font registry starts out with a new `FontDefinitions` when the editor registers fonts. This means either its fonts are getting registered, or the clients are getting registered.
This change makes it so that registering modifies a provided `FontDefinitions`.
> editor: pass font definitions into register instead of starting a new one

- Cargo.lock
- clients/egui/Cargo.toml
- clients/egui/src/account/modals/help.rs
- clients/egui/src/account/tabs/drawing.rs
- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/workspace.rs
- clients/egui/src/widgets/button_group.rs
- clients/egui/src/widgets/progress_bar.rs
- libs/editor/egui_editor/Cargo.toml
- libs/editor/egui_editor/src/appearance.rs
- libs/editor/egui_editor/src/apple/apple_ffi.rs
- libs/editor/egui_editor/src/draw.rs
- libs/editor/egui_editor/src/element.rs
- libs/editor/egui_editor/src/lib.rs
- utils/winstaller/Cargo.toml
This bumps egui version from 0.19 to 0.20, which has an image painting UI that supports resizing images (most recent is 0.21 but has additional breaking changes that I didn't want to deal with).
~Todo: for some reason, text is larger and colors aren't right 🤔~
> editor/egui client: update egui

- libs/core/src/lib.rs
- libs/core/src/repo/mod.rs
if a migration occurs, cleanup any old log files that may exist, ignore any errors if a cleanup doesn't work.
Tested manually by me from 0.5.11 using cli
> core: cleanup old logs after a successful migration

- libs/core_external_interface/src/c_interface.rs
As far as I can tell, this is not used in any client, but specifically here the apple clients.
> c-interface: remove the 'list_paths' endpoint mapping

- utils/dev-tool/src/workspace.rs
This would have caught the errors that were fixed in https://github.com/lockbook/lockbook/pull/1599
> dev-tool: use --all-targets to also cover benches

- clients/cli/src/imex.rs
- libs/core/src/lib.rs
- libs/core/src/service/import_export_service.rs
- libs/core/tests/import_export_file_tests.rs
- libs/core_external_interface/src/lib.rs
Import still returns on any error, so the error variant of the status is unused.
> core: drop unused error variant from import status

- libs/core/Cargo.toml
- libs/core/src/lib.rs
- libs/core/src/service/sync_service.rs
this change uses standard iter functionality for the last two instances of itertools trait funcs in core and makes itertools a dev dep since we still use it in tests. no impact on static lib size but one less dep for core.
> core: eliminate two unecessary uses of itertools and it make dev dep

- Cargo.lock
- clients/admin/Cargo.toml
- clients/admin/src/error.rs
- libs/core/Cargo.toml
- libs/core/src/model/errors.rs
- libs/core_external_interface/Cargo.toml
- libs/core_external_interface/src/errors.rs
the backtrace crate provides some cool additional functionality for inspecting and using backtraces, none of which we are using. so this change removes it as a dep and just uses std::backtrace instead.
this resulted in 8 less dependencies for core and ~2M reduction in the static lib size.
> core,ffi,admin: drop backtrace crate in favor of standard backtrace

- Cargo.lock
- libs/core/Cargo.toml
- libs/core/src/service/search_service.rs
- libs/core/tests/search_service_tests.rs
The results and their order seem identical to fuzzy-matcher.
> core: use sublime_fuzzy for path search and drop fuzzy-matcher dep

- clients/apple/Shared/Stateful Logic/FileService.swift
- clients/apple/Shared/Views/BookView.swift
- clients/apple/Shared/Views/DocumentView.swift
- clients/apple/Shared/Views/ListFileCell.swift
- clients/apple/Shared/Views/NewFileSheet.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Models/File.swift
- clients/apple/iOS/FileListView.swift
- clients/apple/iOS/FilePathBreadcrumb.swift
- clients/apple/lockbook.xcodeproj/project.pbxproj
Traditionally, we used `NavigationView` to keep track of the file tree structure on iOS. The problem with this implementation was that `NavigationView` was not supposed to be used dynamically in this way. This caused a myriad of bugs (which are resolved now by the new implementation). This PR removes `NavigationView` in place of just mutating a list. Gestures and animation were manually added back, although are not the exact same. 
In addition, I added a file path breadcrumb. Every time a user opens a new folder, the old folder appears in the breadcrumb. If the path becomes larger than the width of the iOS device, the breadcrumb will automatically scroll to the latest folder.
**Screenshot**:
<details>
</details>
fixes #1533
fixes #1529
> apple: remove navigation link file tree

- libs/core/libs/shared/src/path_ops.rs
I forgot to clean this up after the cli redesign, which eliminated the only time we were parsing a `Filter` from strings.
> shared: remove unused Filter derives and parse fn in path_ops

- libs/editor/egui_editor/src/events.rs
> editor: command backspace deletes from row start to cursor

- utils/releaser/src/linux/cli.rs
Since the snapcraft package files were removed and instead created only when we needed it, the directory it was located under for `lockbook cli` became empty. This meant `git` untracked it, and was removed. This directory is still needed as a part of the correct directory structure when building a snapcraft package, and cause releaser to error if it is not found.
I now create the directory if it does not already exist, and since it is always untracked, I do not need to clean it up.
> releaser: fix snap release for lockbook cli

- libs/core/libs/shared/src/lib.rs
I missed one when changing capture to force capture for backtracing on errors.
> shared: force capture backtrace when converting kind to shared error

- clients/egui/src/account/mod.rs
- clients/egui/src/account/modals/mod.rs
- clients/egui/src/account/modals/new_file.rs
- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/tree/response.rs
This also allows for creating files with no extensions by having the "plain text" option be empty instead of `.txt`.
Closes #1384.
> egui: use a separate menu item and modal for creating new folder

- clients/cli/src/edit.rs
in addition to vim, nano, and emacs, this pr introduces support for nvim
> cli: add nvim support

- clients/egui/src/account/mod.rs
- clients/egui/src/account/workspace.rs
There is still room for improving the uiux around saving, for example:
* keep the tab open while saving and then report any error back there.
* still close the tab (currently the case) and then report any error via dialog.
But for now, this prevents one form of data loss.
Checks one box in https://github.com/lockbook/lockbook/issues/1676.
@parth UAT if you can.
> egui: save tabs when closing them

- clients/egui/src/account/tree/node.rs
Dropping a file in its current parent would cause its icon to be a folder. This fixes that by more accurately determining the icon type for a tree node.
Resolves the 2nd task in https://github.com/lockbook/lockbook/issues/1682
> egui: fix icon change from dropping file in same parent

- .github/workflows/integration.yml
- Cargo.lock
- utils/dev-tool/src/main.rs
- utils/dev-tool/src/workspace.rs
- utils/releaser/Cargo.toml
- utils/releaser/src/utils.rs
We were detecting lock file changes by doing a `cargo check --locked`. If you run this locally with/without a `.lock` it will behave as expected. However we invoke this at the end of our CI, at which file, if a lockfile change had not been pushed, the lockfile would have been updated by any of the commands that we run prior to it. My first thought was to just check this first. But the way we check -- inside a rust program that's a part of the workspace -- makes this infeasible.
So then I thought about just extracting out the `cargo check --locked` into the yml file for the CI job, but this needlessly overlaps with the `clippy` call we'll do later.
So I ultimately ended up asserting that after CI is done `git diff` must be empty.
> infra: macos bump bundle version (releaser), detect lockfile changes (dev-tool)

- clients/egui/src/account/modals/settings/mod.rs
- clients/egui/src/widgets/subscription.rs
I don't know why `Response::interact` ceased to work after `0.20`, but good news is that `Ui::interact` still works!
Closes #1674.
> egui: unbreak settings tab and fix usage bar

- libs/editor/egui_editor/src/apple/apple_ffi.rs
- utils/releaser/src/main.rs
- utils/releaser/src/secrets.rs
- utils/releaser/src/server.rs
- utils/releaser/src/utils.rs
- utils/releaser/src/version.rs
+ cleanup code around version bumps and express version bump types to clap more ergonomically
+ fire away a `cargo check` to generate the lockfile
+ push it all to a branch
+ also publish `lockbook-server` along with every release
+ also better error messages for missing env vars
fixes #1562 
I was going to generate a 32 bit version of the windows egui binary, but it didn't compile, in exactly the same manner that the arm binary doesn't compile, so that's going to be something to look into later.
> releaser: better version bump & publish lockbook-server

- clients/cli/Cargo.toml
- clients/cli/src/main.rs
fixes #1691
```
[I] parth@Parths-MBP ~/D/l/l/c/cli (cli-version-about)> lockbook
The private, polished note-taking platform.
Usage: lockbook <COMMAND>
Commands:
account  account related commands
copy     import files from your file system into lockbook
debug    investigative commands
delete   delete a file
edit     edit a document
export   export a lockbook file to your file system
list     list files and file information
move     move a file to a new parent
new      create a new file at the given path or do nothing if it exists
print    print a document to stdout
rename   rename a file
share    sharing related commands
sync     file sync
help     Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
[I] parth@Parths-MBP …
```
> cli: restore version flag

- libs/editor/egui_editor/src/input/canonical.rs
Adds input parsing tests for {none or cmd} x {none or shift} x {up or down} + {none or alt or cmd} x {none or shift} x {left or right} + {none or shift} x {home or end} as a proof of concept for input parsing tests.
Testing remaining intended input combinations (e.g. text, enter, backspace, tab, clicks) as well as conflict resolution for current cases (e.g. cmd+alt+left should resolve the same as cmd+left) is left as future work.
> editor: input tests

- libs/editor/egui_editor/src/appearance.rs
> editor: reduce text highlight background intensity on dark mode

- clients/egui/src/account/modals/new_file.rs
- clients/egui/src/widgets/button_group.rs
This resulted in an unused lifetime param in the button group widget.
The builtin egui `SelectableLabel` widget is used instead of our custom button group. Still needs to be polished, but it's clearer about which option is selected.
> egui: remove 'Plain Text' option from new file dialog and use clearer ui

- libs/core/Cargo.toml
https://doc.rust-lang.org/cargo/reference/profiles.html
> Cargo only looks at the profile settings in the Cargo.toml manifest at the root of the workspace. Profile settings defined in dependencies will be ignored.
Removing this causes no change in the final core lib. Adding it to the workspace Cargo.toml file causes an increase from 66M to 352M.
> core: remove ignored release profile config

- clients/apple/Shared/Views/BottomBar.swift
- clients/apple/iOS/OutlineView/OutlineRow.swift
From:
<details>
</details>
To:
<details>
</details>
fixes #1641
> apple: fix ipad portrait dark mode icons

- libs/editor/egui_editor/src/input/canonical.rs
- libs/editor/egui_editor/src/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/1789
Previous behavior was to move cursor regardless of if there's a selection. New behavior is to do that under the following conditions, otherwise snap the cursor to the start or end of the selection instead:
1. `extend_selection`: if we're extending the selection (e.g. shift+right), we naturally shouldn't snap the cursor (which would clear the selection) when an arrowkey is pressed
2. `current_cursor.selection.is_empty()`: if there's no selection and we're just arrowkey'ing around the doc, we should move the cursor as usual
3. `matches!(offset, Offset::To(..))`: if we're moving the selection to a word/line/paragraph/doc boundary, go ahead and move it to that boundary, so that e.g. cmd+right and end keys still move the cursor to the end …
> editor: fix arrow key behavior when there's a selection

- libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/lib.rs
fixes https://github.com/lockbook/lockbook/issues/1773
demo: https://discord.com/channels/1014184997751619664/1026208854280777789/1116403913969643621
Note that this supports floating cursor via holding the spacebar. Long pressing the cursor and dragging is not supported and will just scroll.
> editor: support floating cursor on iOS

- clients/apple/Shared/LockbookApp.swift
- clients/apple/iOS/FileTreeView.swift
- clients/apple/macOS/FileListView.swift
Pressing `Cmd+Shift+F` will now allow you to initiate your document and content search.
fixes #1794
> apple: macOS and iPadOS search shortcuts

- libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/input/advance.rs
- libs/editor/egui_editor/src/input/canonical.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/lib.rs
fixes https://github.com/lockbook/lockbook/issues/1791 (pending QA)
based on #1778 (uses `Bound::Paragraph`)
also fixes an issue where option+arrowkey would treat annotations as multiple words
> editor: iOS tokenizer

- clients/apple/Shared/Stateful Logic/DocumentLoader.swift
- clients/apple/Shared/Views/DocumentView.swift
The sync bug is caused by SwiftUI recreating the editor when the file's metadata has changed. Often times it is just the `lastModified` field. The change in metadata should not cause the editor to be recreated, since nothing has actually changed (and if there is a document content change, that is propagated to the editor directly through `EditorState`). To fix this, I changed `meta` in `DocumentLoader` into a regular variable, rather than one that is `Published`.
Also modified the shortcut for heading 1, and added shortcuts for headings 2-4.
fixes #1817
fixes #1819
> apple: change conflicting toolbar shortcut and fix toolbar sync bug

- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/input/advance.rs
- libs/editor/egui_editor/src/input/cursor.rs
- libs/editor/egui_editor/src/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/1740
Solution is a bit hacky; I will consider this use case while working on cursor improvements (#1836)
> editor: fix delete annotation at beginning of doc

- libs/editor/egui_editor/src/input/advance.rs
fixes https://github.com/lockbook/lockbook/issues/1833
before:
https://github.com/lockbook/lockbook/assets/6198756/b0b12d01-2bd6-4d3c-af61-9cecd3645184
after:
https://github.com/lockbook/lockbook/assets/6198756/94f9865b-1ddc-41ae-be93-d8abf00e4e2f
> editor: reset cursor x coordinate when not line jumping

- clients/egui/src/theme/palette.rs
> egui: fix color contrast on light mode

- libs/editor/egui_editor/src/appearance.rs
- libs/editor/egui_editor/src/editor.rs
fixes #1878 
added margin on the top, and decreased margin on medium size screens. 
for colors: i made the editor's background true white and true black. it looks crispier. 
after
<details>
</details>
before
<details>
<details>
> editor: enhance background color and refine margins

- libs/editor/egui_editor/src/input/canonical.rs
fixes https://github.com/lockbook/lockbook/issues/1910
QA note: Not QA'd because I'm on MacOS and I use command+tab which is working as expected
> editor: ignore alt tab

- Cargo.lock
- clients/cli/Cargo.toml
- clients/cli/src/edit.rs
addresses this cargo audit warning:
```
Crate:     net2
Version:   0.2.39
Warning:   unmaintained
Title:     `net2` crate has been deprecated; use `socket2` instead
Date:      2020-05-01
ID:        RUSTSEC-2020-0016
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0016
Dependency tree:
net2 0.2.39
├── miow 0.2.2
│   └── mio 0.6.23
│       ├── notify 4.0.17
│       │   └── hotwatch 0.4.6
│       │       └── lockbook-cli 0.7.6
│       └── mio-extras 2.0.6
│           └── notify 4.0.17
└── mio 0.6.23
```
> cli: update hotwatch

- libs/editor/egui_editor/src/ast.rs
- libs/editor/egui_editor/src/input/canonical.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/1872
also fixes an issue where cursor is in wrong place after replacing a list item of one type with that of another
also adds hotkeys for list items
> editor: rewrite list item replacement using ast

- clients/apple/Shared/Stateful Logic/DocumentService.swift
- clients/apple/Shared/Views/DocumentTabView.swift
- clients/apple/Shared/Views/DocumentView.swift
- libs/editor/SwiftEditor/Sources/Editor/EditorState.swift
- libs/editor/SwiftEditor/Sources/Editor/EditorView.swift
- libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/editor.rs
fixes #1935
On iOS and iPadOS, users can lose keyboard focus using the hide keyboard button located on the toolbar.
<details>
</details>
> apple: toolbar hide keyboard

- libs/core/tests/exhaustive_sync/stats.rs
in that previous chart work was the largest element
> fuzzer: fix timing

- clients/apple/Shared/LockbookApp.swift
- clients/apple/Shared/Stateful Logic/FileService.swift
- clients/apple/Shared/Stateful Logic/SyncService.swift
- clients/apple/iOS/Info.plist
For all apple platforms, background sync will now run (the earliest) after 5 minutes of the app being in the background, and an hour repeatedly after.
> apple: background sync

- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/bounds.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/galleys.rs
- libs/editor/egui_editor/src/input/advance.rs
- libs/editor/egui_editor/src/input/canonical.rs
- libs/editor/egui_editor/src/input/click_checker.rs
- libs/editor/egui_editor/src/input/cursor.rs
- libs/editor/egui_editor/src/input/events.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/test_input.rs
fixes https://github.com/lockbook/lockbook/issues/1847
also fixes an issue where alt+left on iOS doesn't jump over bullets etc in one go
> editor: bounds refactor

- libs/editor/egui_editor/src/appearance.rs
- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/ast.rs
- libs/editor/egui_editor/src/bounds.rs
- libs/editor/egui_editor/src/draw.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/galleys.rs
- libs/editor/egui_editor/src/input/advance.rs
- libs/editor/egui_editor/src/input/click_checker.rs
- libs/editor/egui_editor/src/input/cursor.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/layouts.rs
- libs/editor/egui_editor/src/style.rs
- libs/editor/egui_editor/src/test_input.rs
based on https://github.com/lockbook/lockbook/pull/1924
fixes https://github.com/lockbook/lockbook/issues/1838
fixes https://github.com/lockbook/lockbook/issues/1900
fixes https://github.com/lockbook/lockbook/issues/1902
Which markdown elements have syntax characters captured is configurable, but right now only at compile time.
This will require a more formal demo for the next release after UX feedback from the team. For now, here's some screencaps showing the new behavior:
Plain text mode:
Block mode:
Rich text mode:
https://github.com/lockbook/lockbook/assets/6198756/ab837abc-2148-4880-ad1e-995e757a1ba7
> editor: capture more syntax characters

- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/style.rs
I hereby declare asterisks the top-tier bulleted list character 👑 
*'s most closely resemble •'s
+'s don't render as bullets in slack, where I commonly paste a copied bulleted list text
-'s can cause other text to become a header before you start typing, e.g. in
```
confusingly a header
- 
```
confusingly a header
-
> editor: prefer asterisks for bullets

- libs/editor/egui_editor/src/ast.rs
- libs/editor/egui_editor/src/bounds.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/style.rs
- libs/editor/egui_editor/src/test_input.rs
based on https://github.com/lockbook/lockbook/pull/2011
fixes https://github.com/lockbook/lockbook/issues/2007
Also changes default bold and italic characters from underscores to asterisks because they don't need whitespace around them whereas underscores do.
https://github.com/lockbook/lockbook/assets/6198756/45f54724-ee73-45ea-803d-e0c30e27875d
> editor: toggle off current style with empty selection

- libs/editor/egui_editor/src/galleys.rs
before this PR, heading rules are not rendered when the cursor is in the heading
> editor: fix unrendered heading rule

- Cargo.lock
- libs/editor/egui_editor/Cargo.toml
- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/ast.rs
- libs/editor/egui_editor/src/bounds.rs
- libs/editor/egui_editor/src/draw.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/galleys.rs
- libs/editor/egui_editor/src/input/click_checker.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/offset_types.rs
- libs/editor/egui_editor/src/style.rs
fixes https://github.com/lockbook/lockbook/issues/2009
- fixes an issue where galley head sizes were calculated incorrectly in the presence of heading rules
- fixes an issue where the galley of a click was calculated incorrectly
- reduces ast traversals and replaces some linear searches with binary searches (gains not measured, but we should check the use case in https://github.com/lockbook/lockbook/issues/2030 after merging)
https://github.com/lockbook/lockbook/assets/6198756/04928b2e-f226-4cc1-a3fb-08338a56647d
> editor: plaintext links, bug fixes

- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/workspace.rs
- clients/egui/src/theme/palette.rs
- clients/egui/src/theme/visuals.rs
slight visual changes in the aesthetics of the sidebar file tree to make the ui feel more modern and sleek. 
after: 
https://github.com/lockbook/lockbook/assets/66345861/dedb21e5-0f41-44db-9080-fa2fe16c871e
before: 
<details>
</details
> egui: file tree style improvments

- libs/editor/egui_editor/src/bounds.rs
- libs/editor/egui_editor/src/input/mutation.rs
- libs/editor/egui_editor/src/offset_types.rs
- fixes https://github.com/lockbook/lockbook/issues/2079
- fixes an issue where toggling style with empty selection in a nonempty document would do nothing
- fixes an issue where toggling the current style at the end of the styled region would insert characters instead of advancing to after the region
- fixes anything else using range binary search (implemented since last release)
- improves toggle style when selection bounds are in syntax sequences
> editor: toggle style refinements

- libs/editor/egui_editor/src/galleys.rs
fixes https://github.com/lockbook/lockbook/issues/2064
This works for cases I tried but I might be missing something - try opening an image-heavy document to confirm everything's good here.
> editor: fix small image stretch

- libs/editor/egui_editor/src/apple/ios_ffi.rs
- libs/editor/egui_editor/src/galleys.rs
fixes https://github.com/lockbook/lockbook/issues/2049 (graphical glitch and non-indenting-behavior)
> editor: handle tab input as indent

- Cargo.lock
- clients/apple/Shared/Views/DocumentView.swift
- clients/egui/src/account/mod.rs
- clients/egui/src/account/tabs/markdown.rs
- libs/core_external_interface/src/c_interface.rs
- libs/editor/SwiftEditor/Sources/Editor/EditorView.swift
- libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/editor/SwiftEditor/Sources/Editor/macMTK.swift
- libs/editor/egui_editor/Cargo.toml
- libs/editor/egui_editor/src/apple/common_ffi.rs
- libs/editor/egui_editor/src/draw.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/galleys.rs
- libs/editor/egui_editor/src/images.rs
- libs/editor/egui_editor/src/main.rs
fixes https://github.com/lockbook/lockbook/issues/2077
https://github.com/lockbook/lockbook/assets/6198756/af2d23b1-e83c-4508-9218-40830869891e
> editor: image refinements

- libs/editor/egui_editor/src/galleys.rs
...even if the cursor is in the markdown source for the image or whatever
https://github.com/lockbook/lockbook/assets/6198756/61b46d69-935a-4b65-9484-03d7643a4c63
> editor: always render images

- clients/apple/Shared/Stateful Logic/DocumentService.swift
- clients/apple/Shared/Stateful Logic/FileService.swift
- clients/apple/Shared/Stateful Logic/ImportExportService.swift
- clients/apple/Shared/Views/DocumentView.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/CoreApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/FakeApi.swift
- clients/apple/SwiftLockbookCore/Sources/SwiftLockbookCore/Apis/LockbookApi.swift
- libs/editor/SwiftEditor/Sources/Editor/EditorState.swift
- libs/editor/SwiftEditor/Sources/Editor/EditorView.swift
- libs/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/editor/SwiftEditor/Sources/Editor/macMTK.swift
- libs/editor/egui_editor/src/apple/common_ffi.rs
- libs/editor/egui_editor/src/editor.rs
- libs/editor/egui_editor/src/images.rs
Images can now be pasted into the editor. Lockbook will automatically import the file and insert the appropriate markdown syntax for the image to appear.
Demonstration
<details>
https://github.com/lockbook/lockbook/assets/20663038/bbdce5d5-9600-45d0-92d8-ed0b8d33244d
</details>
fixes #2113
> apple: paste images in editor

- clients/apple/Shared/Views/BottomBar.swift
> apple: hide upgrade to premium button when user is already premium

- Cargo.lock
- clients/cli/Cargo.toml
- clients/cli/src/input.rs
- clients/cli/src/main.rs
- utils/releaser/Cargo.toml
adds version support to the CLI and uses a number of fixes and features in the latest cli_rs (https://github.com/lockbook/cli-rs/pull/20)
> cli: cli_rs 0.1.12

- utils/releaser/src/version.rs
apple needs these to be strictly increasing, we format our version keys:
yyyymmdd 
but 
202391
is less than
2023825
so we need to make it
20230901
fixes #2056
> releaser: fix version bump for single digit fields

- clients/apple/lockbook.xcodeproj/project.pbxproj
- libs/content/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
- libs/content/editor/SwiftEditor/Sources/Editor/macMTK.swift
fixes #2192
The high cpu/energy usage was due to two bugs:
1. Every open tab would be re-rendered when the mouse moved
2. Converting `redraw_in`'s `u64` value to swift's `Int` would result in an overflow, and due to the way we schedule re-draws, this caused the editor to re-render immediately.
> apple: fix significant cpu usage in editor

- clients/cli/src/main.rs
- clients/cli/src/stream.rs
Main thing to review: `clients/cli/src/stream.rs`
+ defines the `stream in` and `stream out` (formerly `print`) subcommand in the `lockbook` cli. 
+ allows someone to write pretty big files via std stream, along with blocking indefinitely on the output of a program (`tail -f` for instance).
+ also allows someone to specify the `--append` flag to append to the file within lockbook, rather than overwrite it.
fixes #2181
> cli: lockbook stream in && lockbook stream out

- clients/cli/src/edit.rs
- clients/cli/src/main.rs
+ makes CLI usable on windows out of the box (#2227 but a lil nicer)
+ in addition to LOCKBOOK_EDITOR also try to detect if VISUAL or EDITOR is a value we recognize
+ ultimately fallback to vim if all else fails 
fixes #2180
> cli: respect more system env vars: EDITOR, VISUAL, and HOMEPATH (windows)

- libs/content/editor/egui_editor/src/bounds.rs
- libs/content/editor/egui_editor/src/draw.rs
- libs/content/editor/egui_editor/src/editor.rs
- libs/content/editor/egui_editor/src/galleys.rs
- libs/content/editor/egui_editor/src/input/canonical.rs
- libs/content/editor/egui_editor/src/input/mutation.rs
- libs/content/editor/egui_editor/src/style.rs
- libs/content/editor/egui_editor/src/test_input.rs
* links are underlined
* links are blue even in inline code sections or other places they might be another color
* cursor is styled blue in plaintext links
* plaintext links ignored in code blocks
* pointing hand cursor icon when cmd+hovering a link
* enter finishes link workflow even in a list item
* in touch mode, don't open links when dragging
fixes https://github.com/lockbook/lockbook/issues/2209
fixes https://github.com/lockbook/lockbook/issues/2172
fixes https://github.com/lockbook/lockbook/issues/2173
fixes https://github.com/lockbook/lockbook/issues/2189
https://github.com/lockbook/lockbook/assets/6198756/1127c1a5-b392-4f54-9491-cdbb9e08ddf9
https://github.com/lockbook/lockbook/assets/6198756/1a943404-8146-4cfa-bd4a-b1c79072ab72 …
> editor: link refinements

- libs/content/editor/egui_editor/src/apple/ios_ffi.rs
- libs/content/editor/egui_editor/src/bounds.rs
- libs/content/editor/egui_editor/src/draw.rs
- libs/content/editor/egui_editor/src/editor.rs
- libs/content/editor/egui_editor/src/galleys.rs
- libs/content/editor/egui_editor/src/input/cursor.rs
- libs/content/editor/egui_editor/src/input/mutation.rs
- libs/content/editor/egui_editor/src/style.rs
* 10px more space for numbered list numbers (affects all list types)
* render cursor before annotation if that's where it is
* tune behavior when cursor is before annotation (e.g. newline should not trigger item insertion/deletion/renumbering)
* support changing type of nested list item
fixes https://github.com/lockbook/lockbook/issues/2202
fixes https://github.com/lockbook/lockbook/issues/2193
fixes https://github.com/lockbook/lockbook/issues/2204
https://github.com/lockbook/lockbook/assets/6198756/29245c08-da2d-48d8-8c4e-2e813cad2725
> editor: list refinements

- clients/egui/src/account/workspace.rs
- libs/content/editor/egui_editor/src/editor.rs
- Fixes a variety of pointer hover states in the egui version
- Adds pointer cursor for tab hover
- Stops the editor from setting the default cursor, which was overriding other cursor styling in the app (search input, setting, sync, and collapse button)
- Adds pointer styling for tabs when any hovering occurs
> egui: fix hover states and add pointer hand for tabs

- .github/workflows/integration.yml
- libs/content/editor/egui_editor/src/bounds.rs
- libs/lb/lb-rs/src/model/drawing.rs
- libs/lb/lb_external_interface/Makefile
- libs/lb/lb_external_interface/rust-toolchain.toml
- rust-toolchain.toml
- server/server/src/billing/stripe_service.rs
- server/server/src/file_service.rs
+ specify rust version using `rust-toolchain.toml` eliminating the "can you tell me the output of `cargo --version`?"
+ in only `lb_external_interface` add `targets` via `rust-toolchain.toml` eliminating the need to `rustup` manually when you `make swift_libs`
+ build many targets with a single `cargo build --release` call, greatly speeding up compile times for people building for Apple & Android.
+ fix new clippy problems
fixes #1858
> infra: rust-toolchain.toml

- clients/egui/src/account/mod.rs
- clients/egui/src/account/tabs/svg_editor/main.rs
- clients/egui/src/account/tabs/svg_editor/mod.rs
- clients/egui/src/account/tabs/svg_editor/pen.rs
- clients/egui/src/account/tabs/svg_editor/toolbar.rs
Introduce curve smoothing and reduce space consumption by  _40-50%_  (based on this rough unscientific example where the old pen's file size 10k , and the new one's file size is 16k).   
fixes: #2262
<details>
</details>
> egui: smooth and storage efficient pen tool

- clients/egui/src/account/mod.rs
fixes: #2272 
`Ctrl+E` to toggle zen mode, ie toggle the sidebar's visibility
> egui: add keyboard shortcut to toggle zen mode

- clients/windows/src/input/file_drop.rs
- clients/windows/src/window.rs
Fixes issues with cpu/energy consumption, reducing baseline from ~10% to ~1%. Redraw when necessary instead of redrawing continuously at max speed.
> windows: event loop refinements

- libs/content/editor/SwiftEditor/Sources/Editor/iOSMTK.swift
fixes #2301 
Two gestures that are a part of `UITextInteraction`, which are `UITextMultiTapRecognizer` and `UITapAndAHalfRecognizer`, were consuming single tap events. These gestures are a part of a list of other gestures, all of which are private classes. So I had to do string comparisons to get these two gestures, and stop their gestures from canceling touches in the mtk view.
Even when a checkbox is checked with a tap, selection can change at the same time. That is because both operations are happening simultaneously, rather than depending on one another.
> iOS, iPadOS: fix checkboxes

- clients/egui/src/account/mod.rs
- libs/content/workspace/src/widgets/button.rs
- libs/content/workspace/src/workspace.rs
> Center the new document button on the welcome screen

- libs/content/workspace/src/tab/svg_editor/eraser.rs
- libs/content/workspace/src/tab/svg_editor/history.rs
- libs/content/workspace/src/tab/svg_editor/selection.rs
Now you can scale elements by dragging their edges or by using the keyboard shortcuts of 
- `+` scale up
-  `-` scale down
--- 
Limitations and future considerations:
- Mouse scaling doesn't snap to the current cursor position.  
- You can't change the aspect ratio of the scaled elements. the scale factor in the x axis and y axis are always the same.
- The ability to rotate elements would be nice
https://github.com/lockbook/lockbook/assets/66345861/9d75bf01-b87e-4af4-baf0-f19a47dcb339
> canvas: selection scale

- Cargo.lock
- clients/admin/Cargo.toml
- clients/android/app/build.gradle
- clients/apple/iOS/Info.plist
- clients/apple/macOS/Info.plist
- clients/cli/Cargo.toml
- clients/egui/Cargo.toml
- clients/linux/Cargo.toml
- clients/windows/Cargo.toml
- libs/content/editor/egui_editor/Cargo.toml
- libs/content/workspace-ffi/Cargo.toml
- libs/content/workspace/Cargo.toml
- libs/lb-fs/Cargo.toml
- libs/lb/c_interface_v2/Cargo.toml
- libs/lb/lb-rs/Cargo.toml
- libs/lb/lb-rs/libs/shared/Cargo.toml
- libs/lb/lb-rs/libs/test_utils/Cargo.toml
- libs/lb/lb_external_interface/Cargo.toml
- server/server/Cargo.toml
- utils/dev-tool/Cargo.toml
- utils/releaser/Cargo.toml
- utils/winstaller/Cargo.toml
bumping minor version because when struggling to deploy last time I had to deploy an 0.8.42 to the app store, and 0.8.5 is considered less than 0.8.42 because 42 > 5...
so just to avoid any releasing problems going to 0.9.0
fixes #2430
> all: 0.9.0

- docs/guides/build/apple.md
* added step to run the workspace-ffi create_libs.sh
* added what to open with xcode
* added how to sign the app
> docs: update apple build guide

- libs/content/workspace-ffi/src/lib.rs
fixes https://github.com/lockbook/lockbook/issues/2473
Applies a fix that was already applied to a copy of this function in clients/egui/src/lib.rs. De-duplication tracked by https://github.com/lockbook/lockbook/issues/2475.
> workspace: only configure non-empty surfaces

- clients/apple/macOS/Settings/AccountSettingsView.swift
> macos: private key hint string to match iOS

- clients/egui/src/account/mod.rs
- clients/egui/src/account/tree/mod.rs
- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/tree/state.rs
- libs/content/workspace/src/workspace.rs
fixes: [#2405](https://github.com/lockbook/lockbook/issues/2405)
fixes: https://github.com/lockbook/lockbook/issues/2403
includes some quality of life improvements:
-  one press to open files/folders
-  folder icons are now dynamic to reflects whether they are expanded
and some other bugs:
-  if you deleted a file that is opened but not currently selected, you'll close the incorrect tab
- dragging info in the file tree doesn't adopt to light/dark mode. now it does
> egui: fix file tree regressions caused by workspace 

- libs/content/workspace/src/tab/image_viewer.rs
fixes [#2325](https://github.com/lockbook/lockbook/issues/2325)
> workspace: add scrolling to images

- libs/content/workspace/src/tab/pdf_viewer.rs
while doing https://github.com/lockbook/lockbook/pull/2509,  i encountered the same issue that caused PDF panning to be broken. I figured out how to fix it for images, so I'm porting this fix for pdfs too.
by broken scrolling, previously if you zoom, horizontal left panning was limited. you weren't able to pan back to the start of the document.
fixes #2511
> workspace: fix pdf horizontal panning

- Cargo.lock
- clients/egui/src/lib.rs
- clients/linux/src/window.rs
- clients/windows/src/window.rs
- libs/content/workspace-ffi/src/android/android_ffi.rs
- libs/content/workspace-ffi/src/apple/common_ffi.rs
- libs/content/workspace-ffi/src/lib.rs
fixes https://github.com/lockbook/lockbook/issues/2482
me:
> I took some measurements and wgpu::SurfaceTexture.present() is taking >30ms per frame. Is that normal? Can you suggest troubleshooting next steps?
chatgpt:
> Experiment with disabling VSync or using adaptive sync techniques if your application's performance profile allows for it.
me:
> I disabled vsync by passing wgpu::PresentMode::Immediate. Now my timing statements indicate that configuring the surface is taking ~30ms
chatgpt:
> To optimize and avoid unnecessary reconfigurations (and thus minimize delays), you should track the current configuration of the surface and only reconfigure when there's an actual change in the parameters (e.g., width, height, or present_mode). As there's no direct wgpu API call to retrieve the …
> windows: only reconfigure surface when resized

- clients/egui/src/account/tree/mod.rs
- clients/egui/src/account/tree/node.rs
- clients/egui/src/account/tree/state.rs
- clients/windows/src/input/pointer.rs
- clients/windows/src/window.rs
...and improve file scroll experience.
fixes https://github.com/lockbook/lockbook/issues/2487
also fixes an issue where dragging a file down past the bottom of the tree view would scroll indefinitely
also fixes an issue where dragging wouldn't register if you did it too quickly bc by the frame the drag registered, the cursor would already be over a different file (could be worked around by dragging sideways on the file first, then dragging it to destination)
demo (2nd half is touch-only):
https://github.com/lockbook/lockbook/assets/6198756/bb86c55c-fb83-4981-b9d1-65574c8231c6
> windows/egui: long press to right click

- clients/linux/src/window.rs
In practice we get a request repaint every ~1s, leading to a passive fps of 1
fixes https://github.com/lockbook/lockbook/issues/2355
> linux: only redraw on event or request

- libs/content/workspace-ffi/src/apple/ios_ffi.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
> apple: fix double tap to switch to previous tool on canvas 

- clients/egui/src/lib.rs
- clients/linux/src/window.rs
- clients/windows/src/input/message.rs
- clients/windows/src/input/mouse.rs
- clients/windows/src/input/pointer.rs
- clients/windows/src/window.rs
* rework event loop to match linux (decreases CPU from ~5% to ~1% with no visible degradation)
* adds event queues for the next two frames (supports quick, one-frame pen contacts)
* fix all sorts of egregious errors in pointer logic (e.g. pointer releases without corresponding presses)
* _disable long press right-clicks because they are causing infuriating pen input delay_
> windows: drawing refinements

- clients/apple/lockbook.xcodeproj/project.pbxproj
- clients/egui/src/account/mod.rs
- clients/egui/src/account/syncing.rs
- libs/content/workspace/src/tab/pdf_viewer.rs
- libs/content/workspace/src/theme/icons.rs
- libs/content/workspace/src/theme/visuals.rs
- libs/content/workspace/src/widgets/button.rs
- libs/content/workspace/src/widgets/progress_bar.rs
- libs/content/workspace/src/workspace.rs
fixes #2464 
other changes in this PR:
- avoids polluting std out by removing  a `println!("8")` statement in workspace that happened after each file rename.  
- displays storage percentage in a smart way
- fix this bug noted in qa: offline mode doesn't work on egui because the error text does not wrap
---
related issues to sync on egui that this pr can impact:
- #2244
> egui: fix outdated sync status bug

- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/pen.rs
- libs/content/workspace/src/tab/svg_editor/selection.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
- libs/content/workspace/src/tab/svg_editor/zoom.rs
fixes: #2478, #2530
other issues relating to drawing for ios (by order of importance):
> canvas: pan and zoom on ios 

- libs/content/workspace/src/tab/svg_editor/selection.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
> canvas: fix empty selection on tool switch

- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/svg_editor/zoom.rs
- libs/content/workspace/src/widgets/toolbar.rs
- libs/content/workspace/src/workspace.rs
fixes #2572, #2497
small writeup on how i addressed this issue. it's fixed for now, but there's underlying focus issue that we need to deal with in the near future. 
**so what's the problem?** 
when the tab strip is scrollable, it gets focus away from the editor which mans that if you want to click on the editor you'll end up scrolling on the scrollbar instead. This focus behavior only happens in the editor and not on canvas. 
**how is this problem fixed?**
surprisingly if you nest the scrollarea inside of a horizontal layout `ui.horizonal()`, all the focus problems go away!!! my hypothesis is that if two scrollareas are sibling they might fight for focus but if you nest one the un-nested scrollarea will have higher priority and get the focus.
> workspace: can't edit documents with a scrollable tab strip

- libs/content/workspace/src/workspace.rs
fixes #2500 
this is a hot fix, I think a redesign of the tab strip is warranted. needs more modern look that looks well across all of our clients and robust features like: 
- re-ordering tabs
- #2104
> workspace: center x on tab strip

- libs/content/workspace/src/tab/svg_editor/toolbar.rs
> canvas: remap redo to command+shift+z

- Cargo.lock
- libs/lb/lb-rs/Cargo.toml
- libs/lb/lb-rs/libs/shared/Cargo.toml
- server/server/Cargo.toml
To publish `lb-rs` on [crates.io](https://crates.io/crates/lb-rs), we can't have relative path dependencies. Initially I thought this would require a more substantial change but cargo has explicit support for [this situation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations). Study the behavior of [resolver](https://doc.rust-lang.org/cargo/reference/resolver.html) to reason about how this is going to behave for us. But as far as I can tell here are the salient implications:
- locally it's going to use the relative path
- when we bump the version, if we just bump the patch, no further action is required
- if we bump the minor (or maj) version, cargo will fail to compile because the, so the person performing the bump will have to go through and fix …
> core: publish lb-rs to crates.io

- clients/egui/src/account/syncing.rs
each time you make a file change (delete,upsert, create, share, etc), you'd get a warning that you're workspace is dirty. Given that we auto sync, there's no need to flash out a message immediately after one change makes the workspace dirty. 
this pr sets a limit of **at least 6 changes for the warning to be displayed.** this way the user is informed about the dirty state when they're offline, or experiencing sync issues that without being annoyed in their normal day to day use.
> egui: less frequent dirty state warnings

- Cargo.lock
- clients/egui/Cargo.toml
- libs/content/workspace/Cargo.toml
- libs/content/workspace/src/tab/markdown_editor/mod.rs
Native fonts for the Apple platforms and Android.
**Android**
<details>
Before:
After:
</details>
**Apple (macOS)**
<details>
Before:
After:
</details>
fixes #1626
> apple, android: fonts

- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/pen.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
- fixes the behavior where if you start drawing in canvas, the toolbar  will unintentionally be scrolled.
- makes the toolbar more responsive to resizing the window as the scrollbar is dynamically added and removed depending on the available window width.
> canvas: fix toolbar drag scroll

- clients/egui/src/lib.rs
- clients/windows/src/output/clipboard_copy.rs
- clients/windows/src/window.rs
* fixes an egui client issue where clipboard would be written each frame
* gracefully handles clipboard write errors on windows, which were crashing the app
> windows/linux: clipboard fixes

- Cargo.lock
- libs/lb/lb-rs/Cargo.toml
- libs/lb/lb-rs/libs/shared/Cargo.toml
- server/server/Cargo.toml
meat and potatoes of this work can be found here: https://github.com/lockbook/db-rs/pull/21
will eliminate data corruption issues for 
- egui devs
- corner cases on desktop where multiple windows can be spawned
- cli users
pre-requisite to: #2207 
pre-requisite to: multiple cores on one machine (clis and desktop apps) not duplicating their data
and ultimately: #2207
> core, server: upgrade db-rs to use flocks

- Cargo.lock
- libs/lb/lb-rs/Cargo.toml
- server/server/Cargo.toml
- server/server/src/billing/billing_model.rs
- server/server/src/billing/billing_service.rs
- server/server/src/billing/google_play_client.rs
- server/server/src/billing/google_play_service.rs
- server/server/src/billing/stripe_client.rs
- server/server/src/billing/stripe_service.rs
<details>
```
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 627 security advisories (from /Users/parth/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (857 crate dependencies)
Crate:     libgit2-sys
Version:   0.14.2+1.5.1
Title:     Memory corruption, denial of service, and arbitrary code execution in libgit2
Date:      2024-02-06
ID:        RUSTSEC-2024-0013
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0013
Severity:  8.6 (high)
Solution:  Upgrade to >=0.16.2
Dependency tree:
libgit2-sys 0.14.2+1.5.1
└── git2 0.16.1
└── shadow-rs 0.21.0
└── lockbook-server 0.9.1
└── lb-rs 0.9.1
├── workspace 0.9.1
│   ├── workspace-ffi 0.9.1
│   ├── lockbook-windows 0.9.1
│   ├── lockbook-linux 0.9.1
│   ├── …
```
> infra: appease cargo audit

- libs/content/workspace/src/tab/markdown_editor/appearance.rs
- libs/content/workspace/src/tab/markdown_editor/bounds.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/galleys.rs
- libs/content/workspace/src/tab/markdown_editor/input/canonical.rs
- libs/content/workspace/src/tab/markdown_editor/input/capture.rs
- libs/content/workspace/src/tab/markdown_editor/input/cursor.rs
- libs/content/workspace/src/tab/markdown_editor/input/mod.rs
fixes https://github.com/lockbook/lockbook/issues/2236
Changes behavior to process hover reveal debounce per-ast-text-range for the head/tail ranges of all ast node ancestors of the hovered ast node. The result is that you can smoothly reveal and un-reveal syntax for nested ast nodes. Also fixed a bunch of bugs.
https://github.com/lockbook/lockbook/assets/6198756/5a6d4ca4-e50d-47d5-bce3-5d9ea5fe0453
> editor: rework syntax hover reveal

- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/WorkspaceView.swift
- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift
- libs/content/workspace-ffi/src/apple/ios_ffi.rs
- libs/content/workspace-ffi/src/resp.rs
- libs/content/workspace/src/output.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/theme/icons.rs
- libs/content/workspace/src/widgets/toolbar.rs
- libs/content/workspace/src/workspace.rs
I added a "hide keyboard" button and "create link" button. The "hide keyboard" button will only be shown when the keyboard is shown. The "create link" button is straightforward, and will simply insert the link markdown syntax around what's selected.
note: the hide keyboard button won't be on Android devices, since Android (the OS itself) already allows the user to hide their keyboard
fixes #2682
fixes #2089
> iOS, android: hide keyboard and insert link toolbar buttons

- Cargo.lock
- libs/content/workspace/Cargo.toml
- libs/content/workspace/src/tab/markdown_editor/images.rs
- libs/content/workspace/src/tab/svg_editor/clip.rs
- libs/content/workspace/src/tab/svg_editor/eraser.rs
- libs/content/workspace/src/tab/svg_editor/history.rs
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/parser.rs
- libs/content/workspace/src/tab/svg_editor/pen.rs
- libs/content/workspace/src/tab/svg_editor/selection/mod.rs
- libs/content/workspace/src/tab/svg_editor/selection/rect.rs
- libs/content/workspace/src/tab/svg_editor/selection/scale.rs
- libs/content/workspace/src/tab/svg_editor/selection/translate.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
- libs/content/workspace/src/tab/svg_editor/util.rs
- libs/content/workspace/src/tab/svg_editor/zoom.rs
- libs/content/workspace/src/theme/palette.rs
- libs/content/workspace/src/theme/visuals.rs
- libs/content/workspace/src/workspace.rs
fixes: #2531 #2278 
x axis is the number of anchors in a drawing
1.  path segments are disjointed on a high zoom level
2. path color doesn't adjust to light/dark mode switch
> canvas: replace resvg with epaint

- clients/egui/src/model.rs
- clients/linux/src/input/clipboard_paste.rs
- clients/windows/src/input/clipboard_paste.rs
- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/macMTK.swift
- libs/content/workspace-ffi/src/apple/common_ffi.rs
- libs/content/workspace/src/tab/image_viewer.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/images.rs
- libs/content/workspace/src/tab/markdown_editor/input/events.rs
- libs/content/workspace/src/tab/mod.rs
- libs/content/workspace/src/tab/svg_editor/clip.rs
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/parser.rs
* fixes https://github.com/lockbook/lockbook/issues/2694
* fixes https://github.com/lockbook/lockbook/issues/2480
* fixes an issue where all images were imported with .png extensions
* fixes an issue where non-png images weren't imported as images
* fixes an issue where the editor crashes when you drop an unsupported file (now it just does nothing)
* updates supported image file extensions to include all the supported image file extensions
https://github.com/lockbook/lockbook/assets/6198756/806d3a3e-7a98-43f6-8ef5-28ee0ae42884
> workspace: image refinements

- clients/egui/src/account/mod.rs
- clients/egui/src/account/modals/help.rs
- clients/egui/src/account/modals/search.rs
- clients/egui/src/account/tree/node.rs
- libs/content/workspace/src/workspace.rs
macos quality is not super important here because we don't release it, but launching the egui app on macos is the easiest way for me to iterate on the editor and mac-friendly shortcuts make that nicer
qa on macos:
- this opens spotlight/alfred instead, seems just a bad choice of shortcut for mac (that's what cmd+l is for)
- alt+h does not open the help menu (not a regression)
- not working (not a regression)
qa on linux or windows:
- alt+h does not open the help menu (not a regression)
- not working (not a regression)
opened these issues:
- https://github.com/lockbook/lockbook/issues/2692
- https://github.com/lockbook/lockbook/issues/2693
> egui: improve keyboard shortcuts on macos

- Cargo.lock
- libs/content/workspace/Cargo.toml
- libs/content/workspace/src/tab/markdown_editor/bounds.rs
following the [recommendation from linkify's readme](https://github.com/robinst/linkify):
>If you need to validate URLs, e.g. for checking TLDs, use another library on the returned links.
> editor: more conservative link detection

- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/images.rs
- libs/content/workspace/src/tab/markdown_editor/input/events.rs
- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/tab/mod.rs
- libs/content/workspace/src/workspace.rs
The first time a new document was opened, it was sending suggested file names every frame, and workspace spawned a thread to handle each rename asynchronously (and not necessarily in order). Not sure how to measure all the performance benefits of not spawning a thread each frame, but it could only fix performance issues that occur after creating markdown documents.
Also did some data model cleanup because some fields had been duplicated and had inconsistent/poor names.
before:
https://github.com/lockbook/lockbook/assets/6198756/fe696d44-ca96-4c0b-9063-20691cd90987
after:
https://github.com/lockbook/lockbook/assets/6198756/b3b67d71-6527-4b40-b71b-f9af20b5737c
> editor: suggested filename refinements

- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/iOSMTK.swift
- libs/content/workspace-ffi/SwiftWorkspace/Sources/Editor/macMTK.swift
- libs/content/workspace-ffi/src/apple/common_ffi.rs
- libs/content/workspace-ffi/src/lib.rs
we stopped return repaint_after and the integration fell back to continuous redraws
https://discord.com/channels/1014184997751619664/1026208854280777789/1253746606855950428
> apple: fix the energy consumption problem

- libs/content/workspace-ffi/src/apple/ios_ffi.rs
- libs/content/workspace/src/tab/markdown_editor/input/mutation.rs
fixes https://github.com/lockbook/lockbook/issues/2528
To debug this, I started by tediously adding print statements to everything in ios_ffi.rs to indicate what was being called. I also printed the results of those calls (with an '->' arrow) just for the functions that were interesting to me during the process.
For the following logs, I reproduced the bug using a sample document containing only a single character 'X', then clicked after it and observed the cursor being placed before it. Before the changes here, a sample log looked like this:
```
touches_began: 4436965872 51.33333 59.333332 0.0
current_tab
update_virtual_keyboard: false
current_tab
update_virtual_keyboard: false
...
current_tab
update_virtual_keyboard: false
get_selected
position_at_point: CPoint { x: 51.33332824707031, …
```
> ios/editor: fix end of line cursor placement

- libs/content/workspace-ffi/src/lib.rs
- libs/content/workspace-ffi/src/resp.rs
- libs/content/workspace/src/output.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/workspace.rs
> editor: cleanup state and output

- libs/content/workspace-ffi/cbindgen.toml
- libs/content/workspace-ffi/src/lib.rs
[cbindgen](https://github.com/mozilla/cbindgen) is configured using `cbindgen.toml` and needs help deciding how to translate conditionally compiled code. Instead of supporting filters like "only generate C bindings for apple" it maps cfg's to C preprocessor define's so someone on the C side can use a flag to enable/disable compilation. Basically, cbindgen needs help translating the conditions for compiling Rust functions into conditions for compiling C functions.
In C, this is done by defining variables for the preprocessor and checking if those are defined. I'm not sure exactly the mechanism but there are variables that are defined based on the target platform and [references](https://github.com/cpredef/predef/blob/master/OperatingSystems.md) are available.
This PR adds a config to …
> infra: address cbindgen warnings

- clients/apple/iOS/ConstrainedHomeView.swift
Consistent with the empty folder "look" on Android.
https://github.com/user-attachments/assets/db72cc18-af4c-4e99-bba9-2aef99d10bce
fixes #2742 
fixes #2739
> ios: change empty folder icon and make refreshable

- libs/content/workspace/src/tab/markdown_editor/ast.rs
- libs/content/workspace/src/tab/markdown_editor/bounds.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
...also present in XCode log output. Pasting any multi-line content from XCode logs crashed the editor before this change.
> editor: support windows-style line endings

- clients/apple/Shared/Views/DeleteConfirmationButtons.swift
- clients/apple/Shared/Views/ListFileCell.swift
- clients/apple/Shared/Views/PlatformView.swift
- clients/apple/iOS/OutlineView/OutlineBranch.swift
- clients/apple/iOS/OutlineView/OutlineContextMenu.swift
- clients/apple/iOS/OutlineView/OutlineRow.swift
- clients/apple/iOS/OutlineView/SheetState.swift
- clients/apple/lockbook.xcodeproj/project.pbxproj
- clients/apple/macOS/TreeView/DataSource.swift
- clients/apple/macOS/TreeView/MenuItems.swift
I added delete confirmation dialogs for all platforms. On iOS and iPadOS, I moved the delete buttons to the bottom of the context menus and made them red.
iOS:
iPadOS:
macOS:
fixes #2360
> apple: delete confirmation

- clients/apple/iOS/FilePathBreadcrumb.swift
> ios: auto-scroll breadcrumb on folder open

- clients/android/build.gradle
Google Play requires that we upgrade our google play billing version (previously `5.0.0`), to a version above `6.0.1`. I took the liberty of updating to the newest version, and since our usage is minimal, we didn't need to change much. I sanity checked billing.
fixes #2743
> android: update google play billing to version 7

- Cargo.lock
- libs/content/workspace-ffi/Cargo.toml
- libs/content/workspace-ffi/src/apple/ios/api.rs
- libs/content/workspace-ffi/src/lib.rs
- libs/content/workspace/Cargo.toml
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/pen.rs
- libs/content/workspace/src/tab/svg_editor/renderer.rs
- libs/lb/lb-rs/src/service/log_service.rs
fixes #2790
better observability for canvas. currently most of the added spans are traces that can be added to your lockbook.log if you ran the app with a trace log level env variable.
> workspace tracing

- Cargo.lock
- clients/apple/lockbook.xcodeproj/xcshareddata/xcschemes/Lockbook (iOS).xcscheme
- libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/iOSMTK.swift
- libs/content/workspace/Cargo.toml
- libs/content/workspace/src/tab/svg_editor/clip.rs
- libs/content/workspace/src/tab/svg_editor/eraser.rs
- libs/content/workspace/src/tab/svg_editor/history.rs
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/tab/svg_editor/parser.rs
- libs/content/workspace/src/tab/svg_editor/pen.rs
- libs/content/workspace/src/tab/svg_editor/renderer.rs
- libs/content/workspace/src/tab/svg_editor/selection/mod.rs
- libs/content/workspace/src/tab/svg_editor/selection/rect.rs
- libs/content/workspace/src/tab/svg_editor/selection/scale.rs
- libs/content/workspace/src/tab/svg_editor/selection/translate.rs
- libs/content/workspace/src/tab/svg_editor/toolbar.rs
- libs/content/workspace/src/tab/svg_editor/util.rs
- libs/content/workspace/src/tab/svg_editor/zoom.rs
- libs/content/workspace/src/theme/icons.rs
- libs/content/workspace/src/workspace.rs
- libs/lb/lb-rs/src/service/log_service.rs
- performance optimizations and better input events processing that minimize input latency. fixes #2791 
- procreate like handling of canceled touch events to avoid phantom strokes fixes #2689 
- remove crashes in selections.  fixes #2792 
- lock viewport changes when drawing a path
- experimental highlighter tool
- brush tool (pen tool with non svg compliant pressure support)
- pen tool refactor that isolates event processing logic allowing unit tests. 
https://github.com/user-attachments/assets/de3daf49-b46d-4abc-b013-bb6f07c743d0
<details>
<summary>work history</summary>
</details>
optimizations done in this pr bring a low latency pen tool, but more can be done to decrease latency:
> canvas: perf improvements and more phantom strokes detection 

- libs/content/workspace/src/workspace.rs
Reverts lockbook/lockbook#2874 because it breaks ipad's ability to close tabs maybe
> Revert "workspace: close tab on pointer release"

- libs/lb/lb-rs/src/service/document_service.rs
After encountering a 2nd `FileNonexistent` error this week, I found this in my logs:
```
2024-10-04T13:57:54.959856Z DEBUG write_document{id=f6a7ad3d-ffc3-44d1-9d6a-ce4cd9b32bf7}: lb_rs::service::document_service: skipping doc cleanup due to active sync
```
This indicates the importance of using [`cleanup()`](https://github.com/lockbook/lockbook/blob/master/libs/lb/lb-rs/src/service/document_service.rs#L92-L104), which accounts for whether we're actively syncing, to clean up old file versions as we did before merging the safe-writes branch (collaborative editing).
> core: fix safe_writes race condition

- libs/content/workspace/src/tab/markdown_editor/bounds.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/input/capture.rs
fixes https://github.com/lockbook/lockbook/issues/2724
- removes paragraph-based capture
- does not un-capture line when command is held because that makes no sense for cmd+v and most others
- does have problem where cmd+right does not necessarily leave you at end of line if capture changes (same as obsidian)
- capture updates for selection applied on release instead of on click (same as obsidian)
- hover mechanism still works while drag-selecting
- hovering an image reveals syntax without flicker (not demo'd)
https://github.com/user-attachments/assets/ae451098-b1c9-4d31-92ae-6c8abb20f43d
> editor: capture refinements

- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/find.rs
- libs/content/workspace/src/tab/markdown_editor/input/mod.rs
- libs/content/workspace/src/tab/markdown_editor/input/mutation.rs
- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/widgets/toolbar.rs
- libs/content/workspace/src/workspace.rs
fixes https://github.com/lockbook/lockbook/issues/2186
It's not the prettiest or most full-featured, but it has enough to get us started:
* focus
* cmd+f opens the toolbar using the selected text as the initial search term
* cmd+f focuses the toolbar if it was already open without modifying the search term
* cmd+f while toolbar is focused closes it (focus returns to editor)
* esc while toolbar is focused also closes it
* tab while toolbar is focused does nothing
* search
* match count updated when search term updated (not when text updated)
* enter (or button) advances cursor to next match after current cursor (shift+enter/other button for previous)
* things that are missing
* highlight search results (enter advances selection to next result which is sort of fine)
* indicator of which …
> editor: find in document mvp

- clients/egui/src/account/modals/mod.rs
- libs/content/workspace/src/tab/markdown_editor/mod.rs
requested by @BuriedInTheGround
what this pr accomplishes: 
- don't abruptly close settings if you change toolbar settings 
- don't render the toolbar if it's disabled. 
what's missing:
- persist toolbar visibility state across sessions.  #2936
> egui: don't close settings when changging toolbar vis

- libs/content/workspace-ffi/src/android/init.rs
- libs/content/workspace/src/tab/markdown_editor/input/events.rs
fixes: https://github.com/lockbook/lockbook/issues/2942
qa:
> android: fix context menu

- libs/content/workspace/src/tab/markdown_editor/editor.rs
fixes https://github.com/lockbook/lockbook/issues/2729
Toolbar almost no longer needs a 'dismiss virtual keyboard' button. Maybe still useful when there's not enough content to make the area scrollable.
The keyboard gets dismissed if you scroll whatsoever. This is more ~~aggressive~~ responsive than other apps I tried but I prefer it.
> editor: scroll to dismiss virtual keyboard

- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/markdown_editor/style.rs
- libs/content/workspace/src/tab/markdown_editor/widgets/find.rs
- libs/content/workspace/src/tab/markdown_editor/widgets/toolbar.rs
- libs/content/workspace/src/theme/icons.rs
- libs/content/workspace/src/widgets/icon_button.rs
- libs/content/workspace/src/widgets/mod.rs
- libs/content/workspace/src/workspace.rs
* fixes https://github.com/lockbook/lockbook/issues/2978
* moves find below toolbar on desktop
* fixes find layout (elements were inconsistently vertically aligned)
* gives toolbar & find buttons visual indicators for being hovered and pressed
* gives toolbar & find buttons tooltips
* toolbar & find buttons set an appropriate cursor icon when hovering
<details>
</details>
> editor: toolbar and find refinements

- libs/content/workspace/src/background.rs
- libs/content/workspace/src/workspace.rs
In the foreground we determine that a user is active if they've done something within the last 10s. If they're active we sync every 5 seconds.
If its been more than 5 seconds or the app is in the background we sync every hour.
Obviously we don't sync automatically if it's disabled.
fixes #3018
> ws: reduce sync aggression

- libs/content/workspace/src/tab/mod.rs
- libs/content/workspace/src/workspace.rs
Maha [reported](https://discord.com/channels/1014184997751619664/1026211549678936214/1301582912746946631) a bug where text she was writing before randomly appeared in a second instance as if it was a remote change.
How could this happen? I added instrumentation and `thread::sleep()`'s to saves and loads to find out. Here's annotated output from my instrumentation. Numbers indicate content length and I did nothing but append to the file during the test:
```
┌── load began (0)
└── load completed:	0
text "a" x2
┌ save began:		2
│ text "a" x5
┌┼ save began:		7
│└ save completed:	2
│  text "a" x5
│┌ save began:		12
└┼ save completed: re-read required (7)
┌─┼ load began 		(2 or 12)
│ │ text "a" x6
│┌┼ save began:		18
││└ save completed:	12
└┼─ load completed:	12
│  text "a" x2
│  text " "
│ …
```
> workspace: prevent a tab from saving and loading concurrently

- clients/cli/src/debug.rs
- clients/cli/src/main.rs
- libs/lb/lb-rs/src/service/account.rs
- libs/lb/lb-rs/src/service/activity.rs
- libs/lb/lb-rs/src/service/admin.rs
- libs/lb/lb-rs/src/service/billing.rs
- libs/lb/lb-rs/src/service/debug.rs
- libs/lb/lb-rs/src/service/documents.rs
- libs/lb/lb-rs/src/service/file.rs
- libs/lb/lb-rs/src/service/import_export.rs
- libs/lb/lb-rs/src/service/integrity.rs
- libs/lb/lb-rs/src/service/logging.rs
- libs/lb/lb-rs/src/service/network.rs
- libs/lb/lb-rs/src/service/path.rs
- libs/lb/lb-rs/src/service/search.rs
- libs/lb/lb-rs/src/service/share.rs
- libs/lb/lb-rs/src/service/sync.rs
- libs/lb/lb-rs/src/service/usage.rs
- authors a file anytime a crash is detected
- debug_info now will show the last crash as part of it's output
- amount of logs shown is reduced 
- instrumentation has been updated to show elapsed times
- logs have been expanded to include workspace and other modules
fixes #1110 
fixes #2456
> lb-rs: improve logging

- libs/lb/lb-rs/src/model/account.rs
We want to be able to ship risky features like collaboration, but also people are trying to depend on our platform in a more serious capacity. This introduces a lightweight way to determine if a user is a beta user.
This would also be a lightweight way to give an ultra conservative way to add opt in telemetry for this category of user. Telemetry will always be opt-in on lockbook, but potentially we may make the opt in mechanism not require a github account in the future (to record consent).
In that spirit @tvanderstad your approval is required for this PR.
hashes the username and takes the first three bytes of the has as rgb values
the deterministic color experiment:
anywhere in the app you see someone's name, a UI developer has the choice to show the
color associated with the username. …
> lb: username based feature flags & colors

- Cargo.lock
- clients/egui/Cargo.toml
- clients/linux/Cargo.toml
- clients/windows/Cargo.toml
- libs/content/editor/egui_editor/Cargo.toml
- libs/content/workspace/Cargo.toml
- libs/lb/lb-rs/Cargo.toml
- utils/dev-tool/Cargo.toml
- utils/releaser/Cargo.toml
try to use rustls-tls for everything. I believe we did native-tls for windows on arm but I see some language in the BUILDING.md that makes me feel like it shouldn't be a problem: https://github.com/briansmith/ring/blob/main/BUILDING.md
if we need to we can re-introduce native-tls just for windows, possibly just for windows on arm. But as it stood we were depending on native-tls for everything which is an annoying dependency to satisfy everywhere.
> all: no openssl

- libs/content/workspace-ffi/src/lib.rs
- libs/content/workspace/src/theme/visuals.rs
This affects Android and Apple. Mainly did this for iPadOS. This does not affect the egui clients.
iPadOS:
<details>
Main Screen before:
Main Screen after:
Editor before:
Editor after:
</details>
macOS
<details>
Main Screen before:
Main Screen after:
Editor before:
Editor after:
</details>
> workspace: change background fill

- clients/egui/src/account/modals/file_picker.rs
- clients/egui/src/account/tree.rs
- libs/content/workspace/src/tab/markdown_editor/input/events.rs
- libs/content/workspace/src/widgets/button.rs
Fixes the following issues based on @Parth's feedback in [discord](https://discord.com/channels/1014184997751619664/1026208854280777789/1319090707558039665):
Made issues for unaddressed feedback:
* https://github.com/lockbook/lockbook/issues/3225
* https://github.com/lockbook/lockbook/issues/3226
* https://github.com/lockbook/lockbook/issues/3227
* https://github.com/lockbook/lockbook/issues/3228
<details>
</details>
> egui: file tree refinements

- libs/lb/lb-rs/src/service/keychain.rs
OnceCell is like an ergonomic Mutex that you only get to set once.
However I thought it was an `Arc<Mutex<T>>`, but it is not. So tasks that may have cloned core before an InitialSync has completed (and the Keychain is populated).
#3200
@smailbarkouch heads up:
This possibly also fixes some bad state that android gets in as described by @ad-tra here: https://github.com/lockbook/lockbook/issues/3203 
well it may not solve the issue, but it probably addresses the `AccountNonexistent` in that log line.
but we were skeptical that log line was correctly attributed to the issue @ad-tra was having.
> lb-rs: fix inital syncs on probably a lot of platforms

- libs/content/workspace/src/show.rs
introduced by https://github.com/lockbook/lockbook/pull/3256
> workspace: fix mixed up tab responses

- clients/egui/src/account/mod.rs
- clients/egui/src/account/modals/mod.rs
- clients/egui/src/account/syncing.rs
- libs/content/workspace-ffi/src/android/api.rs
- libs/content/workspace-ffi/src/android/response.rs
- libs/content/workspace-ffi/src/apple/api.rs
- libs/content/workspace-ffi/src/apple/ios/response.rs
- libs/content/workspace-ffi/src/apple/macos/response.rs
- libs/content/workspace/src/output.rs
- libs/content/workspace/src/show.rs
- libs/content/workspace/src/syncing.rs
- libs/content/workspace/src/tab/markdown_editor/editor.rs
- libs/content/workspace/src/tab/mod.rs
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/task_manager.rs
- libs/content/workspace/src/workspace.rs
- libs/lb/lb-rs/src/repo/mod.rs
- libs/lb/lb-rs/src/service/documents.rs
- libs/lb/lb-rs/src/service/file.rs
- libs/lb/lb-rs/src/service/logging.rs
- libs/lb/lb-rs/src/service/network.rs
- libs/lb/lb-rs/src/service/sync.rs
- libs/lb/lb-rs/src/svg/buffer.rs
- libs/lb/lb-rs/src/svg/element.rs
**changes**
- tab content is now copied for save when the save is launched (rather than when it's queued) and canvas contents are now serialized on a background thread
- tasks once again rely on periodic check-ins from the UI thread via workspace (required to prevent file self-conflicts)
- introduces a tab `is_closing` ("purgatory") state which collapses the tab's tab to just a status indicator and removes it when all dependent tasks are complete (i.e. if a save was in progress, finish saving the tab before closing)
- closing a tab now generally just moves it to this state
- we check each frame if it's ready to close
- some interactions (like opening the file again) will remove the state leaving the tab as a normal tab
- clean ups including removal of unpopulated/unused fields …
> workspace: task management refinements

- clients/admin/src/main.rs
- clients/cli/src/lb_fs.rs
- clients/cli/src/main.rs
- clients/egui/src/splash.rs
- libs/content/editor/egui_editor/src/main.rs
- libs/lb-fs/src/lib.rs
- libs/lb/lb-c/src/lib.rs
- libs/lb/lb-java/src/lib.rs
- libs/lb/lb-rs/src/model/core_config.rs
- libs/lb/lb-rs/src/service/logging.rs
- libs/lb/lb-rs/src/service/search.rs
- libs/lb/lb-rs/tests/cli_data_tests.rs
- libs/lb/test_utils/src/lib.rs
* fixes cli output (see below) by introducing `stdout_logs` config
* `false` for `admin`, `cli`
* `true` for `egui`, `lbfs`, `lb-c`, `lb-java`
* reduces code duplication by introducing helper fn for ui config (similar to helper for cli config)
* cleans up writeable path usage
* `egui`: removed duplicate code
* `lbfs`: removed duplicate code
cli output on master:
```
❯ lockbook list
2025-01-10T19:13:02.840528Z DEBUG  new
at libs/lb/lb-rs/src/service/search.rs:200
in spawn_build_index
2025-01-10T19:13:02.840636Z DEBUG  close, time.busy: 22.0µs, time.idle: 240µs
at libs/lb/lb-rs/src/service/search.rs:200
in spawn_build_index
2025-01-10T19:13:02.840716Z DEBUG  new
at libs/lb/lb-rs/src/service/file.rs:102
in root
2025-01-10T19:13:02.843366Z DEBUG  close, time.busy: 2.59ms, time.idle: 76.0µs
at …
```
> all: logging refinements

- libs/content/workspace-ffi/src/apple/ios/api.rs
fixes https://github.com/lockbook/lockbook/issues/3047
I did record a demo but didn't bother uploading because it looks exactly how you'd expect.
> ios: fix double tap space to insert period

- libs/lb/lb-rs/src/model/errors.rs
- libs/lb/lb-rs/src/service/integrity.rs
- libs/lb/lb-rs/tests/cli_data_tests.rs
- 95% of the time was taken reading every document serially.
- this does have some value -- we get to check to make sure we can decrypt every document, but these checks fully overlap with our metadata assertions (if you can decrypt filename you can prob decrypt document)
- we're also going to move to a world where all docs aren't present locally
- so I made two changes here: only try to validate text files 
- and do this in parallel
- it's much faster from the CLI now, probably will be even faster in other settings once long lived caches are saturated by organic use
fixes #3164
> lb-rs: 50x time debug_info takes

- server/src/account_service.rs
- server/src/billing/app_store_service.rs
- server/src/billing/billing_service.rs
- server/src/billing/google_play_service.rs
- server/src/billing/stripe_service.rs
- server/src/file_service.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/metrics.rs
- server/src/router_service.rs
- we're not supposed to hold a std lib mutex across an await point
- there's some places we do this and we could trivially not (some billing code)
- there's some places we do this and it's a bit tricky (`error!` will invoke pagerduty).
- we could solve this nicely using channels, and I would also like tracing-gcp to nicely stream directly to gcp using channels
- I would also like one user's problems to not impact another user (#3063 is when I'll take a thorough pass over server concerns).
- I believe the nature of the deadlock was something like: q a pages (while holding std lib mutex), while there are n requests in the queue. The call to pagerduty likely needs to take a certain amount of time alongside n being sufficiently large.
- this used to happen once in a blue moon but either as a …
> server: resolve deadlock

- clients/egui/src/account/mod.rs
- clients/egui/src/account/syncing.rs
- libs/content/workspace-ffi/src/android/api.rs
- libs/content/workspace-ffi/src/apple/api.rs
- libs/content/workspace-ffi/src/apple/ios/api.rs
- libs/content/workspace-ffi/src/lib.rs
- libs/content/workspace/src/file_cache.rs
- libs/content/workspace/src/mind_map/show.rs
- libs/content/workspace/src/show.rs
- libs/content/workspace/src/syncing.rs
- libs/content/workspace/src/tab/mod.rs
- libs/content/workspace/src/tab/svg_editor/mod.rs
- libs/content/workspace/src/task_manager.rs
- libs/content/workspace/src/workspace.rs
...and some visual updates
* updates tab data model so not all tabs need a file
* re-adds mind map button to workspace landing page
* fixes problems when mind map is the only tab
* fixes problems when creating a file while mind map is open
* fixes problems closing mind map via the tab strip button
<details>
</details>
> workspace: not all tabs are files

- libs/content/workspace/src/workspace.rs
This prevents the tab from being "unknown" in the time between when a file is created and when the file cache is refreshed.
Fix verified on iOS and on egui on macOS
> workspace: synchronously add new files to file cache

- Cargo.lock
- libs/lb/lb-rs/Cargo.toml
`cargo check --tests -p lb-rs`
> lb-rs: removed diffy dependency

- Cargo.lock
- clients/egui/Cargo.toml
`cargo check --tests -p lockbook-egui`
I don't see anything related to these two dependencies in the specified package in cargo.toml should be safe to remove
> removed minidom and lbeditor dependencies

- clients/windows/src/input/file_drop.rs
- clients/windows/src/input/message.rs
- Tried to annotate types for transmute()
- Removed an unused import
- added #[allow(dead_code)] for Message struct to suppress unused struct fields warnings
> windows: new clippy warnings

- libs/lb/lb-rs/src/subscribers/search.rs
adds support for id & lb:// style searches.
If any query greater than 8 characters is contained within a Uuid, the path associated with that Uuid will be returned as the highest scoring result.
fixes: https://github.com/lockbook/lockbook/issues/2718
> lb-rs: path & link search

- Cargo.lock
- clients/windows/Cargo.toml
> lockbook-windows: Removed unused dependencies

- .github/workflows/github-release.yml
- .github/workflows/publish-crate.yml
- utils/releaser/src/utils.rs
PS: Crate publishing is expected to fail due to the expiration of the cratesio auth token
crate publishing now listens on manual releases (if needed), `workflow_dispatch` and `workflow_call`
Tested on my fork by running the release workflow
> infra: fix crate publishing not triggering

- libs/content/workspace/src/tab/markdown_editor/galleys.rs
fixes #3077 
tested scenarios:
- short doc 1-2 lines
- medium doc ~3/4 the screen size
- long doc 100's of lines
- doc with very long single line
on platforms:
- egui on macos
- macos
- ios
> editor: fix scroll with long final line

- clients/apple/Shared/Screens/OnboardingView.swift
fixes #3547: api_url was nil
also fixed some critical elided text. Used to be this:
and is now this:
> apple: onboarding QA bugfixes

- libs/lb-fs/Cargo.toml
To make it easier to find it from the standard locations More explanation: https://github.com/szabgab/rust-digger/issues/89
> (chore) Update Cargo.toml add repository field

- clients/apple/iOS/Screens/DetailView.swift
Updates the tab look and also shows it when only 1 document is open.
> apple: update tab icon

- clients/apple/Shared/State/BillingState.swift
- clients/apple/Shared/State/SettingsViewModel.swift
- libs/content/workspace-ffi/SwiftWorkspace/Sources/Workspace/Lb/Billing.swift
- server/src/billing/billing_service.rs
Fixes
+ Show billing correctly for apple (if subscription expired, don't show premium)
+ Prevent double spend for subscription id
> apple: fix billing issues

- libs/content/workspace/src/tab/markdown_editor/galleys.rs
- libs/content/workspace/src/tab/markdown_editor/input/cursor.rs
fixes https://github.com/lockbook/lockbook/issues/3682
The logic for rendering the cursor and for deciding where it is for the purposes of arrow key navigation were out-of-sync. This PR makes the cursor rendering logic depend on the same logic as arrow key navigation and fixes arrow key navigation by updating it to match the previous cursor rendering logic i.e. preferring a later galley when at a boundary between galleys. This matters when there are two galleys that contain the cursor location and those galleys would render that cursor location in different places, which to my knowledge only happens when text wraps.
> editor: fix stuck cursor

- libs/lb-fs/src/file_handle.rs
- libs/lb-fs/src/fs_impl.rs
- libs/lb-fs/src/lib.rs
with recent switch to nfs3_server, there is no need to resolve fileid into its uuid
> nfs3: remove id lookups

- libs/content/workspace/src/tab/markdown_editor/mod.rs
Some weirdness with wrapping text, not sure if that's due to the font.
> workspace: add back sf fonts for apple platforms

- libs/content/workspace/src/tab/markdown_editor/mod.rs
fixes an issue where framerates were stuck at max when scrolled past the very top of the editor
evidence of low framerates for desktop & mobile:
> editor: fix scroll updated detection

- libs/content/workspace/src/tab/markdown_editor/widget/block/leaf/paragraph.rs
> editor: fix paragraphs getting too much space

- libs/content/workspace/src/tab/markdown_editor/widget/block/leaf/paragraph.rs
> editor: show images above paragraph lines containing them

- libs/content/workspace/src/tab/markdown_editor/widget/inline/image/image.rs
> editor: show image error messages

- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/tab/markdown_editor/widget/block/container/mod.rs
- libs/content/workspace/src/tab/markdown_editor/widget/block/container/table_row.rs
- libs/content/workspace/src/tab/markdown_editor/widget/block/mod.rs
- libs/content/workspace/src/tab/markdown_editor/widget/block/spacing.rs
- libs/content/workspace/src/tab/markdown_editor/widget/mod.rs
This raises the max fps from ~5 to 90 for a 750kb document of headings, paragraphs, lists, and code blocks on my M3 Max (and from ~1 to 60 on my iPhone 13 Pro). It reduces significant waste by re-using results of expensive calls or eliminating them entirely. It also only shows blocks that are visible in the viewport.
https://github.com/user-attachments/assets/10cfb987-79d4-445e-ab4c-ae8ae4b72ecd
> editor: performance fixes

- libs/content/workspace/src/tab/markdown_editor/widget/block/container/mod.rs
Fixes a bug introduced in https://github.com/lockbook/lockbook/pull/3771 where navigating with arrowkeys to positions that were off-screen wouldn't work, including cmd+down, which navigates to the end of the doc
> editor: fix arrowkey navigation for viewport culling

- libs/content/workspace/src/show.rs
as requested by @steverusso this is a tweak & a new feature.
- on non apple devices, you can now jump to a tab via alt + tab number (in addition to control + number)
- you can now also re-order tabs via the keyboard. on apple the shortcut is <kbd>cmd</kbd> <kbd>ctrl</kbd> <kbd>shift</kbd> <kbd>[</kbd>or<kbd>]</kbd>. on linux the shortcut is <kbd>ctrl</kbd> <kbd>shift</kbd> <kbd>page up</kbd> or<kbd>page down</kbd>.
> ws: better tab shortcuts

- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/tab/markdown_editor/widget/inline/image/cache.rs
- libs/content/workspace/src/tab/markdown_editor/widget/utils/text_layout.rs
fixes an issue where text was wrapping without creating enough space for the next row when the row ended within half a pixel of the right side
<details>
</details>
fixes an issue where images were only creating enough space for the loading placeholder even after loading
<details>
</details>
> editor: layout fixes

- clients/apple/Shared/Widgets/SyncButton.swift
When syncing, the SyncButton shows a spinner. That spinner was hard to see since it was black, I made it white.
> apple: fix macOS progress spinner color

- libs/content/workspace-ffi/src/apple/ios/api.rs
- libs/content/workspace/src/tab/markdown_editor/output/ui_text_input_tokenizer.rs
fixes an issue raised in [discord](https://discord.com/channels/1014184997751619664/1026208854280777789/1409333850248577066)
<details>
https://github.com/user-attachments/assets/1a1e9dae-58dc-4357-bd6b-edd8a7199607
</details>
> editor: fix opening iOS context menu after autocorrected word

- Cargo.lock
- clients/cli/Cargo.toml
- clients/cli/src/main.rs
- libs/lb-fs/Cargo.toml
- libs/lb-fs/src/main.rs
this is going to improve the experience here #3611.
required code change to cli-rs here: https://github.com/lockbook/cli-rs/commit/824292feb5687599e297d247235875fdd2dad2c0
which changed it to not exit internally rather propagate errors up.
our previous strategy made it so `Drop`s were never called on the way up for the CLI which resulted in a good bit of ugliness. This fixes that.
> cli: graceful shutdowns and fewer ugly messages

- libs/lb/lb-rs/src/io/docs.rs
- libs/lb/lb-rs/src/service/debug.rs
- libs/lb/lb-rs/src/service/documents.rs
fixes #3607 
fixes #3611 
tightens up the handling of our docs which would buckle under the stress of many concurrent docs.
our cleanup fn was super aggressive, it would delete any file that was unreferenced by a file tree, but the way it managed it's logic it could delete a file that was being added by a mass import or a sync.
this pr more intentionally cleans up files during writes -- it knows what the old file is, and if it needs to be cleaned up (a local overwrite) then it will specifically delete that one file.
it also eliminates a bunch of things that were `tokio::spawn`'d to the background which performed poorly in CLI like environments, this is possible now that the logic is lighter.
and then lastly the logic error was corrected in cleanup allowing it to be invoked aggressively …
> lb-rs: fix problems with heavy concurrent doc writes

- libs/lb/lb-rs/src/model/api.rs
- libs/lb/lb-rs/src/subscribers/search.rs
- server/src/account_service.rs
- server/src/billing/billing_model.rs
- server/src/config.rs
- server/src/defense.rs
- server/src/file_service.rs
- server/src/lib.rs
- server/src/main.rs
- server/src/metrics.rs
- server/src/router_service.rs
- server/src/schema.rs
- better logs
- bandwidth monitoring and limits
- you can only create an account from the same IP once per minute
deployment notes:
- `FEATURE_NEW_ACCOUNT_LIMITS` needs to be `true`
> server: bandwidth controls

- clients/egui/src/account/tree.rs
- libs/content/workspace/src/show.rs
- libs/content/workspace/src/tab/markdown_editor/mod.rs
- libs/content/workspace/src/task_manager.rs
- libs/content/workspace/src/workspace.rs
- Fixes an issue when clicking the egui file tree where the file tree withheld focus from the opened file
- Fixes an issue where egui file tree renames would always focus the file tree when done instead of the editor
- Fixes an issue where changing the current tab would not update which tab is focused
- Files opened with the `make_current` flag are now made current only when the load completes
- This makes the fix simpler because loading state tabs don't manage focus, which needs to be actively held every frame
https://github.com/user-attachments/assets/eb058a0f-b205-4d1c-b216-5bda3d19bc40
> editor/egui: focus fixes
